--[[
    init.lua
    Created: 02/06/2023 12:18:05
    Description: Autogenerated script file for the map treasuretownbeach.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local treasuretownbeach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---treasuretownbeach.Init
--Engine callback function
function treasuretownbeach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---treasuretownbeach.Enter
--Engine callback function
function treasuretownbeach.Enter(map)

GROUND:Hide('AdamMudkip')
GROUND:Hide('Piks')
GROUND:Hide('Madilyn')
GROUND:Hide('Poipole')
GROUND:Hide('Lapras')

treasuretownbeach.chapterhidescript()

COMMON.WeatherApply()

  SOUND:FadeInSE("Beach_Noise")
  GAME:FadeIn(20)

end

---treasuretownbeach.Exit
--Engine callback function
function treasuretownbeach.Exit(map)

SOUND:FadeOutSE("Beach_Noise")

end

---treasuretownbeach.Update
--Engine callback function
function treasuretownbeach.Update(map)


end

---treasuretownbeach.GameSave
--Engine callback function
function treasuretownbeach.GameSave(map)


end

---treasuretownbeach.GameLoad
--Engine callback function
function treasuretownbeach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function treasuretownbeach.SeaInteract_Action(obj, activator)
local player = CH('PLAYER')

	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("(Look at that view...)")
	
	GAME:FadeOut(false, 20)
	
	UI:WaitShowBG("SeaLook", 1, 20);
	GAME:WaitFrames(30)
	
	UI:WaitShowDialogue("(I wouldn't be surprised if this is a common place to sit down and relax.)")
	
	UI:WaitHideBG(20);
	GAME:FadeIn(20)

end

function treasuretownbeach.InteractiveFar_Touch(obj, activator)

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
    GROUND:CharSetEmote(activator, "exclaim", 1)

end

function treasuretownbeach.BeachCaveEntrance_Touch(obj, activator)
local player = CH('PLAYER')

	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("(Maybe later, [pause=15]it's not in my interest to explore here.)")

end

function treasuretownbeach.BeachLeave_Touch(obj, activator)

	GAME:FadeOut(false, 20)
	GAME:EnterGroundMap("treasuretownbeachpath", "Entrance2")

end

function treasuretownbeach_TurnRight_Sequence(character)
GROUND:CharAnimateTurn(character, Direction.DownRight, 4, true)
end

function treasuretownbeach_MoveCamWithMove_Sequence(character)
GROUND:MoveInDirection(character, Direction.Right, 70, false, 2)
end

function treasuretownbeach_MoveCamWithMove2_Sequence(character)
GAME:MoveCamera(487, 200, 30, false)
end

function treasuretownbeach.Madilyn_Action(chara, activator)
GROUND:CharTurnToChar(chara,activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("If you're ready, [pause=10]go talk to [color=#54ebaf]Adam[color].")

end

function treasuretownbeach.AdamMudkip_Action(chara, activator)
GROUND:CharTurnToChar(chara,activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Are you ready to head out?")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Er, [pause=10]wait. [pause=0]That's not ready yet.")
UI:WaitShowDialogue("Sorry.")
end

function treasuretownbeach.Piks_Action(chara, activator)

GROUND:CharTurnToChar(chara,activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("What will we learn at Paleté, [pause=10]anyways?")
UI:WaitShowDialogue("I'm not sure, [pause=10]but it's worth a shot.")
end

function treasuretownbeach.Poipole_Action(chara, activator)
GROUND:CharTurnToChar(chara,activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("You're pretty lucky to find that, [pause=10]aren't you?")
end

function treasuretownbeach.Krabby_Action(chara, activator)
GROUND:CharTurnToChar(chara, activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Me thinks I'm too early to start using [color=#07db00]Bubble[color] right now.")
UI:WaitShowDialogue("I'm a little bit bored right now.")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['KrabbyMeme']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
    UI:WaitShowDialogue("PRESTO!")
	
	local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Dig", 3))
	emitter.LocHeight = 5
	GROUND:PlayVFX(emitter, 319, 203)
	SOUND:PlayBattleSE("DUN_Dig")
	GROUND:Hide("Krabby")
else
	UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("Oh.")
end

end

function treasuretownbeach.chapterhidescript()
if SV.chapter.number == 0 then

GROUND:Hide("Krabby")

elseif SV.chapter.number == 1 then --This is completely unprofessional, stupid, and probably bloating to the script, and Groundmap file,
															--But I want to keep everything tidey so ***I*** know what went wrong, and not jumble through several files.


end

end

return treasuretownbeach

