--[[
    init.lua
    Created: 06/28/2024 20:09:39
    Description: Autogenerated script file for the map cutsceneintrofinal7.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutsceneintrofinal7 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneintrofinal7.Init(map)
--Engine callback function
function cutsceneintrofinal7.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutsceneintrofinal7.Enter(map)
--Engine callback function
function cutsceneintrofinal7.Enter(map)

StoryCS()

end

---cutsceneintrofinal7.Exit(map)
--Engine callback function
function cutsceneintrofinal7.Exit(map)


end

---cutsceneintrofinal7.Update(map)
--Engine callback function
function cutsceneintrofinal7.Update(map)


end

---cutsceneintrofinal7.GameSave(map)
--Engine callback function
function cutsceneintrofinal7.GameSave(map)


end

---cutsceneintrofinal7.GameLoad(map)
--Engine callback function
function cutsceneintrofinal7.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function StoryCS()
local player = CH('PLAYER')
local Medallion = OBJ('Medallion') --This looks dumb, but trust me, it's necessary.

GAME:CutsceneMode(true)
GAME:MoveCamera(192, 156, 1, false)

UI:WaitShowTitle("Several hours later,\nat Branchway Woods...", 90);
GAME:WaitFrames(60);
UI:WaitHideTitle(60);

UI:WaitShowBG("IntroSky", 1, 30)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
SOUND:PlayBGM("There's Trouble.ogg", true)

GAME:WaitFrames(20)

UI:WaitShowDialogue("What'chu got there? [pause=0]Some stupid coin?")

GAME:WaitFrames(10)

UI:WaitShowDialogue("It's not some dumb coin! [pause=0]Get away from me, [pause=10]you thieves!")
UI:WaitShowDialogue("This is mine, [pause=10]and you two can't have it!")

GAME:WaitFrames(10)

UI:WaitShowDialogue("Let's hurry and rob this [color=#00FFFF]Zorua[color], [pause=10][color=#00FFFF]Thievul[color]! [pause=0]They look like they got something worthwhile.")
UI:WaitShowDialogue("Hi-yah!")

SOUND:PlayBattleSE("DUN_Stomp")
GAME:WaitFrames(20)
SOUND:PlayBattleSE("DUN_Sucker_Punch")
GAME:WaitFrames(20)
SOUND:PlayBattleSE("EVT_Tackle")
GAME:WaitFrames(40)

UI:WaitShowDialogue("Ah-how! [pause=0]Fine! [pause=0]You want rough, [pause=10]I'll give you rough!")
UI:WaitShowTimedDialogue("Hah!", 30)

SOUND:PlayBattleSE("DUN_Throw_Start")
GAME:WaitFrames(10)
SOUND:PlayBattleSE("DUN_Throw_Arc")
GAME:WaitFrames(10)
SOUND:PlayBattleSE("EVT_Tackle")
GAME:WaitFrames(5)
SOUND:PlayBattleSE("DUN_Blast_Seed")
GAME:WaitFrames(30)
SOUND:PlayBattleSE("DUN_Eruption")

GAME:FadeOut(true, 1)
SOUND:PlayBGM("None", true)
UI:WaitHideBG(10)

local coro1 = TASK:BranchCoroutine(function()

UI:WaitShowTimedDialogue("Waaaahhhhh....!!!", 60)

end)

local coro2 = TASK:BranchCoroutine(function()
SOUND:PlayBattleSE("EVT_EP_Pitfall_Fall")
end)

TASK:JoinCoroutines({coro1,coro2})

GAME:WaitFrames(30)

UI:WaitShowDialogue("Got'cha! [pause=0]How do you like that!?")
GAME:WaitFrames(40)
UI:WaitShowDialogue("...Huh? [pause=0]Oh no, [pause=10]I threw the medallion with the [color=#32a852]Blast Seed[color]!")
UI:WaitShowDialogue("Oh great... [pause=20]where could that thing even end up at in this stupid forest...?")

GAME:WaitFrames(90)
GAME:FadeIn(40)
GAME:WaitFrames(30)

local coro1 = TASK:BranchCoroutine(function()
GROUND:MoveToPosition(player, 192, 156, false, 2)
end)

local coro2 = TASK:BranchCoroutine(function()
GAME:WaitFrames(30)
SOUND:PlayBattleSE("_UNK_EVT_048")
GROUND:MoveObjectToPosition(Medallion, 192, 156, 3)
end)

TASK:JoinCoroutines({coro1,coro2})

SOUND:PlayBattleSE("SingleCoin")
SOUND:PlayBattleSE("DUN_Iron_Head")
GAME:FadeOut(true, 5)
GAME:FadeIn(5)

coro1 = TASK:BranchCoroutine(function()

GROUND:AnimateInDirection(player, "Hurt", Direction.Left, Direction.Right, 15, 4, 4)
GROUND:CharSetAnim(player, "Hurt", true)

end)

coro2 = TASK:BranchCoroutine(function()

GROUND:MoveObjectToPosition(Medallion, 188, 152, 1)
GROUND:MoveObjectToPosition(Medallion, 184, 150, 1)
GROUND:MoveObjectToPosition(Medallion, 178, 150, 1)

end)

GAME:WaitFrames(20)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Dizzy")
UI:WaitShowDialogue("(Ooww... [pause=20]what even was that...?)")

GROUND:CharSetAnim(player, "None", true)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Left)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.DownLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Left)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Left)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.DownLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Left)

GAME:WaitFrames(40)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(player, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Huh? [pause=0]Is that the thing that hit me? [pause=0]What is that...?)")

GROUND:MoveInDirection(player, Direction.Left, 30, false, 2)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(30)

UI:WaitShowDialogue("(Hm... [pause=20]just looks like some big, [pause=10]muddy thing to me...)")

GROUND:MoveInDirection(player,Direction.Left, 14, false, 1)
GROUND:CharAnimateTurn(player, Direction.Up, 4, false)

UI:WaitShowDialogue("(What even is this...?)")
UI:WaitShowDialogue("(I think there's supposed to be something here, [pause=10]but it's too muddy to tell...)")

GROUND:Hide("Medallion")
SOUND:PlayBattleSE("_UNK_EVT_018")

GAME:WaitFrames(30)

UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(Guess I'll take it with me.)")
UI:WaitShowDialogue("(Someone might be looking for it...)")

GROUND:CharAnimateTurn(player, Direction.Left, 4, true)
GROUND:MoveInDirection(player, Direction.Left, 90, false, 2)

GAME:WaitFrames(30)
GAME:FadeOut(false, 30)

GAME:WaitFrames(40)

GAME:EnterGroundMap("cutsceneintrofinalactualreal8", "Entrance")

GAME:CutsceneMode(false)

end

return cutsceneintrofinal7

