--[[
    init.lua
    Created: 12/22/2022 21:56:05
    Description: Autogenerated script file for the map cutscenezone.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutscenezone = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---cutscenezone.Init
--Engine callback function
function cutscenezone.Init(zone)


end

---cutscenezone.EnterSegment
--Engine callback function
function cutscenezone.EnterSegment(zone, rescuing, segmentID, mapID)


end

---cutscenezone.ExitSegment
--Engine callback function
function cutscenezone.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---cutscenezone.Rescued
--Engine callback function
function cutscenezone.Rescued(zone, name, mail)


end

return cutscenezone

