--[[
    init.lua
    Created: 04/16/2024 00:03:57
    Description: Autogenerated script file for the map cutsceneintrosnowplace3.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutsceneintrosnowplace3 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneintrosnowplace3.Init(map)
--Engine callback function
function cutsceneintrosnowplace3.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutsceneintrosnowplace3.Enter(map)
--Engine callback function
function cutsceneintrosnowplace3.Enter(map)

StoryTime()

end

---cutsceneintrosnowplace3.Exit(map)
--Engine callback function
function cutsceneintrosnowplace3.Exit(map)


end

---cutsceneintrosnowplace3.Update(map)
--Engine callback function
function cutsceneintrosnowplace3.Update(map)


end

---cutsceneintrosnowplace3.GameSave(map)
--Engine callback function
function cutsceneintrosnowplace3.GameSave(map)


end

---cutsceneintrosnowplace3.GameLoad(map)
--Engine callback function
function cutsceneintrosnowplace3.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function StoryTime()
local player = CH('PLAYER')
local Hoopa = CH('Hoopa')
GAME:CutsceneMode(true)

GAME:WaitFrames(20)
GROUND:CharSetAnim(Hoopa, "Sleep", true) --300 304
GROUND:AddMapStatus("blizzard")
GAME:MoveCamera(300, 304, 1, false)

UI:ResetSpeaker()
UI:WaitShowDialogue("One day, [pause=10]".. CH('PLAYER'):GetDisplayName() .." wandered in the arctic regions on ".. COMMON.GenderCheck(player, "their", false) .." journey as part of a detour...")
UI:WaitShowDialogue("But something caught ".. COMMON.GenderCheck(player, "their", false) .." eye... [pause=20]a wounded Pokémon in need of help in the middle of a snow storm...")

GAME:WaitFrames(20)
GAME:FadeIn(30)

SOUND:PlayBGM("B36. Mysterious Passage 2.ogg", true, 20)

GROUND:MoveInDirection(player, Direction.Up, 40, false, 2)
GROUND:EntTurn(player, Direction.UpLeft)

GAME:WaitFrames(10)
GROUND:CharSetEmote(player, "question", 1)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GAME:WaitFrames(40)

UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Huh...? [pause=0]What is that Pokémon doing...?")

GROUND:MoveInDirection(player, Direction.UpLeft, 20, false, 1)

local coro1 = TASK:BranchCoroutine(function()

SOUND:PlayBattleSE("EVT_Emote_Startled")
GROUND:AnimateInDirection(player, "Hurt", Direction.UpLeft, Direction.DownRight, 5, 4, 2)

end)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, Hoopa.CurrentForm.Species, Hoopa.CurrentForm.Form, Hoopa.CurrentForm.Skin, Hoopa.CurrentForm.Gender)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Nnf, [pause=10]please...")
UI:WaitShowDialogue("My sister...")

GROUND:MoveInDirection(player, Direction.UpLeft, 17, true, 2)
GROUND:MoveInDirection(player, Direction.Left, 10, true, 2)
GROUND:EntTurn(player, Direction.Left)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Surprised")
UI:WaitShowTimedDialogue("Now's not the time to be talking! [pause=0]Hurry and eat this [color=#32a852]Oran Berry[color], [pause=10]before-", 5)

GAME:WaitFrames(10)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, Hoopa.CurrentForm.Species, Hoopa.CurrentForm.Form, Hoopa.CurrentForm.Skin, Hoopa.CurrentForm.Gender)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue(GenderCheck(player, "buddy", true) ..", [pause=10]forget about me! [pause=0]My sister's all alone on the 15th floor of this dungeon...!")
UI:WaitShowDialogue("You must rescue her before they hurt her...!")

GROUND:AnimateInDirection(player, "Walk", Direction.Left, Direction.Right, 10, 4, 2)
GROUND:CharAnimateTurn(player, Direction.Up, 4, false)

GAME:WaitFrames(20)

UI:ResetSpeaker()
UI:WaitShowDialogue("As ".. CH('PLAYER'):GetDisplayName() .." looked into the cavern ahead, [pause=10]".. COMMON.GenderCheck(player, "they", false) .." couldn't just leave the wounded Pokémon there...")
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they", true) .." needed to act now if ".. COMMON.GenderCheck(player, "they", false) .." wanted to save this Pokémon's sister in time, [pause=10]however.")
UI:WaitShowDialogue("But ".. COMMON.GenderCheck(player, "their", false) .." body was so conflicted, [pause=10]fighting if this stranger was lying to ".. COMMON.GenderCheck(player, "them", false) .."...")
UI:WaitShowDialogue("Surely, [pause=10]this Pokémon wasn't lying to ".. COMMON.GenderCheck(player, "them", false) .." about it... [pause=20]Who could jest about a serious situation like that?")
UI:WaitShowDialogue("Acting on instinct alone, [pause=10]".. CH('PLAYER'):GetDisplayName() .." cleared any doubt in ".. COMMON.GenderCheck(player, "their", false) .." head...")

GROUND:EntTurn(player, Direction.UpRight)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Up)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Up)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.UpRight)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Up)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(3)
GROUND:EntTurn(player, Direction.Up)

GAME:WaitFrames(10)

GROUND:CharAnimateTurn(player, Direction.Left, 4, true)

GAME:WaitFrames(10)

UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("I'll save your sister, [pause=10]don't worry!")
UI:WaitShowDialogue("You need to get to town before you freeze out here!")

GROUND:CharAnimateTurn(player, Direction.UpRight, 4, false)
GAME:WaitFrames(5)

coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(player, Direction.UpRight, 20, true, 2)
GROUND:MoveInDirection(player, Direction.Up, 60, true, 2)
end)

local coro2 = TASK:BranchCoroutine(function()
SOUND:FadeOutBGM(60)
GAME:FadeOut(false, 40)
end)

GAME:WaitFrames(120)

UI:ResetBounds()
UI:ResetSpeakerLoc()
GAME:MoveCamera(-164, 325, 1, false) --Why did I do this, again?
GROUND:RemoveMapStatus("blizzard")

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("...Heh...")
UI:WaitShowDialogue("...Heh-heh...")
UI:WaitShowDialogue("Heh-heh-heh...!")
UI:WaitShowDialogue("Grah-hah-hah-ha!!!")

local pcSpecies = _DATA:GetMonster(CH('PLAYER').CurrentForm.Species):GetColoredName()

UI:SetSe("Menu/SpeakBadGuy")
UI:WaitShowDialogue("What a stupid fool! [pause=0]".. COMMON.GenderCheck(player, "they", true) .." wanted to be the hero so badly!")
UI:WaitShowDialogue("Now I got a little runt to help me with my little magic trick!")
UI:WaitShowDialogue("Once I get my abilities' unhindered power back from that stupid bottle...")
UI:WaitShowDialogue("...I will plunge this world back into it's lawless form!")
--UI:WaitShowDialogue("I will control these dungeons to make those 'peace lovers' cower and fear this world once more!")
UI:WaitShowDialogue("And this time, [pause=10]I won't mess it up!")

--GAME:FadeIn(1)
--Because the Camera is OOB, it should just immediately go to a black screen.
--SOUND:PlaySE("PR_Transition_Edited")

--UI:WaitShowBG("PurpleHueScreen", 1, 20);
GAME:WaitFrames(20);
--UI:WaitHideBG(120);

--GAME:FadeOut(true, 20)

--GAME:WaitFrames(60)


UI:WaitShowBG("RainySky", 1, 30)
SOUND:PlayBGM("In the Future.ogg", true)
GAME:WaitFrames(30)
--SOUND:FadeInSE('eos intro wind+rain2', 20)

UI:ResetSpeaker()
UI:WaitShowDialogue("Not everything was as it seemed, [pause=10]however...")
UI:WaitShowDialogue("Unknowingly, [pause=10]".. CH('PLAYER'):GetDisplayName() .." was sent on a wild [color=#00FFFF]Golduck[color] chase.")
UI:WaitShowDialogue("...Why? [pause=0]The Pokémon ".. COMMON.GenderCheck(player, "they were", false) .." helping was dubbed '[color=#00FFFF]Hoopa[color]'.")
UI:WaitShowDialogue("An ancient being, [pause=10]sealed away in [color=#32a852]Djinn's Bottle[color] to prevent the world's chaos from spreading.")

GAME:WaitFrames(30)
UI:WaitHideBG(30)
--SOUND:FadeOutSE("eos intro wind+rain2", 30)

UI:WaitShowDialogue("But the seal is not permanent. [pause=0]Only recently has [color=#00FFFF]Hoopa[color] been able to use it's powers again.")
UI:WaitShowDialogue("With it, [pause=10]they can bend this dimension's rules, [pause=10]and summon Pokémon from a different time altogether...")
UI:WaitShowDialogue("Even without those powers, [pause=10][color=#00FFFF]Hoopa[color] possesses strong psychic abilities to manipulate the world around it.")
UI:WaitShowDialogue("Thank [color=#00FFFF]Arceus[color] it couldn't change what is already here...")

GAME:WaitFrames(30)

UI:WaitShowDialogue("As ".. CH('PLAYER'):GetDisplayName() .." ventured deeper into the dungeon, [pause=10]the blizzard only gotten worse...")
UI:WaitShowDialogue("And soon enough, [pause=10]".. COMMON.GenderCheck(player, "they", false) .." reached the pit of the dungeon...")

SOUND:PlayBGM("None", true)
GAME:WaitFrames(15)

GAME:EnterGroundMap("cutsceneintrobottle", "Entrance")

GAME:CutsceneMode(false)

end

function GenderCheck(chara, form, uppercase)

    local gender = chara.CurrentForm.Gender --Ripped straight from Halcyon / I should really put this in the Common.LUA thing instead of this, this is messy af. / THEY KEEP EXISTING
    local value = ""
    
    if gender == Gender.Female then
        local female_pronouns = {
            ["buddy"] = "miss",
        }
        value = female_pronouns[form]
    elseif gender == Gender.Male then
        local male_pronouns = {
            ["buddy"] = "mister", 
        }
        value = male_pronouns[form]
    else -- if neither male or female, use they/them, so just return the form 
        value = form
    end

return uppercase and value:gsub("^%l", string.upper) or value

end

return cutsceneintrosnowplace3

