--[[
    init.lua
    Created: 02/11/2023 15:20:14
    Description: Autogenerated script file for the map wigglyguildbedsun.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildbedsun = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildbedsun.Init
--Engine callback function
function wigglyguildbedsun.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildbedsun.Enter
--Engine callback function
function wigglyguildbedsun.Enter(map) --shouldn't matter, you're not supposed to go back in this room after leaving it, so this cutscene triggers every time. / How the tables have turned.
GROUND:Hide("oobloudred") --there's a reason for everything.

if SV.repeatable.day_finished == true then
  wigglyguildbedsun.dailygetup(loud)
  end
  
  GAME:FadeIn(20)
end

---wigglyguildbedsun.Exit
--Engine callback function
function wigglyguildbedsun.Exit(map)


end

---wigglyguildbedsun.Update
--Engine callback function
function wigglyguildbedsun.Update(map)


end

---wigglyguildbedsun.GameSave
--Engine callback function
function wigglyguildbedsun.GameSave(map)


end

---wigglyguildbedsun.GameLoad
--Engine callback function
function wigglyguildbedsun.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function wigglyguildbedsun.Sign_Action(obj, activator)

UI:ResetSpeaker()
UI:SetCenter(true)
UI:SetAutoFinish(true)
UI:WaitShowDialogue("'GET UP ALREADY!' -Loudred")

UI:WaitShowDialogue("Oh, there seems to be more.")

UI:WaitShowDialogue("'EXCEPT [color=#54ebaf]MADILYN[color], SHE'S TOO SCARY!' -Loudred")
UI:SetCenter(false)
UI:SetAutoFinish(false)

end

function wigglyguildbedsun.dailygetup(loud)
local oobloudred = CH('oobloudred')
local player = CH('PLAYER')
SOUND:PlayBGM("None", true)
  
  SOUND:PlaySE("Battle/EVT_Emote_Complain")
  UI:SetSpeaker(oobloudred)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("RISE AND SHINE, [pause=10]SUNSHINE!")
  
  SOUND:PlaySE("Battle/EVT_Emote_Startled")
  GAME:WaitFrames(20)
  
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Dizzy")
  UI:WaitShowDialogue("(Yeowwch!)")
  SV.repeatable.day_finished = false
  GAME:WaitFrames(40)
  
  GAME:FadeIn(20)
  UI:WaitShowDialogue("(Time to get to work.)")
  SOUND:PlayBGM("Wigglytuff's Guild.ogg", true)
end

function wigglyguildbedsun.Leave_Touch(obj, activator)
	GAME:FadeOut(false, 20)

	if not SV.repeatable.daily_chant then
	GAME:EnterGroundMap("wigglyguildbottom", "EntranceDC")
	else
	GAME:EnterGroundMap("wigglyguildbedhalls", "EntranceRight")
	end
end

return wigglyguildbedsun

