--[[
    init.lua
    Created: 09/27/2025 21:00:47
    Description: Autogenerated script file for the map craggy_coast.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local craggy_coast = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---craggy_coast.Init(zone)
--Engine callback function
function craggy_coast.Init(zone)


end

---craggy_coast.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function craggy_coast.EnterSegment(zone, rescuing, segmentID, mapID)


end

---craggy_coast.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function craggy_coast.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---craggy_coast.Rescued(zone, name, mail)
--Engine callback function
function craggy_coast.Rescued(zone, name, mail)


end

return craggy_coast

