--[[
    init.lua
    Created: 11/17/2023 21:50:18
    Description: Autogenerated script file for the map eontestroom.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local eontestroom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---eontestroom.Init(map)
--Engine callback function
function eontestroom.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---eontestroom.Enter(map)
--Engine callback function
function eontestroom.Enter(map)
  SV.eontestroom.Starter = { Species="piplup", Form=1, Skin="normal", Gender=1 }
  local Madilyn = CH("Madilyn")
  local Madilyn = RogueEssence.Dungeon.CharData()
  Madilyn.BaseForm = RogueEssence.Dungeon.MonsterID(SV.eontestroom.Starter.Species, SV.eontestroom.Starter.Form, SV.eontestroom.Starter.Skin, LUA_ENGINE:LuaCast(SV.eontestroom.Starter.Gender, Gender))
  
  GROUND:SetPlayer(Madilyn)
  GROUND:Hide("Madilyn")
  GAME:FadeIn(20)

end

---eontestroom.Exit(map)
--Engine callback function
function eontestroom.Exit(map)


end

---eontestroom.Update(map)
--Engine callback function
function eontestroom.Update(map)


end

---eontestroom.GameSave(map)
--Engine callback function
function eontestroom.GameSave(map)


end

---eontestroom.GameLoad(map)
--Engine callback function
function eontestroom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function eontestroom.AdamMudkip_Action(chara, activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:ChoiceMenuYesNo("Are you ready to enter the test dungeon, Logical? This'll most likely break your save, so backup first.")
UI:WaitForChoice()
if UI:ChoiceResult() then
UI:WaitShowDialogue("Hold on, let me clear your team...")

_DATA.Save.ActiveTeam.NoRecruiting = true --Disable recruitment in this area

	local party_table = GAME:GetPlayerPartyTable()
	-- check for presence
	local in_party = false
	for ii = 1, #party_table, 1 do
	  local ent = party_table[ii]
	  if ent.IsFounder then
	    in_party = true
		break
	  end
	end
	
	-- if no, search assembly and then add to party
	if not in_party then
	  local assemblyCount = GAME:GetPlayerAssemblyCount()
  
      for i = assemblyCount,1,-1 do
        p = GAME:GetPlayerAssemblyMember(i-1)
		if p.IsFounder then
		  GAME:RemovePlayerAssembly(i-1)
		  GAME:AddPlayerTeam(p)
		end
      end
	end
	
	-- move everyone else into assembly
	local partyCount = GAME:GetPlayerPartyCount()
    for i = partyCount,1,-1 do
      p = GAME:GetPlayerPartyMember(i-1)
	  if not p.IsFounder then
		GAME:RemovePlayerTeam(i-1)
		GAME:AddPlayerAssembly(p)
	  end
    end

	local mon_id = RogueEssence.Dungeon.MonsterID("kecleon", 0, "normal", Gender.Male)
	local kecleon = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 5, "color_change", 0)
	kecleon.Discriminator = _DATA.Save.Rand:Next()--tbh idk what this is lol
	kecleon.Level = 15
	kecleon.Nickname = 'Kecleon'
	kecleon.IsPartner = true-- if they somehow manage to die, end the run / Thanks Palika.
	
	kecleon.MaxHPBonus = 10
	kecleon.AtkBonus = 0
	kecleon.DefBonus = 0
	kecleon.MDefBonus = 0
	kecleon.SpeedBonus = 0

	kecleon:ReplaceSkill("feint", 0, true)
	kecleon:ReplaceSkill("fury_swipes", 1, true)
	kecleon:ReplaceSkill("shadow_sneak", 2, true) --Causes problems because he's too aggressive lol / Feint and Shadow Sneak act the exact same, his aggressiveness has not changed.
	kecleon:ReplaceSkill("bind", 3, true)
	
	GAME:AddPlayerGuest(kecleon)
	kecleon:FullRestore()
    local talk_evt = RogueEssence.Dungeon.BattleScriptEvent("EscortInteract")
    kecleon.ActionEvents:Add(talk_evt)
	kecleon:RefreshTraits()

	local mon_id = RogueEssence.Dungeon.MonsterID("piplup", 1, "normal", Gender.Female)
	local madilyn = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 5, "defiant", 0) --This is a real Ability Piplup has, look it up.
	madilyn.Discriminator = _DATA.Save.Rand:Next()--tbh idk what this is lol
	madilyn.Level = 75
	madilyn.Nickname = 'Madilyn'
	madilyn.IsPartner = true -- if they somehow manage to die, end the run / Thanks Palika.
	
	madilyn.MaxHPBonus = 0
	madilyn.AtkBonus = 0
	madilyn.DefBonus = 0
	madilyn.MDefBonus = 0
	madilyn.SpeedBonus = 0

	madilyn:ReplaceSkill("brick_break", 0, true)
	madilyn:ReplaceSkill("aerial_ace", 1, true)
	madilyn:ReplaceSkill("bubble_beam", 2, false)
	madilyn:ReplaceSkill("protect", 3, false)
	
	GAME:AddPlayerGuest(madilyn)
	madilyn:FullRestore() --What does this function do...? / Restores their Stats so they don't appear with 0 HP.
	
	madilyn.Tactic = _DATA:GetAITactic("go_after_foes") -- Sunkern helped here.
    
	local talk_evt = RogueEssence.Dungeon.BattleScriptEvent("MadilynInteract")
    madilyn.ActionEvents:Add(talk_evt)
	--madilyn.SilentEquipItem(seed_reviver) --No idea how I make this work.
	madilyn:RefreshTraits()
	
	GAME:WaitFrames(10)
	GAME:FadeOut(false, 20)
	
	GAME:EnterDungeon('roadwalkpathway', 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, true)

else
UI:WaitShowDialogue("Alrighty then, I'll wait here patiently.")
end

end

function eontestroom.AdamBook_Action(obj, activator)

UI:ResetSpeaker()
UI:ChoiceMenuYesNo("Do you want to test Adam's book?")
UI:WaitForChoice()
	if UI:ChoiceResult() then
UI:WaitShowDialogue("I know you want to, but you're going to need to make the UI for this on a whole new Groundmap, because you're weird.")
	else

	end
end

function eontestroom.WeatherCheck_Action(obj, activator)

SV.weather.allow = true
SV.weather.rolled = false

COMMON.WeatherStatus()
UI:WaitShowDialogue("Weather rolled.")
COMMON.WeatherApply()

end

function eontestroom.Piks_Action(chara, activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")

UI:WaitShowDialogue("My dialogue changes depending on the weather.")

if SV.weather.number == 1 then

UI:WaitShowDialogue("The current weather is... Clear!")
UI:WaitShowDialogue("This is how things usually are in Story Mode.")

elseif SV.weather.number == 2 then

UI:WaitShowDialogue("The current weather is... Cloudy!")
UI:WaitShowDialogue("This is typical weather in Explorers.")

elseif SV.weather.number == 3 then

UI:WaitShowDialogue("The current weather is... Raining!")
UI:WaitShowDialogue("This can be present in Freeplay.")

else

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("That's odd, the number is not 1, 2, or 3.")
UI:WaitShowDialogue("Might wanna check the code, and try again.")

end

end


return eontestroom

