--[[
    init.lua
    Created: 07/29/2023 13:54:22
    Description: Autogenerated script file for the map electraterhome.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local electraterhome = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---electraterhome.Init(map)
--Engine callback function
function electraterhome.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---electraterhome.Enter(map)
--Engine callback function
function electraterhome.Enter(map)

electraterhome.HideChara() --Hiding characters this way is completely stupid.

	if not SV.chapter1.mission_brief then
		electraterhome.Missionbrief()
	end
	
	if SV.chapter.number == 1 and SV.chapter1.meeting_partA and not SV.chapter1.meeting_partB then
		electraterhome.Missionbrief2()
	end
	
	if SV.chapter.number == 1 and SV.chapter1.meeting_partB then
		SOUND:PlayBGM("", true) --But only *if* these are here. Might change later.
		SOUND:FadeInSE("Beach_Noise")
	end
	
	if SV.weather.number ~= 3 or 4 then

		COMMON.WeatherApply()
			if SV.weather.number == 5 then
	
			GROUND:RemoveMapStatus("rain")
			GROUND:AddMapStatus("non_colliding_rain")

		end
	end

  GAME:FadeIn(20)

end

---electraterhome.Exit(map)
--Engine callback function
function electraterhome.Exit(map)



end

---electraterhome.Update(map)
--Engine callback function
function electraterhome.Update(map)


end

---electraterhome.GameSave(map)
--Engine callback function
function electraterhome.GameSave(map)


end

---electraterhome.GameLoad(map)
--Engine callback function
function electraterhome.GameLoad(map)

  	if SV.chapter.number == 1 and SV.chapter1.meeting_partB then
		SOUND:PlayBGM("", true) --But only *if* these are here. Might change later.
		SOUND:FadeInSE("Beach_Noise")
	end
	
  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function electraterhome.InteractiveNearby_Touch(obj, activator)
	SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(activator, "question", 1)
end

function electraterhome.Ocean_Action(obj, activator)
local player = CH('PLAYER')

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(It smells like seafoam.)")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Not sure what else I expected. [pause=0]If I wanted a scenic view, [pause=10]I'd go to the beach.)")

end

function electraterhome.Fountain_Action(obj, activator)
local player = CH('PLAYER')

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(I wonder if these fountains are safe to drink from.)")
UI:WaitShowDialogue("(They seem to be everywhere, [pause=10]so I have to assume they are.)")
end

function electraterhome.Leave_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("sharpedobluff", "EntranceB")

end

function electraterhome.Missionbrief()
local player = CH('PLAYER')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')

GAME:CutsceneMode(true)
GAME:MoveCamera(240, 176, 1, false)

GROUND:MoveToPosition(player, 236, 154, true, 3)
GROUND:MoveToPosition(AdamMudkip, 248, 182, true, 3)
GROUND:MoveToPosition(Piks, 224, 182, true, 3)
GROUND:EntTurn(player, Direction.Down)
GROUND:EntTurn(AdamMudkip, Direction.Left)
GROUND:EntTurn(Piks, Direction.Right)
GAME:FadeIn(20)
GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(085,131)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['BroughtPlayer'], player:GetDisplayName()))

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Nice, [pause=10]it's about time we introduced ourselves to them properly.")

local coro1 = TASK:BranchCoroutine(function() electraterhome.rotateup(AdamMudkip) end)
local coro2 = TASK:BranchCoroutine(function() electraterhome.rotateup(Piks) end)
 
TASK:JoinCoroutines({coro1,coro2})
GAME:WaitFrames(10)

UI:WaitShowDialogue("My name is [color=#54ebaf]Adam[color]...")

if SV.prologue_alts.talked_to_adam_at_cafe >= 1 then
UI:WaitShowDialogue("You most likely already know what I do.")
else
UI:WaitShowDialogue("I'm the leader of Team [color=#ffb5fd]Electrater[color].")
end

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(085,131)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("My name's [color=#54ebaf]Piks[color], [pause=10]I'm [color=#54ebaf]Adam[color]'s partner.")
UI:WaitShowDialogue("And... [pause=20]well, that [color=#00FFFF]Piplup[color] you saw yesterday?")
UI:WaitShowDialogue("Her name's [color=#54ebaf]Madilyn[color].")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("And her demeanor is... [pause=20]something. [pause=0]She's a lone explorer.")
UI:WaitShowDialogue("I hope she's been treating you okay.")

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("She's certainly a [color=#00FFFF]Piplup[color]...")
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Anyways, [pause=10]let's go over some basic rules.")

GROUND:CharAnimateTurn(AdamMudkip, Direction.Left, 4, true)

UI:WaitShowDialogue("Do you see this Pink Scarf across [color=#54ebaf]Piks[color]' neck?")
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Yeah, [pause=10]don't touch that.")

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(085,131)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Basically, [pause=10]if you touch my scarf, [pause=10]you're going to be sleeping in for a while.")
UI:WaitShowDialogue("This special [color=#32a852]Pecha Scarf[color] causes minor poison to those who touch it.")
UI:WaitShowDialogue("But it gives me full immunity to any poison when I wear it.")
UI:WaitShowDialogue("Nobody except me and my family are allowed to touch this scarf.")

GAME:WaitFrames(10)
GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, false)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("*Ahem* Uhm, [pause=10]next rule.")
UI:WaitShowDialogue("No touching my journal.")
UI:WaitShowDialogue("It's basically my mental help book... [pause=20]kind of.")
UI:WaitShowDialogue("I write down what happens in the day before I go to bed. [pause=0]Good, [pause=10]bad, [pause=10]doesn't matter.")
UI:WaitShowDialogue("Or sometimes, [pause=10]I like to think about the past and ponder about them to myself.")
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("So, [pause=10]uh, [pause=10]no touchy. [pause=0]Again, [pause=10]if you see my paw-print, [pause=10]that's mine. [pause=0]Please don't touch it.")
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Now, [pause=10]with you being unable to speak, [pause=10]I've made up a solution on how you can still help us.")

GROUND:EntTurn(player, Direction.DownRight)
GROUND:MoveInDirection(AdamMudkip, Direction.Up, 10, false, 1)
GROUND:EntTurn(AdamMudkip, Direction.UpLeft)

SOUND:PlayBattleSE("EVT_CH02_Item_Place")
GAME:WaitFrames(30)

UI:ResetSpeaker(false)
UI:SetSpeakerEmotion("Normal")
UI:SetCenter(true)
UI:WaitShowDialogue("You recieved... [pause=20]some papers?")
UI:SetCenter(false)
GAME:WaitFrames(20)

GROUND:EntTurn(player, Direction.Down)
GROUND:AnimateInDirection(AdamMudkip, "Walk", Direction.Up, Direction.Down, 10, 2, 1)
GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Looks boring, [pause=10]doesn't it? [pause=0]That's paperwork for you.")
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Don't fret, [pause=10]this is good for you.")
UI:WaitShowDialogue("If you're asked a question, [pause=10]and it's not a 'yes-no' question, [pause=10]you can write down an answer and show them.")
UI:WaitShowDialogue("It's also where you're going to do your assignment.")
UI:WaitShowDialogue("I want you to write down whatever Pokémon you've encountered, [pause=10]and describe the dungeon itself.")
UI:WaitShowDialogue("You can write this out when you're finished with the dungeon, [pause=10]even at dinner time.")
UI:WaitShowDialogue("There are some dungeons up north that we've got reports about.")
UI:WaitShowDialogue("Your task is to head in those dungeons, [pause=10]and reach the end of them.")

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(085,131)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("And that should be it! [pause=0]Let me mark those dungeons on your map for you.")
SOUND:PlayBattleSE("_UNK_EVT_028")
GAME:WaitFrames(50)
UI:WaitShowDialogue("Your task is to explore [color=#FFC663]Mossy Outcroppings[color], [pause=10][color=#FFC663]Seaside Serenade[color], [pause=10]and [color=#FFC663]Cackling Quarry[color].")
UI:SetSpeakerEmotion("Joyous")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['EncouragePlayer'], player:GetDisplayName()))
UI:ResetSpeakerLoc()

GAME:MoveCamera(0, 0, 15, true)

SV.dungeons.mpr_mosscrop = true
SV.dungeons.mpr_seasong = true
SV.dungeons.mpr_cackle = true
SV.chapter1.mission_brief = true
SV.chapter1.sbfadein = false --This is stupid. / The game does not stop fade-out at Sharpedo Bluff unless I do this terribleness.

GAME:UnlockDungeon('mossyoutcroppings')
GAME:UnlockDungeon('seasideserenade')
GAME:UnlockDungeon('cacklingquarry')

GAME:CutsceneMode(false)

end

function electraterhome.rotateup(character)
GROUND:CharAnimateTurnTo(character, Direction.Up, 4)
end

function electraterhome.AdamMudkip_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara,player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['NeedSomethingPlayer'], false, player:GetDisplayName())) --False is {0} and player:GetDisplayName is {1}. Maybe the order of these kind of commands important?
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
    UI:WaitShowDialogue("Good to know, [pause=10]lemme think of one you could use...")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Uhm...")
	electraterhome.AdviceKip()
else
    UI:WaitShowDialogue("Alrighty then. [pause=0]If you need help, [pause=10]just ask.")
end

end

function electraterhome.AdviceKip()
local player = CH('PLAYER')
local AdamMudkip = CH('AdamMudkip')

UI:SetSpeaker(AdamMudkip)

	if SV.repeatable.asked_adam_for_help == 0 then

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Let's skip the boring nitty gritty, [pause=10]you should already know the super basic stuff.")
UI:WaitShowDialogue("Instead, [pause=10]I should share with you some of the stranger pieces I noticed.")
UI:WaitShowDialogue("For example, [pause=10]Moves. [pause=0]You most likely have seen it yourself, [pause=10]but they're different.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("[color=#54ebaf]Piks[color]' destructive [color=#07db00]Discharge[color] now actively targets and hurts me...")
UI:WaitShowDialogue("In order for me to not get hurt, [pause=10]I need to use [color=#07db00]Protect[color] before he does...")
UI:WaitShowDialogue("But that's just one example of moves changing that could change how an explorer thinks.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I'm hoping we could find the reason for that, [pause=10]but for now, [pause=10]we'll make due. [pause=0]Be safe out there.")

SV.repeatable.asked_adam_for_help = 1

	elseif SV.repeatable.asked_adam_for_help == 1 then
	
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Well, [pause=10]this'll sound boring, [pause=10]but you know about recruiting, [pause=10]yes?")
UI:WaitShowDialogue("I probably shouldn't have to tell you this, [pause=10]but [color=#32a852]Apricorns[color] are necessary to get your numbers up.")
UI:WaitShowDialogue("[color=#32a852]Plain Apricorns[color] are universal, [pause=10]but colored ones seem to work better.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I would just recommend using any colored [color=#32a852]Apricorns[color] rather than plain if you can.")
UI:WaitShowDialogue("If you don't want to recruit anyone, [pause=10]that's fine, [pause=10]but I wouldn't recommend being by yourself.")
UI:WaitShowDialogue("Your chances of making it through a dungeon increases the more members that are on your team.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("But, [pause=10]that is your choice. [pause=0]Stay safe out there.")

SV.repeatable.asked_adam_for_help = 2

	elseif SV.repeatable.asked_adam_for_help == 2 then
	
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Mystery Dungeons do live up to their name: [pause=20]Mystery Dungeons.")
UI:WaitShowDialogue("I won't take up too much time explaining, [pause=10]but dungeons come in all shapes and sizes.")
UI:WaitShowDialogue("This shouldn't be surprising, [pause=10]but hallways seemed to also have changed.")
UI:WaitShowDialogue("They might seem bigger than usual, [pause=10]or they might actually be a room.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("If you ever find yourself in a [color=#FFC663]Monster House[color], [pause=10]those hallways wouldn't be any safer.")
UI:WaitShowDialogue("Entire rooms could be halls, [pause=10]and halls could be rooms by whatever logic these dungeons run off...")
UI:WaitShowDialogue("I hope we don't find one of 'those' dungeons...")

SV.repeatable.asked_adam_for_help = 3

	elseif SV.repeatable.asked_adam_for_help == 3 then
	
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Have you found a Trap, [pause=10]yet? [pause=0]Well, [pause=10]they actually now have a use, [pause=10]believe it or not.")
--UI:WaitShowDialogue("Well, [pause=10]they actually now have a use, [pause=10]believe it or not.")
UI:WaitShowDialogue("When a Move overlaps a Trap, [pause=10]it will activate.")
UI:WaitShowDialogue("Say it's a Slow Trap, and you activated it with a lucky shot.")
UI:WaitShowDialogue("Good news, the Pokémon surrounding it are now slowed down.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("But if you activated it with a move that moves you too close, [pause=10]you'll get caught in it.")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("And if you're really unlucky to not check what that trap is before activating it... [pause=20]yikes.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("There are a bunch of traps; [pause=20]Emera-Crushing, [pause=10]Sealing, [pause=10]Chestnuts... [pause=20]and that's just what we've found.")
UI:WaitShowDialogue("But Traps and Tiles share the same rules. [pause=0]Something happens if they're triggered.")
UI:WaitShowDialogue("Do make sure you keep this in mind when you're heading out to a dungeon, [pause=10]alright?")

SV.repeatable.asked_adam_for_help = 4

	elseif SV.repeatable.asked_adam_for_help == 4 then
	
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("I assume you're someone who isn't keen with their pockets, [pause=10]right?")
	UI:WaitShowDialogue("That explains why your [color=#32a852]Treasure Bag[color] always looks full to the brim.")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Even when it's empty... [pause=10]I'm not sure if I should be concerned about that...")
	UI:WaitShowDialogue("Uhm...")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Hold these 30 sticks for me, [pause=10]please.")
	
	SOUND:PlayBattleSE("EVT_CH02_Item_Place")
	
	GAME:WaitFrames(40)
	
	SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(AdamMudkip, "question", 1)
	
	GAME:WaitFrames(40)
	
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Hm... [pause=20]I might have to teach you how to hold more than 9 per pouch...")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Well, [pause=10]that shouldn't matter for now.")
	UI:WaitShowDialogue("With your moves alone, [pause=10]any dungeon shouldn't give you that much trouble.")
	UI:WaitShowDialogue("...")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("...Can I have those sticks back, [pause=10]please?")
	
SV.repeatable.asked_adam_for_help = 5

	elseif SV.repeatable.asked_adam_for_help == 5 then
	
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I don't know if I have any more dungeon advice for you...")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['ResetAdvice']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
    UI:WaitShowDialogue("Uhm, [pause=10]alright. [pause=0]It might take a bit, [pause=10]I'll need to remember what I first said to you.")
	SV.repeatable.asked_adam_for_help = 0
else
	UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("That makes sense.")
	UI:WaitShowDialogue("Though, [pause=10]you'll know where to find me if you're ever stuck with anything, [pause=10]okay?")
end

	end

end

function electraterhome.Piks_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara,player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['EncouragePlayer'], player:GetDisplayName()))

end

function electraterhome.Missionbrief2()
local player = CH('PLAYER')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')
local Kecleon = CH('Kecleon')

GAME:CutsceneMode(true)
GAME:MoveCamera(240, 176, 1, false)

GROUND:Unhide("Kecleon")
GROUND:MoveToPosition(Kecleon, 221, 122, true, 10)
GROUND:Hide("Kecleon")

GAME:FadeIn(20)
GAME:WaitFrames(20)

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
    GROUND:CharSetEmote(Piks, "exclaim", 1)
	GAME:WaitFrames(10)
	
	GROUND:CharTurnToCharAnimated(Piks,player, 4)
	GAME:GetTeamLeaderIndex() --What is this line for?
	GAME:WaitFrames(10)
	UI:SetSpeaker(Piks)

local coro1 = TASK:BranchCoroutine(function() 
	GAME:WaitFrames(15)
	GROUND:CharSetEmote(AdamMudkip, "exclaim", 1)
	GROUND:CharTurnToCharAnimated(AdamMudkip,player, 4)
end)
local coro2 = TASK:BranchCoroutine(function()
	GAME:WaitFrames(10)
	GROUND:CharTurnToCharAnimated(player,Piks, 4) --Don't animate, no point. / Says who, jack***?
end)

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Oh, [pause=10]hey ".. CH('PLAYER'):GetDisplayName() .."! [pause=0]You must be here to report back on the assignment.") --I currently don't see a reason to use a... concatenation, for a lot of these dialogues. If it saves something, I wouldn't even know.
																																																													--Hey dumba**, it's Time you're saving, and clearly, they're a lot more useful than strings. This just makes them harder to translate to another language.

coro1 = TASK:BranchCoroutine(function()
GROUND:MoveToPosition(player, 236, 154, false, 1)
GROUND:CharAnimateTurn(player, Direction.Down, 4, false)
end)

coro2 = TASK:BranchCoroutine(function()
GROUND:MoveToPosition(AdamMudkip, 248, 182, false, 1)
GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, false)
end)

local coro3 = TASK:BranchCoroutine(function()
GROUND:MoveToPosition(Piks, 224, 182, false, 1)
GROUND:CharAnimateTurn(Piks, Direction.Up, 4, true)
end)

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Alright then, [pause=10]lemme see what you've written down.")

GROUND:MoveInDirection(player, Direction.Down, 10, false, 1)
GROUND:EntTurn(player, Direction.DownRight)
GAME:WaitFrames(10)
SOUND:PlayBattleSE("EVT_CH02_Item_Place")
GAME:WaitFrames(10)

UI:ResetSpeaker(false)
UI:SetCenter(true)
UI:WaitShowDialogue("You given [color=#54ebaf]Adam[color] your reports.")
UI:SetCenter(false)
GROUND:AnimateInDirection(player, "Walk", Direction.Down, Direction.Up, 10, 1, 1)

GROUND:EntTurn(AdamMudkip, Direction.UpRight)
GROUND:EntTurn(player, Direction.DownRight)
GROUND:CharTurnToCharAnimated(Piks, AdamMudkip, 4)
GAME:WaitFrames(40)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", false)
UI:WaitShowDialogue("... [pause=20]... [pause=20]... [pause=20]... [pause=20]... [pause=20]...")

GAME:WaitFrames(20)
GROUND:CharTurnToCharAnimated(AdamMudkip,player, 4)
GROUND:EntTurn(Piks, Direction.UpRight)

UI:SetSpeakerEmotion("Normal", true)
GROUND:EntTurn(player, Direction.Down)
UI:WaitShowDialogue("Well, [pause=10]sometimes exploration yields nothing. [pause=0]I can't blame you for not finding anything, [pause=10]".. CH('PLAYER'):GetDisplayName() ..".")
UI:SetSpeakerEmotion("Happy", true)
UI:WaitShowDialogue("But you did your job, [pause=10]so have something nice for your troubles.")

GROUND:AnimateInDirection(AdamMudkip, "Walk", Direction.Up, Direction.Up, 10, 1, 1)
GROUND:EntTurn(player, Direction.DownRight)
GROUND:EntTurn(AdamMudkip, Direction.UpLeft)
GAME:WaitFrames(10)

local itemcount = GAME:GetPlayerBagCount() + GAME:GetPlayerEquippedCount() --Equipped Items don't count as being in the Inventory. Not sure why.
local bagsize = GAME:GetPlayerBagLimit()

if itemcount >= bagsize then --Basically, check if the capacity of your items is OVER, OR AT BAGSIZE CAP (should be 16)

GAME:WaitFrames(20)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(AdamMudkip, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Uh... [pause=0]you don't mind me sending this to your storage, [pause=10]do you? [br]Your bag looks like it's about to break apart if I put anything else in there.")

UI:ResetSpeaker(false)
UI:SetCenter(true)
GAME:GivePlayerStorageItem('held_friend_bow', 1)
SOUND:PlayFanfare("Fanfare/Item")
GAME:WaitFrames(10)
UI:WaitShowDialogue("The [color=#32a852]Friend Bow[color] was sent to your storage.")

else

UI:ResetSpeaker(false)
UI:SetCenter(true)
GAME:GivePlayerItem('held_friend_bow', 1)
SOUND:PlayFanfare("Fanfare/Item")
GAME:WaitFrames(10)
UI:WaitShowDialogue("You have been awarded with the [color=#32a852]Friend Bow[color].")

end

UI:SetCenter(false)
GROUND:AnimateInDirection(AdamMudkip, "Walk", Direction.Up, Direction.Down, 10, 1, 1)
GROUND:EntTurn(player, Direction.Down)
GROUND:EntTurn(Piks, Direction.Up)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowTimedDialogue("Now, [pause=10]we don't got anything for you right now ".. CH('PLAYER'):GetDisplayName() ..", [pause=10]but if you want to, [pause=10]you can-", 30)
GAME:WaitFrames(10)

GROUND:CharSetEmote(AdamMudkip, "exclaim", 1)
GROUND:CharSetEmote(Piks, "exclaim", 1)
GROUND:CharSetEmote(player, "exclaim", 1)
SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")

UI:SetSpeaker(STRINGS:Format("\\uE040"), true)
UI:SetSpeakerEmotion("Normal")
SOUND:PlayBGM("None", true)
UI:WaitShowDialogue("[color=#ffb5fd]Electrater[color], [pause=10]you got a visitor who needs help.")

GROUND:Unhide("Madilyn")
GROUND:EntTurn(AdamMudkip, Direction.Up)
GROUND:CharAnimateTurn(player, Direction.UpLeft, 4, false)

GAME:WaitFrames(10)

	local rotationAlpha = false
	local rotationBeta = false
	local rotationCharlie = false
	local rotationPlayer = false

coro1 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(Madilyn, Direction.Down, 10, false, 1)
GROUND:MoveInDirection(Madilyn, Direction.DownLeft, 60, false, 1)
GROUND:CharTurnToCharAnimated(Madilyn,Kecleon, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(40)
GROUND:Unhide("Kecleon")
GROUND:MoveInDirection(Kecleon, Direction.Down, 10, false, 1)
GROUND:MoveInDirection(Kecleon, Direction.DownLeft, 30, false, 1)

GROUND:CharTurnToCharAnimated(Kecleon, Piks, 4)

rotationAlpha = true
rotationBeta = true
rotationPlayer = true

end)

coro3 = TASK:BranchCoroutine(function()

while not rotationPlayer do

GROUND:CharTurnToCharAnimated(player,Madilyn)
GAME:WaitFrames(10)

end

GROUND:CharTurnToChar(player, Kecleon)

end)

local coro4 = TASK:BranchCoroutine(function()

while not rotationBeta do

GROUND:CharTurnToCharAnimated(AdamMudkip,Madilyn)
GAME:WaitFrames(10)

end

GROUND:CharTurnToCharAnimated(AdamMudkip, Kecleon)

end)

local coro5 = TASK:BranchCoroutine(function() --This is stupid, don't do this.

GROUND:MoveInDirection(Piks, Direction.Down, 20, false, 1)

while not rotationAlpha do

GROUND:CharTurnToCharAnimated(Piks,Madilyn)
GAME:WaitFrames(10)

end

GROUND:CharTurnToCharAnimated(Piks, Kecleon)

end)


GAME:WaitFrames(80)
SOUND:PlayBGM("Wigglytuff's Guild Remix.ogg", true)
UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(204,121)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Oh, [pause=10]mister [color=#00FFFF]Kecleon[color]. [pause=0]Is there something you need from us?")

--GROUND:CharTurnToChar(Kecleon,AdamMudkip)
GROUND:CharSetEmote(Kecleon, "sweatdrop", 1)
SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GAME:WaitFrames(40)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(50,50)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("It's... [pause=20]a rather urgent request from me...")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("You see, [pause=10]one of my caravan Pokémon was being chased down by bandits on his way here.")
UI:WaitShowDialogue("According to [color=#00FFFF]Skiddo[color] himself, [pause=10]he's not very familiar with this region...")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I told him this job would be very dangerous, [pause=10]but he insisted on going...")
UI:WaitShowDialogue("Hence why I'm asking for your support to help me get him back here...")

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(Piks, "question", 1)
GAME:WaitFrames(40)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(12)
GROUND:CharTurnToCharAnimated(Madilyn,Piks)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(13)
GROUND:CharTurnToCharAnimated(player,Piks)

end)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Ehm, [pause=10]sorry for asking, [pause=10]but...")
UI:WaitShowDialogue("Why do you need us? [pause=0]We've encountered a lot of strong [color=#00FFFF]Kecleon[color] on our travels.")
UI:WaitShowDialogue("I'm just rather curious, [pause=10]since everyone we know seems to be scared of them.")

GAME:WaitFrames(10)
--GROUND:EntTurn(Kecleon, Direction.Down)
GROUND:CharSetEmote(Kecleon, "glowing", 0)
GROUND:CharTurnToChar(Kecleon,Piks)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(14)
GROUND:CharTurnToCharAnimated(Madilyn,Kecleon, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(9)
GROUND:CharTurnToCharAnimated(player,Kecleon, 4)

end)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(50,50)
UI:SetSpeakerEmotion("Happy")
UI:WaitShowDialogue("Oh ho ho, [pause=10][color=#54ebaf]Piks[color]! [pause=0]I wouldn't be here if I were like my 1,000 other cousins!")

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(player, "shock", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(player, false)
UI:SetSpeakerLoc(170,50)
UI:SetSpeakerEmotion("Surprised", true)
UI:WaitShowDialogue("(What in the world-!? [pause=0]What do you mean there's a thousand of you??)")

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(190,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Ooh... [pause=20]Fair enough...")
GROUND:CharSetEmote(Kecleon, "", 0)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(11)
GROUND:CharTurnToCharAnimated(Madilyn,Piks, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(10)
GROUND:CharTurnToCharAnimated(player,Piks, 4)

end)

UI:WaitShowDialogue("There is one small problem I should address to you first...")

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(Kecleon, "question", 1)
GAME:WaitFrames(40)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(13)
GROUND:CharTurnToCharAnimated(Madilyn,Kecleon, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(12)
GROUND:CharTurnToCharAnimated(player,Kecleon, 4)

end)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(50,50)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("And what would that be, [pause=10]exactly?")

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerEmotion("Worried", true)
UI:SetSpeakerLoc(204,121)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(11)
GROUND:CharTurnToCharAnimated(Madilyn,AdamMudkip, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(9)
GROUND:CharTurnToCharAnimated(player,AdamMudkip, 4)

end)

coro3 = TASK:BranchCoroutine(function()

GAME:WaitFrames(10)
GROUND:CharTurnToCharAnimated(Piks,AdamMudkip, 4)

end)

UI:WaitShowDialogue("A town near the mountains has gotten a nasty tornado and left it in shambles.")
UI:WaitShowDialogue("We're going over there to help rebuild it and make sure everything is ok.")

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(Kecleon, "shock", 1)
GROUND:CharSetEmote(player, "shock", 1)
GAME:WaitFrames(40)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(12)
GROUND:CharTurnToCharAnimated(Madilyn,Kecleon, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(9)
GROUND:CharTurnToCharAnimated(Piks,Kecleon, 4)

end)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(50,50)
UI:SetSpeakerEmotion("Surprised")
UI:WaitShowDialogue("A tornado?! [pause=0]That seems highly unlikely to happen here!")

GAME:WaitFrames(10)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(14)
GROUND:CharTurnToCharAnimated(Madilyn,AdamMudkip, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(9)
GROUND:CharTurnToCharAnimated(Piks,AdamMudkip, 4)

end)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(204,121)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Heavy storms happen from time to time, [pause=10]but I do agree with you, [color=#00FFFF]Kecleon[color]. [br]This region doesn't really get tornadoes as much as somewhere like [color=#FFC663]Baram Town[color].")

GROUND:CharSetEmote(Madilyn, "sweatdrop", 1)
SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GAME:WaitFrames(40)

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(9)
GROUND:CharTurnToCharAnimated(AdamMudkip,Madilyn, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(13)
GROUND:CharTurnToCharAnimated(player,Madilyn, 4)

end)

coro3 = TASK:BranchCoroutine(function()

GAME:WaitFrames(11)
GROUND:CharTurnToCharAnimated(Piks,Madilyn, 4)

end)

coro4 = TASK:BranchCoroutine(function()

GAME:WaitFrames(12)
GROUND:CharTurnToCharAnimated(Kecleon,Madilyn, 4)

end)

rotationAlpha = false
rotationBeta = false
rotationCharlie = false
rotationPlayer = false

UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")
UI:ResetSpeakerLoc()
UI:WaitShowDialogue("And that just leaves me and ".. CH('PLAYER'):GetDisplayName() .." to help out...")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("*Sigh* [pause=20]Fine... [pause=20]I'll take [color=#00FFFF]Kecleon[color] and the greenhorn to wherever.")

GAME:WaitFrames(10)
GROUND:EntTurn(Madilyn, Direction.UpRight)

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Come on, [pause=10][color=#00FFFF]Kecleon[color]. [pause=0]I need to buy stuff from your store before we leave.")

coro1 = TASK:BranchCoroutine(function()

while not rotationPlayer do

GROUND:CharTurnToCharAnimated(player,Madilyn)
GAME:WaitFrames(10)

end

end)

coro2 = TASK:BranchCoroutine(function()

while not rotationBeta do

GROUND:CharTurnToCharAnimated(AdamMudkip,Madilyn)
GAME:WaitFrames(10)

end

end)

coro3 = TASK:BranchCoroutine(function() --This is stupid, don't do this.

while not rotationAlpha do

GROUND:CharTurnToCharAnimated(Piks,Madilyn)
GAME:WaitFrames(10)

end

end)

coro4 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(Kecleon, Direction.DownRight, 15, false, 1)

while not rotationCharlie do

GROUND:CharTurnToCharAnimated(Kecleon,Madilyn)
GAME:WaitFrames(10)

end

end)

coro5 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(Madilyn, Direction.UpRight, 60, false, 1)
GROUND:MoveInDirection(Madilyn, Direction.Up, 10, false, 1)
GROUND:Hide("Madilyn")

rotationAlpha = true
rotationBeta = true
rotationCharlie = true
rotationPlayer = true

end)

GAME:WaitFrames(80)

coro1 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(player,Kecleon, 4) end)
coro2 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(Piks,Kecleon, 4) end)
coro3 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(AdamMudkip,Kecleon, 4) end)

GAME:WaitFrames(15)
rotationAlpha = false
rotationBeta = false
rotationCharlie = false
rotationPlayer = false

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(65,65)
UI:SetSpeakerEmotion("Normal")
GROUND:EntTurn(Kecleon,Direction.UpRight)
UI:WaitShowDialogue("I'll let you get prepared, [pause=10]then. [pause=0]I'll be near my shop when you're ready, [pause=10]".. CH('PLAYER'):GetDisplayName().. ".")

coro1 = TASK:BranchCoroutine(function()

GROUND:MoveToPosition(Kecleon, 221, 146, false, 1)
GROUND:MoveInDirection(Kecleon, Direction.Up, 20, false, 1)
GROUND:Hide("Kecleon")

rotationAlpha = true
rotationBeta = true
rotationCharlie = true
rotationPlayer = true

end)

coro2 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(player, Direction.Right, 10, false, 1)

while not rotationPlayer do

GROUND:CharTurnToCharAnimated(player,Kecleon)
GAME:WaitFrames(10)

end

end)

coro3 = TASK:BranchCoroutine(function()

while not rotationBeta do

GROUND:CharTurnToCharAnimated(AdamMudkip,Kecleon)
GAME:WaitFrames(10)

end

end)

coro4 = TASK:BranchCoroutine(function() --This is stupid, don't do this.

while not rotationAlpha do

GROUND:CharTurnToCharAnimated(Piks,Kecleon)
GAME:WaitFrames(10)

end

end)
GAME:WaitFrames(10)
UI:ResetSpeakerLoc()
UI:SetSpeaker(Piks)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("See you later, [pause=10]mister [color=#00FFFF]Kecleon[color].[pause=60]")

coro1 = TASK:BranchCoroutine(function()

GAME:WaitFrames(11)
GROUND:CharTurnToCharAnimated(player,AdamMudkip, 4)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(10)
GROUND:CharTurnToCharAnimated(AdamMudkip,player, 4)

end)

coro3 = TASK:BranchCoroutine(function()

GAME:WaitFrames(10)
GROUND:CharTurnToCharAnimated(Piks,player, 4)

end)

GAME:WaitFrames(10)
GROUND:EntTurn(AdamMudkip, Direction.Up)
UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("I would recommend you prepare accordingly, [pause=10]".. CH('PLAYER'):GetDisplayName() ..". [pause=0]You're escorting [color=#00FFFF]Kecleon[color] to his destination.")
UI:WaitShowDialogue("Don't sweat too hard about it, [pause=10][color=#54ebaf]Madilyn[color] will be with you in the dungeon to help out.")
UI:WaitShowDialogue("I should remind you that this is a special job, [pause=10]meaning you're not allowed to recruit for the time being.")
UI:WaitShowDialogue("This also means you can't bring anyone with you. [br]Besides a law or two, [pause=10][color=#54ebaf]Madilyn[color] wouldn't enjoy the extra company you're bringing.")
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("And don't pout, [pause=10]escorting someone is not that hard if you play your cards right.")
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("For now, [pause=10]we have to get going. [pause=0]I'm trusting you to do your best for this mission.")
UI:WaitShowDialogue("When we come back, [pause=10]we'll talk about extra credit.")
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Well, [pause=10]uh, [pause=10]it's more like paid overtime...")
UI:SetSpeaker(AdamMudkip, false)
UI:SetSpeakerEmotion("Pain", true)
UI:WaitShowDialogue("(God, [pause=10]I hope they understand what those concepts are, [pause=10]because I don't remember what they mean.)")

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Happy")
UI:WaitShowDialogue("See you later, [pause=10]".. CH('PLAYER'):GetDisplayName() ..". [pause=0]You got this whole thing under control!")

coro1 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(player, Direction.Right, 15, false, 1)
GROUND:CharAnimateTurn(player, Direction.UpLeft, 4, true)

end)

coro2 = TASK:BranchCoroutine(function()

GROUND:MoveToPosition(AdamMudkip, 221, 146, false, 1)
GROUND:MoveInDirection(AdamMudkip, Direction.Up, 20, false, 1)
GROUND:Hide("AdamMudkip")

end)

coro3 = TASK:BranchCoroutine(function()

GROUND:EntTurn(Piks, Direction.UpRight)
GAME:WaitFrames(10)
GROUND:MoveToPosition(Piks, 221, 146, false, 1)
GROUND:MoveInDirection(Piks, Direction.Up, 20, false, 1)
GROUND:Hide("Piks")

end)

SOUND:PlayBGM("", true) --But only *if* these are here. Might change later.
--221 146
GAME:WaitFrames(120)

SOUND:FadeInSE("Beach_Noise")

GROUND:CharSetAnim(player, "Idle", false) --Because, for whatever reason, they do not revert back to the Idle Animation. Not sure why.
GAME:CutsceneMode(false)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(Guess I'm on my own for the time being.)")

GAME:MoveCamera(0, 0, 20, true)

SV.chapter1.meeting_partB = true
end

function electraterhome.Book_Action(obj, activator)

UI:ResetSpeaker()
UI:WaitShowDialogue("Sorry, you cannot open this yet. You should check in on a later update.")

end

function electraterhome.HideChara()

GROUND:Hide("Madilyn")
GROUND:Hide("Kecleon")

if SV.chapter.number == 1 and not SV.chapter1.meeting_partA then

GROUND:Hide("Book")

elseif SV.chapter.number == 1 and SV.chapter1.meeting_partB then

GROUND:Hide("Piks")
GROUND:Hide("AdamMudkip")
--GROUND:Unhide("Book")

end

end

return electraterhome

