--[[
    init.lua
    Created: 05/10/2024 23:14:46
    Description: Autogenerated script file for the map beginners_footpath.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local beginners_footpath = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---beginners_footpath.Init(zone)
--Engine callback function
function beginners_footpath.Init(zone)


end

---beginners_footpath.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function beginners_footpath.EnterSegment(zone, rescuing, segmentID, mapID)


end

---beginners_footpath.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function beginners_footpath.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---beginners_footpath.Rescued(zone, name, mail)
--Engine callback function
function beginners_footpath.Rescued(zone, name, mail)


end

return beginners_footpath

