--[[
    init.lua
    Created: 06/15/2023 00:13:40
    Description: Autogenerated script file for the map wigglyguildbedup.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildbedup = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildbedup.Init(map)
--Engine callback function
function wigglyguildbedup.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildbedup.Enter(map)
--Engine callback function
function wigglyguildbedup.Enter(map)

  GAME:FadeIn(20)

end

---wigglyguildbedup.Exit(map)
--Engine callback function
function wigglyguildbedup.Exit(map)


end

---wigglyguildbedup.Update(map)
--Engine callback function
function wigglyguildbedup.Update(map)


end

---wigglyguildbedup.GameSave(map)
--Engine callback function
function wigglyguildbedup.GameSave(map)


end

---wigglyguildbedup.GameLoad(map)
--Engine callback function
function wigglyguildbedup.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


function wigglyguildbedup.InteractiveNearby_Touch(obj, activator)

SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(activator, "question", 1)

end

function wigglyguildbedup.Diary_Action(obj, activator)
local player =CH('PLAYER')

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(It's all pretty dusty aside from the weirdly square shape on the top of it. [pause=0]I wonder what's been on it?)")

end

function wigglyguildbedup.LeaveRoom_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbedhalls", "EntranceUp")

end

return wigglyguildbedup

