--[[
    init.lua
    Created: 12/21/2022 00:30:07
    Description: Autogenerated script file for the map cutscenepath.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutscenepath = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutscenepath.Init
--Engine callback function
function cutscenepath.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutscenepath.Enter
--Engine callback function
function cutscenepath.Enter(map) --Should be NO cases where a player is able to walk on this Groundmap, therefore, no FadeIn should happen unless otherwise.

    GROUND:AddMapStatus("dark")

	if not SV.cutscenepath.DreamDone then
cutscenepath.EnterScene(danganronpa)
	else
cutscenepath.ExitScene(objection)
	end
	
end

---cutscenepath.Exit
--Engine callback function
function cutscenepath.Exit(map)


end

---cutscenepath.Update
--Engine callback function
function cutscenepath.Update(map)


end

---cutscenepath.GameSave
--Engine callback function
function cutscenepath.GameSave(map)


end

---cutscenepath.GameLoad
--Engine callback function
function cutscenepath.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function cutscenepath.EnterScene(danganronpa) --There's always a time and place for something funny. / But probably not now since apparently parameters are weird.

  GAME:CutsceneMode(true)
  GAME:MoveCamera(180, 225, 1, false)

GAME:FadeOut(false, 1)

  SOUND:PlayBGM("At The End Of The Road.ogg", true)
    UI:WaitShowBG("Night", 1, 40);
	GAME:WaitFrames(120)
	UI:WaitHideBG(40)

  GAME:FadeIn(20)
  
  local player = CH('PLAYER')
  
  GROUND:MoveInDirection(player, Direction.Right, 150, false, 1)
  
  GAME:WaitFrames(60)
  
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")
  UI:WaitShowDialogue("(I've been running for what feels like the whole night...)")
  UI:WaitShowDialogue("(I'm not sure how long they'll take to try and get on my trail.)")
  UI:WaitShowDialogue("(Hopefully long enough where they won't ever consider trying to chase me.)")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(I can hope that, [pause=10]but only one question remains now.)")
  UI:WaitShowDialogue("(What exactly does this medallion even do? [pause=0]Because I can't figure it out, [pause=10]or their obsession with it.)")
  UI:WaitShowDialogue("(Maybe I should take this to an explorer, [pause=10]or something...)")
  
    GROUND:MoveInDirection(player, Direction.Right, 20, false, 1)
		GAME:WaitFrames(40)
	GROUND:MoveInDirection(player, Direction.Right, 20, false, 1)
		GAME:WaitFrames(25)
	
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("(Ow ow ow... [pause=20]My legs are very sore...)")
	
	GROUND:CharAnimateTurn(player, Direction.Left, 4, true)
	GAME:WaitFrames(15)
	
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("(I should be far enough away from those two weirdoes.)")
	UI:WaitShowDialogue("(Let's hope they don't plan to waste their energy chasing me down at this time of day...)")
	UI:WaitShowDialogue("(I'll need to take a quick power-nap here on the road to have enough energy to get anywhere.)")
	
	GAME:FadeOut(false, 20)
	GAME:WaitFrames(20)
	SOUND:PlayBattleSE("EVT_CH03_Boss_Collapse") --Good enough.
	
	GAME:WaitFrames(35)
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue("(At least my [color=#32a852]Treasure Bag[color] makes for a good bed...)")
	UI:WaitShowDialogue("(Kind of. [pause=0]It's full of old papers and other stuff. [pause=0]I should be careful not to ruin any of it.)")
	
	  GAME:WaitFrames(60)
	
	GAME:EnterGroundMap("cutscenebluff", "Entrance")

end

function cutscenepath.ExitScene(objection) --no, that's wrong.

  local player = CH('PLAYER')
  GAME:CutsceneMode(true)

	GAME:MoveCamera(0, 0, 1, true)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(...nnf...)")

GAME:FadeIn(20)
GAME:WaitFrames(20)

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharAnimateTurn(player, Direction.Left, 4, true)
GAME:WaitFrames(20)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharAnimateTurn(player, Direction.Right, 4, true)
GAME:WaitFrames(30)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharAnimateTurn(player, Direction.Left, 4, false)
GAME:WaitFrames(15)
		
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Thankfully, [pause=10]nothing bad seemed to have happen while I was napping...)")
UI:WaitShowDialogue("(I guess it helped, [pause=10]but next time, [pause=10]I'm not gonna sleep in the middle of nowhere.)")
UI:WaitShowDialogue("...")
UI:WaitShowDialogue("(Uh... [pause=20]Maybe I should look for a town, [pause=10]or a sign.)")
UI:WaitShowDialogue("(I haven't the slightest clue where I'm going.)")

GROUND:CharAnimateTurn(player, Direction.Right, 4, true)
GAME:WaitFrames(20)

UI:WaitShowDialogue("(I guess I'll just keep following the road. [pause=0]It's here for a reason.)")

GROUND:MoveInDirection(player, Direction.Right, 90, true, 2)
GAME:WaitFrames(15)
GROUND:EntTurn(player, Direction.UpRight)

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Well, [pause=10]talk about convenience. [pause=0]There's a signpost here.) [br](That's odd, [pause=10]I don't remember seeing it here before.)") --Made to fit into one text box.

GROUND:MoveInDirection(player, Direction.Right, 13, true, 2)
GAME:WaitFrames(20)
GROUND:CharAnimateTurn(player, Direction.Up, 4, true)

GAME:WaitFrames(40)

UI:WaitShowDialogue("(Hm... [pause=20]I still have a way to go, [pause=10]but I should be able to reach [color=#FFC663]Treasure Town[color] before the sun rises...)")
GAME:WaitFrames(25)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(I kinda wish it wasn't so far... [pause=20]But it's better than nothing.)")

	GROUND:CharAnimateTurn(player, Direction.Right, 4, false)

GROUND:MoveInDirection(player, Direction.Right, 120, false, 1)
GAME:FadeOut(false, 40)
GAME:WaitFrames(60)

SV.prologue.dont_cutscene = true
SV.prologue.cant_do_that_yet = true
GAME:CutsceneMode(false)

GAME:EnterZone('treasuretownzone', -1, 0, 0)


end

return cutscenepath

