--[[
    init.lua
    Created: 04/15/2024 23:40:55
    Description: Autogenerated script file for the map cutsceneintromountain2.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutsceneintromountain2 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneintromountain2.Init(map)
--Engine callback function
function cutsceneintromountain2.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutsceneintromountain2.Enter(map)
--Engine callback function
function cutsceneintromountain2.Enter(map)

  StoryTime()

end

---cutsceneintromountain2.Exit(map)
--Engine callback function
function cutsceneintromountain2.Exit(map)


end

---cutsceneintromountain2.Update(map)
--Engine callback function
function cutsceneintromountain2.Update(map)


end

---cutsceneintromountain2.GameSave(map)
--Engine callback function
function cutsceneintromountain2.GameSave(map)


end

---cutsceneintromountain2.GameLoad(map)
--Engine callback function
function cutsceneintromountain2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function StoryTime()
local player = CH('PLAYER')
local BlueRat = CH('background_NPC1') --not in the mood, also I made a horrible mistake calling the NPCs these.
local Palpitoad = CH('background_NPC1_1')
local Pidgeot = CH('background_NPC1_2')
local Psyduck = CH('Psyduck')
local Poliwag = CH('background_NPC1_4')
local Weedle = CH('background_NPC1_5')

local PsyduckLoop = false
local FriendsALoop = false
local FriendsBLoop = false
local BlueRatLoop = false

GROUND:CharSetAnim(BlueRat, "Idle", true)
GROUND:CharSetAnim(Weedle, "Idle", true)
GROUND:CharSetAnim(Poliwag, "Idle", true)

GROUND:CharSetEmote(Weedle, "glowing", 0)
GROUND:CharSetEmote(Poliwag, "glowing", 0)

GAME:CutsceneMode(true)
GAME:MoveCamera(245, 193, 1, false)
GAME:WaitFrames(30)

local coro1 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(player, Direction.Up, 40, false, 1)
GROUND:MoveInDirection(player, Direction.UpRight, 8, false, 1)
GROUND:MoveInDirection(player, Direction.Up, 70, false, 1)

GAME:WaitFrames(10)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(60)

GROUND:CharSetEmote(player, "happy", 0)

end)

local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(30) end)

local coro3 = TASK:BranchCoroutine(function()

while not PsyduckLoop do

GAME:WaitFrames(20)
GROUND:MoveInDirection(Psyduck, Direction.Left, 30, false, 1)
GAME:WaitFrames(20)
GROUND:MoveInDirection(Psyduck, Direction.Right, 30, false, 1)

end

end)

local coro4 = TASK:BranchCoroutine(function() GAME:MoveCamera(245, 130, 60, false) end)

local coro5 = TASK:BranchCoroutine(function()

while not FriendsALoop do

GROUND:CharSetAnim(Palpitoad, "Walk", false)
GAME:WaitFrames(20)
GROUND:CharSetAnim(Pidgeot, "Walk", false)
GAME:WaitFrames(25)
GROUND:CharSetEmote(Palpitoad, "notice", 1)
GAME:WaitFrames(20)
GROUND:CharSetAnim(Palpitoad, "Walk", false)
GAME:WaitFrames(25)
GROUND:CharSetEmote(Pidgeot, "notice", 1)
GAME:WaitFrames(20)
GROUND:CharSetAnim(Pidgeot, "Walk", false)
GAME:WaitFrames(25)

end

end)

GAME:WaitFrames(20)

UI:WaitShowDialogue("Ever since ".. COMMON.GenderCheck(player, "their", false) .." journey started, [pause=10]".. COMMON.GenderCheck(player, "they have", false) .." seen incredible sights, [pause=10]and met interesting Pokémon.")
UI:WaitShowDialogue("Vast mountains, [pause=10]deep oceans... [pause=20]dense jungles, [pause=10]and desolate deserts... [pause=20]".. COMMON.GenderCheck(player, "they've", false) .." been to a lot of places.")
UI:WaitShowDialogue("Though, [pause=10]deep down in ".. COMMON.GenderCheck(player, "their", false) .." soul, [pause=10]the real reason for this journey was something more profound...")
GROUND:CharSetEmote(player, "", 0)

GAME:WaitFrames(15)
GROUND:CharSetEmote(player, "notice", 1)
GAME:WaitFrames(10)

GROUND:CharAnimateTurn(player, Direction.UpRight, 4, false)
GAME:WaitFrames(50)
GROUND:EntTurn(player, Direction.Right)
GAME:WaitFrames(20)

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Sad")
UI:WaitShowDialogue("Sigh... [pause=20]I miss having a partner...")
--UI:WaitShowDialogue("It always felt like we were meant to pair up...")

GROUND:CharAnimateTurn(player, Direction.UpLeft, 4, true)
GAME:WaitFrames(20)

UI:WaitShowDialogue("But how can I possibly trust someone like that again...?")
UI:WaitShowDialogue("...A friend turned criminal...")

local coro6 = TASK:BranchCoroutine(function()
SOUND:FadeOutBGM(90)
GAME:FadeOut(false, 90)
end)

GAME:WaitFrames(20)

UI:ResetSpeaker()
UI:SetCenter(true)
UI:WaitShowDialogue("Trust... [pause=20]The underlying basis for us in the Pokémon world. [pause=0]This is what ".. CH('PLAYER'):GetDisplayName() .." is looking for.")
UI:SetCenter(false)

PsyduckLoop = true
FriendsALoop = true
FriendsBLoop = true
BlueRatLoop = true

UI:WaitShowDialogue(COMMON.GenderCheck(player, "they", true) .." searched high and low trying to find what 'trust' truly was...")
UI:WaitShowDialogue("But no matter where ".. COMMON.GenderCheck(player, "they", false) .." looked, [pause=10]the truth always seemed so far away...")
GAME:WaitFrames(40)

GAME:EnterGroundMap("cutsceneintrosnowplace3", "Entrance")

GAME:CutsceneMode(false)

end

return cutsceneintromountain2

