--[[
    init.lua
    Created: 10/03/2023 21:00:14
    Description: Autogenerated script file for the map seasideseranadefinal.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local seasideseranadefinal = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---seasideseranadefinal.Init(map)
--Engine callback function
function seasideseranadefinal.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---seasideseranadefinal.Enter(map)
--Engine callback function
function seasideseranadefinal.Enter(map)

COMMON.RespawnAllies()

seasideseranadefinal.cutscene()

end

---seasideseranadefinal.Exit(map)
--Engine callback function
function seasideseranadefinal.Exit(map)


end

---seasideseranadefinal.Update(map)
--Engine callback function
function seasideseranadefinal.Update(map)


end

---seasideseranadefinal.GameSave(map)
--Engine callback function
function seasideseranadefinal.GameSave(map)


end

---seasideseranadefinal.GameLoad(map)
--Engine callback function
function seasideseranadefinal.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function seasideseranadefinal.cutscene()
local player = CH('PLAYER')
local Teammate_1 = CH('Teammate_1')
local Teammate_2 = CH('Teammate_2')
local Teammate_3 = CH('Teammate_3')
local Dragonair = CH('Dragonair')
local Masquerain = CH('Masquerain')
local Floette = CH('Floette')

GAME:CutsceneMode(true)
GAME:MoveCamera(282, 133, 1, false)

UI:WaitShowTitle("At the end of\nSeaside Seranade", 20)
GAME:WaitFrames(60)
UI:WaitHideTitle(20)
GAME:WaitFrames(30)

GROUND:CharSetEmote(Dragonair, "happy", 0)
GROUND:CharSetEmote(Masquerain, "glowing", 0)
GROUND:CharSetEmote(Floette, "happy", 0)

local coro1 = TASK:BranchCoroutine(function() 
SOUND:PlayBGM("Heartwarming.ogg", true)
GAME:FadeIn(20)
end)

local coro2 = TASK:BranchCoroutine(function() 
GROUND:MoveInDirection(player, Direction.Left, 100, false, 1)
end)

local coro3 = TASK:BranchCoroutine(function() seasideseranadefinal.teammateswalkforward_Sequence(Teammate_1) end)
local coro4 = TASK:BranchCoroutine(function() seasideseranadefinal.teammateswalkforward_Sequence(Teammate_2) end) --Function Names need to be shorter.
local coro5 = TASK:BranchCoroutine(function() seasideseranadefinal.teammateswalkforward_Sequence(Teammate_3) end)

TASK:BranchCoroutine({coro1,coro2,coro3.coro4,coro5})

GAME:WaitFrames(110)
GROUND:EntTurn(player, Direction.UpLeft)
GAME:WaitFrames(30)
GROUND:CharSetEmote(Masquerain, "notice", 1)
GAME:WaitFrames(30)
GROUND:CharSetEmote(Dragonair, "", 0)
GROUND:CharSetEmote(Floette, "", 0)
GROUND:EntTurn(Masquerain, Direction.Right)
GAME:WaitFrames(10)
GROUND:EntTurn(Masquerain, Direction.DownRight)
GROUND:EntTurn(Dragonair, Direction.Left)
GAME:WaitFrames(10)
GROUND:EntTurn(Masquerain, Direction.Down)
GROUND:EntTurn(Teammate_1, Direction.UpLeft)
GAME:WaitFrames(10)
GROUND:EntTurn(Masquerain, Direction.DownRight)
GROUND:EntTurn(Floette, Direction.UpLeft)
GAME:WaitFrames(10)
GROUND:EntTurn(Masquerain, Direction.Right)
GAME:WaitFrames(10)
GROUND:EntTurn(Masquerain, Direction.DownRight)
GAME:WaitFrames(20)

GROUND:CharSetEmote(Dragonair, "question", 1)
GROUND:CharSetEmote(Floette, "question", 1)
GAME:WaitFrames(40)

coro1 = TASK:BranchCoroutine(function()
GROUND:CharAnimateTurn(Dragonair, Direction.DownRight, 4, true)
end)
coro2 = TASK:BranchCoroutine(function()
GROUND:CharAnimateTurn(Floette, Direction.Right, 4, false)
end)

GAME:WaitFrames(30)
GROUND:CharSetEmote(Dragonair, "notice", 1)
GROUND:CharSetEmote(Floette, "notice", 1)
GAME:WaitFrames(30)

GROUND:CharSetEmote(Dragonair, "happy", 0)
GROUND:CharSetEmote(Floette, "happy", 0)
GROUND:CharSetEmote(Masquerain, "happy", 0)

GAME:WaitFrames(40)

GROUND:CharSetEmote(player, "sweatdrop", 1)

UI:ResetSpeaker(false)
UI:SetCenter(true)

UI:WaitShowDialogue("You've made it through [color=#FFC663]Seaside Seranade[color]...")
UI:WaitShowDialogue("But the only thing at the end was an obscure village.")
UI:WaitShowDialogue("Other than that, [pause=10]there's nothing else to report. [pause=0]\nTime to head back.")
UI:SetCenter(false)

GAME:FadeOut(false, 20)
GAME:CutsceneMode(false)
GAME:EnterZone('treasuretownzone', -1, 17, 0)

GAME:CutsceneMode(false)
end

function seasideseranadefinal.teammateswalkforward_Sequence(character)
GROUND:MoveInDirection(character, Direction.Left, 100, false, 1)
end

return seasideseranadefinal

