--[[
    init.lua
    Created: 06/14/2023 22:14:51
    Description: Autogenerated script file for the map wigglyguildbedhalls.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildbedhalls = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildbedhalls.Init(map)
--Engine callback function
function wigglyguildbedhalls.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildbedhalls.Enter(map)
--Engine callback function
function wigglyguildbedhalls.Enter(map)

  GAME:FadeIn(20)

end

---wigglyguildbedhalls.Exit(map)
--Engine callback function
function wigglyguildbedhalls.Exit(map)


end

---wigglyguildbedhalls.Update(map)
--Engine callback function
function wigglyguildbedhalls.Update(map)


end

---wigglyguildbedhalls.GameSave(map)
--Engine callback function
function wigglyguildbedhalls.GameSave(map)


end

---wigglyguildbedhalls.GameLoad(map)
--Engine callback function
function wigglyguildbedhalls.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function wigglyguildbedhalls.LeaveHall_Touch(obj, activator)
GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbottom", "EntranceRight")
end

function wigglyguildbedhalls.EnterBedroomUp_Touch(obj, activator)
GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbedup", "Entrance")
end

function wigglyguildbedhalls.EnterBedroomDown_Touch(obj, activator)
GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbeddown", "Entrance")
end

function wigglyguildbedhalls.EnterRoom_Touch(obj, activator)
GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbedsun", "EntranceLeft")
end

return wigglyguildbedhalls

