--[[
    init.lua
    Created: 12/30/2022 10:16:24
    Description: Autogenerated script file for the map treasuretown2.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local treasuretown2 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---treasuretown2.Init
--Engine callback function
function treasuretown2.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---treasuretown2.Enter
--Engine callback function
function treasuretown2.Enter(map)

  treasuretown2.chapterhidescript()

  GAME:FadeIn(20)
  SV.repeatable.pots = false
  
  treasuretown2.default_initialize(wanderzoneloc, wanderzonesize, wanderspeed, wanderstepmin, wanderstepmax, idledelaymin, idledelaymax) --don't ask, idfk

end

---treasuretown2.Exit
--Engine callback function
function treasuretown2.Exit(map)


end

---treasuretown2.Update
--Engine callback function
function treasuretown2.Update(map)


end

---treasuretown2.GameSave
--Engine callback function
function treasuretown2.GameSave(map)


end

---treasuretown2.GameLoad
--Engine callback function
function treasuretown2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function treasuretown2.BankActivate_Action(obj, activator)
--how the heck am I gonna make this dude work lmao, do I just take a Deposit Box Function, and modify it to the situation? / You just solved the problem yourself, get rid of this line.

local duskull = CH('Duskull')
local player = CH('PLAYER')
GROUND:CharTurnToChar(duskull, player)
GROUND:CharTurnToChar(player, duskull)

		UI:SetSpeaker(duskull)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue("Welcome to the [color=#FFC663]Duskull Bank[color]. [pause=0]How may I assist your finances for the day...?")
		
		UI:BankMenu()
		UI:WaitForChoice()
		
		UI:WaitShowDialogue("Good doing business with you... [pause=20]keheheh...")
		
GROUND:EntTurn(duskull, Direction.Down)
end

function treasuretown2.marowak_Action(chara, activator)


--side note, what do I even do with the Dojo? I could copy the Training dungeon from Base Camp, but that seems lazy.
GROUND:CharTurnToChar(chara,CH('PLAYER'))

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I'm sorry, [pause=10]but this place is under renovation. [pause=0]I do not want trainees to get hurt from this old place.")

end

function treasuretown2.SignRight_Action(obj, activator)

  UI:ResetSpeaker()
  UI:SetCenter(true)
  UI:SetAutoFinish(true)
  
  UI:WaitShowDialogue("Crossroads, [color=#FFC663]Wigglytuff's Guild[color] -->")
  
  UI:SetCenter(false)
  UI:SetAutoFinish(false)

end

function treasuretown2.caretaker_Action(chara, activator) --The most complicated character I had to script for. / Probably because making Logic Gates in script is harder than placing them down in LittleBigPlanet.
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara,player)
GROUND:CharTurnToChar(player,chara)

if SV.prologue.cant_do_that_yet then

	if not SV.prologue_alts.blissy_declined then
		if not SV.prologue.has_spindas_shaker then

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Happy")

UI:WaitShowDialogue("Oh! [pause=0]Good morning, [pause=10]you must be a new visitor! [pause=0]Welcome to [color=#FFC663]Treasure Town[color]! ♪")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Why, [pause=10]what appears to be the matter? [pause=0]Is something bothering you?")
UI:WaitShowDialogue("...")
UI:WaitShowDialogue("You're not much of a talker, [pause=10]huh?")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Oh! [pause=0]But you do have a [color=#32a852]Treasure Bag[color] on you, [pause=10]so maybe you're one of those explorer types! ♪")
UI:WaitShowDialogue("I can only guess so much from your silence alone, [pause=10]but you probably want something to eat.")

UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['ContinueStory1']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
				if ch then

	UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Why thank you very much! ♪")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("You see, [pause=10]his supplies were accidentally given to me, [pause=10]so I want you to give them back to him.")
	UI:WaitShowDialogue("Oh! [pause=0]And can you say hello to him for me?")
	UI:WaitShowDialogue("Really-really sorry for having to make you do something, [pause=10]but I have to watch over the little ones.")
	
	SOUND:PlayBattleSE("EVT_CH02_Item_Place")
	
	GAME:WaitFrames(20)
	
	UI:ResetSpeaker()
	UI:SetCenter(true)
	UI:WaitShowDialogue(CH('caretaker'):GetDisplayName() .." gave you a small box. \nIt was small enough to fit in your [color=#32a852]Treasure Bag[color].")
		UI:SetCenter(false)
	
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("(I might as well do it for her. [pause=0]I got a fair bit of time to spend.)")
	
	SV.prologue.has_spindas_shaker = true
	
				else

	UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("*sigh* [pause=15]Really-really? [pause=0]He's not that far from here...")
	UI:WaitShowDialogue("If you do want to help, [pause=10]I'll wait here patiently.")
	
	SV.prologue_alts.blissy_declined = true
	
				end

		elseif SV.prologue.has_spindas_shaker == true then --This and the call above it SHOULD NEVER CONFLICT! Only this one or the other! / 4start

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("[color=#FFC663]Spinda's Café[color] should be near the crossroads. [pause=0]It has a sign, [pause=10]so you can't miss it! ♪")

			end
		elseif SV.prologue_alts.blissy_declined == true then --This and the call below it SHOULD NEVER CONFLICT! Only one or the other!

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['ContinueStory2']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then

	UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Why, [pause=10]thank you very much!")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("You see, [pause=10]his supplies were accidentally given to me, [pause=10]so I want you to give them back to him.")
	UI:WaitShowDialogue("Oh! [pause=0]And can you say hello to him for me?")
	UI:WaitShowDialogue("Really-really sorry for having to make you do something, [pause=10]but I have to watch over the little ones.")
	
	SOUND:PlayBattleSE("EVT_CH02_Item_Place")
	
	GAME:WaitFrames(20)
	
	UI:ResetSpeaker(false)
	UI:SetCenter(true)
	UI:WaitShowDialogue(CH('caretaker'):GetDisplayName() .." gave you a small box. \nIt was small enough to fit in your [color=#32a852]Treasure Bag[color].")
		UI:SetCenter(false)
	
	GAME:WaitFrames(20)
	
	GROUND:CharSetEmote(player, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	
	GAME:WaitFrames(40)
	
	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("(I might as well do it for her. [pause=0]I don't really have anything else to do.)")
	
	SV.prologue.has_spindas_shaker = true
	SV.prologue_alts.blissy_declined = false --Used to make complete sure you have the box, and prioritize messages.

else
	
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("Seriously? [pause=0]I dunno what game you're playing, [pause=10]but it's not funny.") --Honestly, I don't even know what she'd say if she'd been declined a 2nd time, consider this a rough draft.
	
end
		end
	
	elseif not SV.prologue.cant_do_that_yet then

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Another nice day, [pause=10]isn't it? ♪")
		end
	end 
	
function treasuretown2.SignLeft_Action(obj, activator)

  UI:ResetSpeaker()
  UI:SetCenter(true)
  UI:SetAutoFinish(true)
  
  UI:WaitShowDialogue("<-- [color=#FFC663]Sharpedo Bluff[color] \nKecleon Brothers, Item Storage, Xatu's Box Appraisal")
  
  UI:SetCenter(false)
  UI:SetAutoFinish(false)

end

function treasuretown2.LinkShop_Action(obj, activator)
local electivire = CH('Electivire')
local player = CH('PLAYER')

GROUND:CharTurnToChar(electivire, player)
GROUND:CharTurnToChar(player, electivire)

	if SV.prologue.cant_do_that_yet then
	
		UI:SetSpeaker(electivire)
		UI:SetSpeakerEmotion("Worried")
		
		UI:WaitShowDialogue("Woah bud, [pause=10]I think you should eat something before you pass out from learning new moves.")
		UI:WaitShowDialogue("The last thing you wanna do is waste a good day by sleeping in with sore muscles.")
		
	else
	
		UI:SetSpeaker(electivire)
   --Enable debugging this coroutine
  
  local price = 150
  local state = 0
  local repeated = false
  local member = nil
  local move = ""
  
	while state > -1 do
		if state == 0 then
			local msg = STRINGS:Format(STRINGS.MapStrings['Tutor_Intro'], STRINGS:FormatKey("MONEY_AMOUNT", price))
			if repeated == true then
				msg = STRINGS:Format(STRINGS.MapStrings['Tutor_Intro_Return'])
			end
			
			local tutor_choices = {RogueEssence.StringKey("MENU_RECALL_SKILL"):ToLocal(),
			RogueEssence.StringKey("MENU_FORGET_SKILL"):ToLocal(),
			STRINGS:FormatKey("MENU_INFO"),
			STRINGS:FormatKey("MENU_EXIT")}
			UI:BeginChoiceMenu(msg, tutor_choices, 1, 4)
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			repeated = true
			if result == 1 then
				if price > GAME:GetPlayerMoney() then
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_No_Money']))
				else
					state = 1
				end
			elseif result == 2 then
				state = 4
			elseif result == 3 then
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Info_001']))
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Info_002']))
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Info_003']))
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Info_004']))
			else
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Goodbye']))
				state = -1
			end
		elseif state == 1 then
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Who']))
			UI:TutorTeamMenu()
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			if result > -1 then
				state = 2
				member = GAME:GetPlayerPartyMember(result)
			else
				state = 0
			end
		elseif state == 2 then
			if not GAME:CanRelearn(member) then
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Cant_Remember']))
				state = 1
			else
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_What'], member:GetDisplayName(true)))
				UI:RelearnMenu(member)
				UI:WaitForChoice()
				local result = UI:ChoiceResult()
				if result ~= "" then
					move = result
					state = 3
				else
					state = 1
				end
			end
		elseif state == 3 then
			local moveEntry = _DATA:GetSkill(move)
			if GAME:CanLearn(member) then
				SOUND:PlayBattleSE("DUN_Money")
				GAME:RemoveFromPlayerMoney(price)
				GAME:LearnSkill(member, move)
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Begin']))
				treasuretown2.Tutor_Sequence(member, moveEntry)
				SOUND:PlayFanfare("Fanfare/LearnSkill")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Success'], member:GetDisplayName(true), moveEntry:GetIconName()))
				state = 0
			else
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Replace']))
				local result = UI:LearnMenu(member, move)
				UI:WaitForChoice()
				local result = UI:ChoiceResult()
				if result > -1 and result < 4 then
					SOUND:PlayBattleSE("DUN_Money")
					GAME:RemoveFromPlayerMoney(price)
					GAME:SetCharacterSkill(member, move, result)
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Begin']))
					treasuretown2.Tutor_Sequence(member, moveEntry)	
				    SOUND:PlayFanfare("Fanfare/LearnSkill")
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Remember_Success'], member:GetDisplayName(true), moveEntry:GetIconName()))
					state = 0
				else
					state = 2
				end
			end
		elseif state == 4 then
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Forget_Who']))
			UI:TutorTeamMenu()
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			if result > -1 then
				member = GAME:GetPlayerPartyMember(result)
				if not GAME:CanForget(member) then
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Cant_Forget']))
				else
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Forget_What'], member:GetDisplayName(true)))
					state = 5
				end
			else
				state = 0
			end
		elseif state == 5 then
			local result = UI:ForgetMenu(member)
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			if result > -1 then
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Forget_Begin']))
				treasuretown2.Tutor_Sequence()
				move = GAME:GetCharacterSkill(member, result)
				local moveEntry = _DATA:GetSkill(move)
				GAME:ForgetSkill(member, result)
				SOUND:PlayFanfare("Fanfare/LearnSkill")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Tutor_Forget_Success'], member:GetDisplayName(true), moveEntry:GetIconName()))
				state = 0
			else
				state = 4
			end
		end
	end
	
	end	
GROUND:EntTurn(electivire, Direction.Down)
end

function treasuretown2.InteractiveNearby_Touch(obj, activator)

SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(activator, "question", 1)

end

function treasuretown2.Pots_Action (obj, activator)
local player = CH('PLAYER')
--whoever gets the reference, and looks at this line in particular deserves a cookie, welcome to my version of the Director's Commentary, being extremely well hidden because who looks at this stuff?
	if not SV.repeatable.pots then --Omega, count how many Script Variables this mod has.
	
UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(This... [pause=20]is a pot. [pause=0]It contains [pause=25]absolutely nothing. [pause=0]There's more, [pause=20]the other pots also have nothing.)")
	SV.repeatable.pots = true
	
	else
	
		UI:SetSpeaker(player)
		UI:SetSpeakerEmotion("Worried")
		UI:WaitShowDialogue("(It's an empty pot, [pause=10]do I really need to waste time with empty pots?)")
	
	end
end

function treasuretown2.TreasureTownLeftEntrance_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("treasuretown1", "EntranceRight")

end

function treasuretown2.TreasureTownLeave_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("treasuretowncrossroads", "EntranceLeft")

end

function treasuretown2.Pidove_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Happy") --doesn't work yet.
UI:WaitShowDialogue("Huwwo, [pause=10]I'm with my friend!")

GROUND:EntTurn(chara, Direction.Down)

end

function treasuretown2.Cutiefly_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Happy") --Default works fine.
UI:WaitShowDialogue("Good morning!") --If you say 'good morning' back when I say 'good morning', you fell into my trap of saying my catchphrase. *Insert Snatcher voiceclip here*

GROUND:EntTurn(chara, Direction.Up)

end

function treasuretown2.default_initialize(wanderzoneloc, wanderzonesize, wanderspeed, wanderstepmin, wanderstepmax, idledelaymin, idledelaymax)

AI:SetCharacterAI(CH('ariados_roamer'), "what_does_n_stand_for.ai.ground_default", RogueElements.Loc(80, 216), RogueElements.Loc(32, 32), 1, 16, 32, 40, 180) --It's Magic Joel, it's Magic!
AI:SetCharacterAI(CH('Staravia_roamer'), "what_does_n_stand_for.ai.ground_default", RogueElements.Loc(352, 200), RogueElements.Loc(46, 46), 1, 16, 32, 40, 120)
--103 245 / Ariados location / 352 200 - Staravia loc
end

function treasuretown2.ariados_roamer_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("This [color=#FFC663]Treasure Town[color] place certainly feels cozy.")
UI:WaitShowDialogue("But I'll stay in [color=#FFC663]Baram Town[color] for now. [pause=0]The air feels better there.")

end

function treasuretown2.Togetic_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Such a nice day out, [pause=10]don't you agree?~")

GROUND:EntTurn(chara, Direction.DownRight)
end

function treasuretown2.Ledian_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I would love to go on the beach on a sunny day like this. [pause=0]Seriously, [pause=10]it's great!")

GROUND:EntTurn(chara, Direction.DownLeft)
end

function treasuretown2.Politoed_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Another summer day, [pause=10]eh? [pause=0]Hard to believe spring passed on by without saying hello.")

GROUND:EntTurn(chara, Direction.Up)
end

function treasuretown2.Tutor_Sequence(member, moveEntry)

	local chara = CH('Electivire')
	GAME:WaitFrames(10)
	GROUND:CharSetAnim(chara, "Strike", false)
	GAME:WaitFrames(15)
	local emitter = RogueEssence.Content.FlashEmitter()
	emitter.FadeInTime = 2
	emitter.HoldTime = 4
	emitter.FadeOutTime = 2
	emitter.StartColor = Color(0, 0, 0, 0)
	emitter.Layer = DrawLayer.Top
	emitter.Anim = RogueEssence.Content.BGAnimData("White", 0)
	GROUND:PlayVFX(emitter, chara.MapLoc.X, chara.MapLoc.Y)
	SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:WaitFrames(10)
	GROUND:CharSetAnim(chara, "Idle", true)
	GAME:WaitFrames(30)
end

function treasuretown2.Charmeleon_Action(chara, activator)
local Magnemite2 = CH('Magnemite2')
local player = CH('PLAYER')

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("...*Grumble mumble*...")
UI:WaitShowDialogue("...this is stupid...")
UI:WaitShowDialogue("Why do I gotta clean this stupid town?")

GROUND:CharSetEmote(Magnemite2, "notice", 1)
SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
GAME:WaitFrames(40)
GROUND:CharTurnToChar(Magnemite2, activator)

UI:SetSpeaker(Magnemite2)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("ZZT! [pause=0]Citizen! [pause=0]Please move away from the convict!")
GROUND:EntTurn(Magnemite2, Direction.DownRight)

end

function treasuretown2.Magnemite1_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("ZZT! [pause=0]Please move along.")

GROUND:EntTurn(chara, Direction.DownLeft)

end

function treasuretown2.Magnemite2_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("ZZT! [pause=0]Convict is not to be talked to while they are working. [pause=0]ZZT!")

GROUND:EntTurn(chara, Direction.DownRight)

end

function treasuretown2.Staravia_roamer_Action(chara, activator)
local player = CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I was a little curious why the [color=#00FFFF]Kecleon[color] brothers don't sell [color=#32a852]Looplets[color].")
UI:WaitShowDialogue("But then I noticed that the [color=#32a852]Emeras[color] around this region don't appear too often...")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("How strange...")
end

function treasuretown2.Hitmonchan_Action(chara, activator)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Stunned") --Hitmonchan has no emotions.
UI:WaitShowDialogue("Dude, [pause=10]the dojo's completely croaked! [pause=0]Where will we go now, [pause=10]man?")

end

function treasuretown2.Hitmonlee_Action(chara, activator) --I am not a 'dude / bro' man, so I don't like writing these two lol.

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Bro, [pause=10]we have to go somewhere else to train. [pause=0]We can come back later.")

end

function treasuretown2.chapterhidescript()

if SV.chapter.number == 0 then

GROUND:Hide("Charmeleon")
GROUND:Hide("Magnemite1")
GROUND:Hide("Magnemite2")
GROUND:Hide("Staravia_roamer")
GROUND:Hide("Hitmonchan")
GROUND:Hide("Hitmonlee")

elseif SV.chapter.number == 1 then --This is completely unprofessional, stupid, and probably bloating to the script, and Groundmap file,
															--But I want to keep everything tidey so ***I*** know what went wrong, and not jumble through several files.
GROUND:Hide("ariados_roamer")
GROUND:Hide("Togetic")
GROUND:Hide("Politoed")
GROUND:Hide("Ledian")
GROUND:Hide("Pidove")
GROUND:Hide("Cutiefly")

end

end

return treasuretown2

