--[[
    init.lua
    Created: 06/07/2023 00:11:45
    Description: Autogenerated script file for the map treasuretownbeachpath.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local treasuretownbeachpath = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---treasuretownbeachpath.Init(map)
--Engine callback function
function treasuretownbeachpath.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---treasuretownbeachpath.Enter(map)
--Engine callback function
function treasuretownbeachpath.Enter(map)

  GAME:FadeIn(20)

end

---treasuretownbeachpath.Exit(map)
--Engine callback function
function treasuretownbeachpath.Exit(map)


end

---treasuretownbeachpath.Update(map)
--Engine callback function
function treasuretownbeachpath.Update(map)


end

---treasuretownbeachpath.GameSave(map)
--Engine callback function
function treasuretownbeachpath.GameSave(map)


end

---treasuretownbeachpath.GameLoad(map)
--Engine callback function
function treasuretownbeachpath.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function treasuretownbeachpath.PathUp_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("treasuretowncrossroads", "EntranceDown")

end

function treasuretownbeachpath.PathLeft_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("treasuretownbeach", "Entrance")

end
--What a completely normal map. It has no logical use right now. Totally. It's literally the path to the beach, calm your brass.
return treasuretownbeachpath

