--[[
    init.lua
    Created: 05/18/2023 01:15:24
    Description: Autogenerated script file for the map drenchedbluffend.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local drenchedbluffend = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---drenchedbluffend.Init(map)
--Engine callback function
function drenchedbluffend.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---drenchedbluffend.Enter(map)
--Engine callback function
function drenchedbluffend.Enter(map)

	SV.branchwaywoodsentrance.DungeonComplete = false
	if not SV.dungeons.drenchedbluff then
		drenchedbluffend.EndingA(FirstClear)
	else

GROUND:Hide("Madilyn")
GROUND:Hide("poipole")
COMMON.RespawnAllies()

drenchedbluffend.EndingB()

	end

  --GAME:FadeIn(20) --call later, keeps fading in the game when transitioning.

end

---drenchedbluffend.Exit(map)
--Engine callback function
function drenchedbluffend.Exit(map)


end

---drenchedbluffend.Update(map)
--Engine callback function
function drenchedbluffend.Update(map)


end

---drenchedbluffend.GameSave(map)
--Engine callback function
function drenchedbluffend.GameSave(map)


end

---drenchedbluffend.GameLoad(map)
--Engine callback function
function drenchedbluffend.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function drenchedbluffend.EndingA(FirstClear)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

GROUND:CharSetAnim(Madilyn, "Laying", true)
		  --local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Confuse", 1337))
		  --emitter.LocHeight = 5
		  --GROUND:PlayVFX(emitter, 185, 202)
GROUND:CharSetEmote(Madilyn, "confuse", 0)

GAME:CutsceneMode(true)
GAME:MoveCamera(232, 210, 1, false)
GAME:WaitFrames(30)

UI:WaitShowTitle("The Pit of\nDrenched Bluff", 20)
GAME:WaitFrames(60)
UI:WaitHideTitle(20)

GAME:WaitFrames(30)
SOUND:PlayBGM("At The End Of The Road.ogg", true)
GAME:FadeIn(20)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, poipole.CurrentForm.Species, poipole.CurrentForm.Form, poipole.CurrentForm.Skin, poipole.CurrentForm.Gender)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Why won't you wake up already?")
UI:WaitShowDialogue("If you hadn't scared me, [pause=10]I wouldn't have knocked you out.")
GAME:WaitFrames(20)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("But I wish I haven't done that, [pause=10]I don't know where I am.")
UI:WaitShowDialogue("Not only that, [pause=10]you've been asleep for an really long time. [pause=0]I'm starting to get worried.")

GROUND:MoveInDirection(poipole, Direction.UpLeft, 10, false, 1)
GAME:WaitFrames(20)

SOUND:PlayBattleSE("EVT_Egg")

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Hey, [pause=60]come on... [pause=120]Can you please get up? [pause=120]Helloooo? [pause=80]Agh, [pause=10]it's no use. [pause=0]She's knocked out for a while...")

GROUND:MoveInDirection(player, Direction.Up, 60, true, 2)

SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
GROUND:CharSetEmote(player, "exclaim", 1)
GROUND:EntTurn(player, Direction.UpLeft)

GAME:WaitFrames(40)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("(Hey! [pause=0]What is that Pokémon doing to that [color=#00FFFF]Piplup[color]!?)")

GAME:WaitFrames(10)

GROUND:CharAnimateTurn(poipole, Direction.DownRight, 4, false)
GAME:WaitFrames(20)
GROUND:CharAnimateTurn(poipole, Direction.UpLeft, 4, true)
GAME:WaitFrames(20)
SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
GROUND:CharSetEmote(poipole, "exclaim", 1)
GAME:WaitFrames(40)
GROUND:CharAnimateTurn(poipole, Direction.DownRight, 2, false)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, poipole.CurrentForm.Species, poipole.CurrentForm.Form, poipole.CurrentForm.Skin, poipole.CurrentForm.Gender)
UI:SetSpeakerEmotion("Surprised")
UI:WaitShowDialogue("Eek! [pause=0]Where in the world did you come from??")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("...")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Erm... [pause=20]Look, [pause=10]I know this looks absolutely terrible, [pause=10]but-")

local coro1 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether_Sequence(AdamMudkip) end)
local coro2 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether_Sequence(Piks) end)

TASK:JoinCoroutines({coro1,coro2})

GROUND:EntTurn(AdamMudkip, Direction.UpLeft)
GROUND:EntTurn(Piks, Direction.UpLeft)

SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
GROUND:CharSetEmote(Piks, "exclaim", 1)
GAME:WaitFrames(40)

GROUND:EntTurn(poipole, Direction.Down)

UI:SetSpeaker(Piks)
UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)
UI:SetSpeakerEmotion("Angry")
UI:WaitShowDialogue("Hey, [pause=10]you! [pause=0]Get away from [color=#54ebaf]Madilyn[color] this instant!")

SOUND:PlayBattleSE("EVT_Emote_Startled")
GROUND:CharSetEmote(poipole, "shock", 1)
GROUND:CharSetAnim(poipole, "Hurt", false)
GAME:WaitFrames(20)

coro1 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether2_Sequence(poipole) end)
coro2 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether2_Sequence(player) end)
local coro3 = TASK:BranchCoroutine(function()
GAME:WaitFrames(10)
GROUND:EntTurn(Piks, Direction.Up)
GROUND:EntTurn(AdamMudkip, Direction.Up)
end)

TASK:JoinCoroutines({coro1,coro2})

GROUND:MoveInDirection(poipole, Direction.Up, 80, true, 2)

GAME:WaitFrames(30)

UI:SetSpeaker(player, false)
UI:ResetSpeakerLoc()
UI:ResetBounds()
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(Crud, [pause=10]it ran away through the forest...)")

coro1 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether3_Sequence(AdamMudkip) end)
coro2 = TASK:BranchCoroutine(function() drenchedbluffend.movetogether3_Sequence(Piks) end)

TASK:JoinCoroutines({coro1,coro2})

GAME:WaitFrames(20)

GROUND:CharAnimateTurn(AdamMudkip, Direction.DownLeft, 4, true)
UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Hm... [pause=20][color=#54ebaf]Piks[color], [pause=10]what was that purple Pokémon? [pause=0]I never seen it before.")
GROUND:EntTurn(Piks, Direction.UpRight)
GROUND:CharAnimateTurn(player, Direction.Down, 4, true)
GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(070,131)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I'm with you there, [pause=10]I haven't seen anything like that either.")
UI:WaitShowDialogue("If it's really a new Pokémon, [pause=10]then [color=#54ebaf]Madilyn[color] must've been very lucky to find it.")

GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, false)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,130)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("That explains that purple Pokémon, [pause=10]but...")

	if SV.prologue_alts.talked_to_adam_at_cafe == 0 then --This should've been set at the beginning of the game, if it errors, you did something wrong. / This will happen if you do not finish the startup Intro of Branchway Woods. Only through DevMode or some random arbituary SaveGame Edits, will this error ever occur.
	
	UI:WaitShowDialogue("Who are you? [pause=0]You don't look like you're from around here.")
	
	GROUND:EntTurn(Piks, Direction.Up)
	GAME:WaitFrames(20)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
	GROUND:CharSetEmote(Piks, "exclaim", 1)
	GAME:WaitFrames(40)
	
	UI:SetSpeaker(Piks)
	UI:SetSpeakerLoc(070,131)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Oh, [pause=10]look! [pause=0]".. COMMON.GenderCheck(player, "they have", true) .." a [color=#32a852]Treasure Bag[color] with ".. COMMON.GenderCheck(player, "them", false) ..". [pause=0]Maybe ".. COMMON.GenderCheck(player, "they're", false) .." an explorer?")
	
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(AdamMudkip)
	UI:SetSpeakerLoc(185,125)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Seems like it, [pause=10]no badge though.")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("But I could've sworn I saw you at the crossroads. [pause=0]How did you get here so fast?")
	
	GROUND:EntTurn(Piks, Direction.UpRight)
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(Piks)
	UI:SetSpeakerLoc(070,131)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("We did kind of stay on a few floors for longer than usual.")
	UI:WaitShowDialogue("I don't remember fighting a [color=#00FFFF]Gastrodon[color], [pause=10]or an [color=#00FFFF]Armaldo[color] when we first went here.")
	
	GROUND:CharAnimateTurn(AdamMudkip, Direction.DownLeft, 4, true)
	
	UI:SetSpeaker(AdamMudkip)
	UI:SetSpeakerLoc(185,125)
	UI:SetSpeakerEmotion("Pain", true)
	UI:WaitShowDialogue("Oh yeah... [pause=20]That weird issue going around.")

	elseif SV.prologue_alts.talked_to_adam_at_cafe >= 1 then
	
	UI:WaitShowDialogue("You there. [pause=0]You're an adventurer, [pause=10]yes?")
	UI:WaitShowDialogue("I think I saw your face at the café this morning.")
	
	GROUND:EntTurn(Piks, Direction.Up)
	GAME:WaitFrames(40)
	GROUND:EntTurn(Piks, Direction.UpRight)
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(Piks)
	UI:SetSpeakerLoc(070,131)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Ehm, [pause=10]what does that have to do with ".. COMMON.GenderCheck(player, "them", false) .." being here?")
	
	GROUND:CharAnimateTurn(AdamMudkip, Direction.DownLeft, 4, true)
	
	UI:SetSpeaker(AdamMudkip)
	UI:SetSpeakerLoc(185,125)
	UI:SetSpeakerEmotion("Normal", true)
	UI:WaitShowDialogue("Remember how we spent a little while on a few floors? [pause=0]Did anything seem just a bit off?")
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(Piks)
	UI:SetSpeakerLoc(070,131)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("The [color=#00FFFF]Gastrodon[color] and [color=#00FFFF]Armaldo[color] appearing in this dungeon, [pause=10]or the feeling that it's taking longer than ususal?")

	GAME:WaitFrames(10)
	UI:SetSpeaker(AdamMudkip)
	UI:SetSpeakerLoc(185,125)
	UI:SetSpeakerEmotion("Normal", true)
	UI:WaitShowDialogue("Both of them, [pause=10]there's something weird going on that all adventurers should know.")
	
	end

	GROUND:EntTurn(Piks, Direction.Up)
	GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, false)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("There are reports from some Pokémon going around that some dungeons are acting stranger than usual.")
UI:WaitShowDialogue("What I mean is that these dungeons, [pause=10]for whatever reason, [pause=10]are getting stronger.")
UI:WaitShowDialogue("Here's the thing, [pause=10]we're a bit too strong for these quote unquote 'beginner dungeons'.")
UI:WaitShowDialogue("So we're looking for a recruit for just that job, [pause=10]and you fit that job if you're here right now.")

drenchedbluffend.playgame_Choice(Uno)

end

function drenchedbluffend.boringending_Choice(boring)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

SV.prologue_alts.d_bluff_no_counter = 1

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Surprised")
UI:WaitShowDialogue("N-[pause=10]no? [pause=0]Wh-...?")
UI:SetSpeakerEmotion("Worried")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['WantBoringEnd']), true)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
    UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("Wow, [pause=10]uhm... [pause=20]ok.")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("I guess you got somewhere to be, [pause=10]and what-not.")
	UI:WaitShowDialogue("Explorers be exploring, [pause=10]huh?")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Take care of yourself, [pause=10]ok?")
	
	SOUND:PlayBGM("None", true)
	GAME:FadeOut(false, 60)
	
	GAME:WaitFrames(40)
	
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	SOUND:PlayBGM("Pelipper Island.ogg", true)
	
	UI:WaitShowVoiceOver("Project EoN \nDeveloped by: [color=#20c7fa]Logical123[color] \nCoding Support: [color=#fc0373]AudinoWho[color], [color=#ffdd63]Palika[color], and [color=#ff9e3d]Sunkern[color]. \nMisc help: [color=#9696ff]Trio[color](Dialogue referencing). \nAnd those who playtested and gave me feedback.", 210)
	
	GAME:WaitFrames(210)
	SOUND:PlayBGM("None", true)
	
	UI:SetCenter(false)
	UI:SetAutoFinish(false)
	UI:ResetSpeaker()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Wow, [pause=10]what a boring ending.")
	UI:WaitShowDialogue("I don't even think [color=#00FFFF]Arceus[color] would've liked that ending.")
	UI:WaitShowDialogue("Because who in their right mind ends it before their journey even began?")
	UI:WaitShowDialogue("I can control the flow of time without harming the timeline too much, [pause=10]so too bad for you.")
	UI:WaitShowDialogue("Just pretend you said yes, [pause=10]ok?")
	UI:WaitShowDialogue("And also don't tell [color=#00FFFF]Grovyle[color] I'm messing with time...")
	UI:WaitShowDialogue("...Not that you can do that, [pause=10]anyways.")
	
	GAME:FadeIn(40)
	drenchedbluffend.ContinueGame_Choice(Continue)
else

GAME:WaitFrames(20)
UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(070,131)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("...[pause=20]Wait, [pause=10]what? [pause=0]They're not sure if they don't want to...?")
drenchedbluffend.youreannoying_Choice(Uno)
	
end
	--GAME:CutsceneMode(false) --Disabled for testing purposes.
end

function drenchedbluffend.ContinueGame_Choice(Continue)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

SOUND:PlayBGM("Pokémon Square.ogg", true)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Happy")
UI:WaitShowDialogue("Glad to have you around for this!")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I do have to cut your excitement short however, [pause=10]but can you go back to [color=#FFC663]Treasure Town[color] and wait?")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I'm gonna be honest, [pause=10]I wasn't expecting to have a recruitment today.")
GAME:WaitFrames(10)

GROUND:EntTurn(Piks, Direction.UpRight)
UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(070,131)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Me neither, [pause=10]we don't have a bed prepared for ".. COMMON.GenderCheck(player, "them", false) ..".")
UI:WaitShowDialogue("Where will ".. COMMON.GenderCheck(player, "they", false) .." go, [pause=10][color=#54ebaf]Adam[color]?")

GROUND:CharAnimateTurn(AdamMudkip, Direction.DownLeft, 4, true)
GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("I guess our old bedroom in the guild.")
UI:WaitShowDialogue("[color=#00FFFF]Chatot[color] didn't seem to mind too much when [color=#54ebaf]Madilyn[color] was training there.")
UI:WaitShowDialogue("Let's hope he doesn't mind this one too.")

GROUND:EntTurn(Piks, Direction.Up)
GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, false)

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Just head over to [color=#FFC663]Wigglytuff's Guild[color]. [pause=0]We'll handle things here, [pause=10]and meet you there.")

GAME:FadeOut(false, 40)

GAME:WaitFrames(10)
SOUND:PlayBGM("None", true)

GAME:WaitFrames(50)

--COMMON.EndDungeonDay(result, 'treasuretownzone', -1, 0, 4)
SV.dungeons.drenchedbluff = true
GAME:EnterZone('cutscenezone', -1, 2, 0)
GAME:CutsceneMode(false)
end

function drenchedbluffend.playgame_Choice(Uno)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['ContinueGame']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
    drenchedbluffend.ContinueGame_Choice(Continue)
else
    drenchedbluffend.boringending_Choice(boring) --More effective at making sure both Yes outcomes equal the same result.
end

GAME:CutsceneMode(false)

end

function drenchedbluffend.youreannoying_Choice(Uno)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['AnnoyingGame']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
	GAME:WaitFrames(10)
	UI:SetSpeaker(AdamMudkip, false)
	UI:SetSpeakerEmotion("Dizzy")
	UI:SetSpeakerLoc(185,125)
	UI:WaitShowDialogue("(Finally, [pause=10]a straight answer... [pause=20]How hard was that...?)")
	UI:SetSpeaker(AdamMudkip)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("*Ahem*...")
	GAME:WaitFrames(20)
    drenchedbluffend.ContinueGame_Choice(Continue)
else
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("...")
	UI:SetSpeaker(AdamMudkip, false)
	UI:WaitShowDialogue("(Chatot would seriously squawk harshly from this one.)")
    drenchedbluffend.seriouslyannoying_Choice(DosRepeating)
end

GAME:CutsceneMode(false)

end

function drenchedbluffend.seriouslyannoying_Choice(DosRepeating)
local player = CH('PLAYER')
local poipole = CH('poipole')
local AdamMudkip = CH('AdamMudkip')
local Piks = CH('Piks')
local Madilyn = CH('Madilyn')

SV.prologue_alts.d_bluff_no_counter = SV.prologue_alts.d_bluff_no_counter + 1

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried")
UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['AnnoyingGameBoring']), false)
UI:WaitForChoice()
ch = UI:ChoiceResult()
if ch then
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("*Sigh* [pause=20]Wow, [pause=10]ok...")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("I guess you got somewhere to be, [pause=10]probably.")
	UI:WaitShowDialogue("Explorers be exploring, [pause=10]huh?")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Take care of yourself, [pause=10]ok?")
	
	SOUND:PlayBGM("None", true)
	GAME:FadeOut(false, 60)
	
	GAME:WaitFrames(30)

	UI:SetSpeaker(Piks)
	UI:ResetSpeakerLoc()
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue("(What a confusing Pokémon...)")
	
	GAME:WaitFrames(40)
	
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	SOUND:PlayBGM("Pelipper Island.ogg", true)
	
	UI:WaitShowVoiceOver("Project EoN \nDeveloped by: [color=#20c7fa]Logical123[color] \nCoding Support: [color=#fc0373]AudinoWho[color], [color=#ffdd63]Palika[color], and [color=#ff9e3d]Sunkern[color]. \nMisc help: [color=#9696ff]Trio[color](Dialogue referencing). \nAnd those who playtested and gave me feedback.", 210)
	
	GAME:WaitFrames(210)
	SOUND:PlayBGM("None", true)
	
	UI:SetCenter(false)
	UI:SetAutoFinish(false)
	UI:ResetSpeaker()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Wow, [pause=10]what an annoying ending.")
	UI:WaitShowDialogue("I don't even think [color=#00FFFF]Arceus[color] would've liked that ending.")
	UI:WaitShowDialogue("Because who in their right mind ends it before their journey even began?")
	UI:WaitShowDialogue("Nevermind the weird tendency to do... [pause=20]whatever you just did.")
	UI:WaitShowDialogue("However, [pause=10]I can control the flow of time without messing up the timeline too much.")
	UI:WaitShowDialogue("I'm also going to change the fact you never did that.")
	UI:WaitShowDialogue("Seriously, [pause=10]don't do that please.")
	UI:WaitShowDialogue("Just go with the flow, [pause=10]you still have a journey to travel through.")
	
	GAME:FadeIn(40)
	drenchedbluffend.ContinueGame_Choice(Continue)
	
else

		if SV.prologue_alts.d_bluff_no_counter == 3 then

SOUND:PlayBGM("None", true)

GAME:WaitFrames(60)

GROUND:EntTurn(Piks, Direction.UpRight)
GROUND:CharTurnToCharAnimated(AdamMudkip, Piks, 4)

GAME:WaitFrames(60)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("...?")
GAME:WaitFrames(10)
UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(070,131)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("...?")

GAME:WaitFrames(60)

GROUND:CharSetEmote(AdamMudkip, "sweatdrop", 1)
GROUND:CharSetEmote(Piks, "sweatdrop", 1)
SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GAME:WaitFrames(40)

GROUND:EntTurn(Piks, Direction.Up)
GROUND:CharTurnToCharAnimated(AdamMudkip, player, 4)

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerLoc(185,125)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("We're, [pause=10]uh... [pause=20]we're gonna let you be yourself.")
UI:WaitShowDialogue("Which means we're going to just get [color=#54ebaf]Madilyn[color] and leave...")
UI:WaitShowDialogue("So uhm... [pause=20]bye.")

	GAME:FadeOut(false, 60)
	
	GAME:WaitFrames(30)

	UI:ResetSpeakerLoc()
	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("(Whoops, [pause=10]I might've pulled his tail too hard.)")
	UI:WaitShowDialogue("(I don't even remember what I was doing shaking my head like that.)")
	
	GAME:WaitFrames(40)
	
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	SOUND:PlayBGM("Pelipper Island.ogg", true)
	
	UI:WaitShowVoiceOver("Project EoN \nDeveloped by: [color=#20c7fa]Logical123[color] \nCoding Support: [color=#fc0373]AudinoWho[color], [color=#ffdd63]Palika[color], and [color=#ff9e3d]Sunkern[color]. \nMisc help: [color=#9696ff]Trio[color](Dialogue referencing). \nAnd those who playtested and gave me feedback.", 210)
	
	GAME:WaitFrames(210)
	SOUND:PlayBGM("None", true)
	
	UI:SetCenter(false)
	UI:SetAutoFinish(false)
	UI:ResetSpeaker()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("...Are you serious?")
	UI:WaitShowDialogue("What was the point of that...?")
	UI:WaitShowDialogue("*Sigh*...")
	UI:WaitShowDialogue("Well, [pause=10]too bad for you. [pause=0]I can control the flow of time without harming the timeline too much.")
	UI:WaitShowDialogue("And please, [pause=10]no more jokes.")
	UI:WaitShowDialogue("This 'no' thing isn't funny, [pause=10]it never was.")
	UI:WaitShowDialogue("Now, [pause=10]let's just keep this story moving.")
	
	GAME:FadeIn(40)
	drenchedbluffend.ContinueGame_Choice(Continue)

	elseif SV.prologue_alts.d_bluff_no_counter <= 3 then

	GAME:WaitFrames(10)
	UI:SetSpeaker(Piks, false)
	UI:SetSpeakerLoc(070,131)
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue("Oh my [color=#00FFFF]Arceus[color], [pause=10]what is going on...?")
    drenchedbluffend.youreannoying_Choice(Uno)
	
	end
end

GAME:CutsceneMode(false)

end

function drenchedbluffend.movetogether_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 60, false, 2)
end

function drenchedbluffend.movetogether2_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 40, true, 2)
end

function drenchedbluffend.movetogether3_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 38, false, 1)
end

function drenchedbluffend.EndingB()
local player = CH('PLAYER')
local Teammate_1 = CH('Teammate_1')
local Teammate_2 = CH('Teammate_2')
local Teammate_3 = CH('Teammate_3')

GAME:CutsceneMode(true)
GAME:MoveCamera(232, 210, 1, false)

UI:WaitShowTitle("The Pit of\nDrenched Bluff", 20)
GAME:WaitFrames(60)
UI:WaitHideTitle(20)

GAME:WaitFrames(30)

SOUND:PlayBGM("A05. Cave Camp.ogg", true)

local coro1 = TASK:BranchCoroutine(function() 
GAME:FadeIn(20)
end)

local coro2 = TASK:BranchCoroutine(function() drenchedbluffend.PlayerWalkin2_Sequence(player) end)

local coro3 = TASK:BranchCoroutine(function() drenchedbluffend.Teammate1_Sequence(Teammate_1) end)

local coro4 = TASK:BranchCoroutine(function() drenchedbluffend.Teammate2_Sequence(Teammate_2) end)

local coro5 = TASK:BranchCoroutine(function() drenchedbluffend.Teammate3_Sequence(Teammate_3) end)

TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5})

GAME:WaitFrames(20)

UI:ResetSpeaker(false)
UI:SetCenter(true)
UI:WaitShowDialogue("There's nothing to report here.")
UI:WaitShowDialogue("Best to head back for now...")
UI:SetCenter(false)

GAME:FadeOut(false, 20)
GAME:WaitFrames(10)

GAME:EnterZone('treasuretownzone', -1, 17, 0)
GAME:CutsceneMode(false)
end

function drenchedbluffend.PlayerWalkin2_Sequence(character)

GROUND:MoveInDirection(character, Direction.Up, 60, false, 2)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Left, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Right, 4, false)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Up, 4, true)

end

function drenchedbluffend.Teammate1_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 57, false, 2)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Left, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Down, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Right, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Up, 4, true)
end

function drenchedbluffend.Teammate2_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 58, false, 2)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Right, 4, false)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Left, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Up, 4, false)
end

function drenchedbluffend.Teammate3_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 56, false, 2)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Left, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Down, 4, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(character, Direction.Up, 4, false)
end

return drenchedbluffend

