--[[
    init.lua
    Created: 06/14/2023 20:53:07
    Description: Autogenerated script file for the map wigglyguildmaster.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildmaster = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildmaster.Init(map)
--Engine callback function
function wigglyguildmaster.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildmaster.Enter(map)
--Engine callback function
function wigglyguildmaster.Enter(map)

  GAME:FadeIn(20)

end

---wigglyguildmaster.Exit(map)
--Engine callback function
function wigglyguildmaster.Exit(map)


end

---wigglyguildmaster.Update(map)
--Engine callback function
function wigglyguildmaster.Update(map)


end

---wigglyguildmaster.GameSave(map)
--Engine callback function
function wigglyguildmaster.GameSave(map)


end

---wigglyguildmaster.GameLoad(map)
--Engine callback function
function wigglyguildmaster.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function wigglyguildmaster.Wigglytuff_Action(chara, activator)
local player =CH('PLAYER')

GROUND:CharTurnToChar(chara, player)

UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Happy")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['WigglytuffWordsofWisdom'], player:GetDisplayName()))

end

function wigglyguildmaster.BoxofTreasures_Action(obj, activator)
local player =CH('PLAYER')

UI:SetSpeaker(player)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(What are these, [pause=10]really? [pause=0]They look like [color=#32a852]Wonder Orbs[color] of some kind.)")
UI:WaitShowDialogue("(Could be precious rocks of some sort.)")

end

function wigglyguildmaster.InteractiveNearby_Touch(obj, activator)

SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(activator, "question", 1)

end

function wigglyguildmaster.Leave_Touch(obj, activator)
GAME:FadeOut(false, 20)
GAME:EnterGroundMap("wigglyguildbottom", "EntranceSide")
end

return wigglyguildmaster

