--[[
    init.lua
    Created: 08/07/2023 23:54:24
    Description: Autogenerated script file for the map cacklingquarry.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cacklingquarry = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---cacklingquarry.Init(zone)
--Engine callback function
function cacklingquarry.Init(zone)


end

---cacklingquarry.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function cacklingquarry.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---cacklingquarry.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function cacklingquarry.ExitSegment(zone, result, rescue, segmentID, mapID)
   --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_cacklingquarry result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  COMMON.ExitDungeonMissionCheck(result, rescue, zoneId, segmentID)
  if rescue == true then
    COMMON.EndRescue(zone, result, segmentID)
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
  
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
	
  else
    if segmentID == 0 then
			SV.dungeons.cacklingquarry = true
			COMMON.EndDungeonDay(result, 'cacklingquarry', -1, 0, 0)
    else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end

---cacklingquarry.Rescued(zone, name, mail)
--Engine callback function
function cacklingquarry.Rescued(zone, name, mail)


end

return cacklingquarry

