--[[
    init.lua
    Created: 05/09/2024 22:21:02
    Description: Autogenerated script file for the map cutsceneintroforest5.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutsceneintroforest5 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneintroforest5.Init(map)
--Engine callback function
function cutsceneintroforest5.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutsceneintroforest5.Enter(map)
--Engine callback function
function cutsceneintroforest5.Enter(map)

StoryTime()

end

---cutsceneintroforest5.Exit(map)
--Engine callback function
function cutsceneintroforest5.Exit(map)


end

---cutsceneintroforest5.Update(map)
--Engine callback function
function cutsceneintroforest5.Update(map)


end

---cutsceneintroforest5.GameSave(map)
--Engine callback function
function cutsceneintroforest5.GameSave(map)


end

---cutsceneintroforest5.GameLoad(map)
--Engine callback function
function cutsceneintroforest5.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function StoryTime()
local player = CH('PLAYER')

GAME:CutsceneMode(true)
GAME:MoveCamera(230, 115, 1, false)

UI:ResetSpeaker()
UI:WaitShowDialogue(CH('PLAYER'):GetDisplayName() .." emerged from ".. COMMON.GenderCheck(player, "their", false) .." long slumber several days later...")
UI:WaitShowDialogue("...I wouldn't call it a happy awakening though.")
UI:WaitShowDialogue("The inability to speak would put one's state of emotion into a wreck.")
UI:WaitShowDialogue("...".. CH('PLAYER'):GetDisplayName() .." is no different...")

GAME:WaitFrames(40)
GAME:FadeIn(30)

GROUND:MoveToPosition(player, 222, 149, false, 1)
GROUND:CharAnimateTurn(player, Direction.UpLeft, 4, true)

GAME:WaitFrames(60)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Sad")
UI:WaitShowDialogue("...")

GAME:WaitFrames(20)

GROUND:CharAnimateTurn(player, Direction.UpRight, 4, false)
GAME:WaitFrames(10)

GROUND:MoveInDirection(player, Direction.UpRight, 15, false, 1)

SOUND:PlayBGM("None", true)
GAME:FadeOut(false, 5)

UI:ResetSpeaker()
UI:SetSe("Menu/SpeakPast")

UI:WaitShowDialogue("...The Heroes of Sky... [pause=20]The Heroine of Prospect...")
UI:WaitShowDialogue("...They cannot win this battle on their own...")

UI:ResetSe()

GAME:FadeIn(20)

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(player, "shock", 1)
GAME:WaitFrames(40)

GROUND:CharAnimateTurn(player, Direction.DownRight, 2, false)
UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Surprised")
UI:WaitShowDialogue("...!?")
GAME:WaitFrames(10)
GROUND:CharAnimateTurn(player, Direction.UpLeft, 2, true)
UI:WaitShowDialogue("(Who just said that...!?)")
GAME:WaitFrames(10)
GROUND:CharAnimateTurn(player, Direction.DownRight, 2, false)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(player, Direction.UpLeft, 2, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(player, Direction.DownLeft, 2, true)
GAME:WaitFrames(15)
GROUND:CharAnimateTurn(player, Direction.DownRight, 2, true)
GAME:WaitFrames(30)
GROUND:CharAnimateTurn(player, Direction.UpRight, 4, true)

GAME:WaitFrames(20)

GROUND:CharAnimateTurn(player, Direction.UpRight, 4, false)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(Oh, [pause=10]I'm going crazy...)")
UI:WaitShowDialogue("(Did someone actually say that, [pause=10]or did I remember something just now...?)")
UI:WaitShowDialogue("(There's no way I'd remember something like that. [pause=0]Nobody I know has that voice...)")
UI:WaitShowDialogue("(It wasn't mine either... [pause=20]I can't understand why I can't speak, [pause=10]but I know I didn't say that.)")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(But what do those words even mean? [pause=0]Who's fighting who that needs me...?)")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(I don't even think I can help either... [pause=20]My body feels so weak... [pause=20]Like a [color=#00FFFF]Caterpie[color] who was recently hatched...)")
UI:WaitShowDialogue("(I'm in no shape to help anybody, [pause=10]much less myself...)")

GROUND:EntTurn(player, Direction.Right)
GAME:WaitFrames(40)

UI:WaitShowDialogue("(Nnf, [pause=10]maybe the weakness is temporary...)[br](If I start training in the [color=#FFC663]Sky Region[color], [pause=10]maybe I'll feel a little better...)")
UI:WaitShowDialogue("(I heard the region's great for training...)")
UI:WaitShowDialogue("(There should be a port close to here that takes me to it, [pause=10]just down the mountain.)")

GROUND:MoveInDirection(player, Direction.UpRight, 30, false, 1)
GROUND:MoveInDirection(player, Direction.Right, 30, false, 1)
--GROUND:CharAnimateTurn(player, Direction.DownRight, 4, false)
--GAME:WaitFrames(10)

local coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(player, Direction.DownRight, 40, false, 1)
end)

local coro2 = TASK:BranchCoroutine(function()
--GAME:WaitFrames(20)
GAME:FadeOut(false, 30)
end)

TASK:JoinCoroutines({coro1,coro2})

GAME:WaitFrames(60)

UI:ResetSpeaker(false)

	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	
--UI:WaitShowDialogue("Pokémon Mystery Dungeon: Origins has a different gameplay style compared to the other games.")
--UI:WaitShowDialogue("Do you want to play the tutorial dungeon?\nNote: Items and EXP will not be saved.")
UI:WaitShowDialogue("Currently, at the time of this update, the Tutorial Dungeon is under works.")
UI:WaitShowDialogue("You won't be able to play it right now.") --Delete once tutorial dungeon done.

GAME:WaitFrames(30)

GAME:CutsceneMode(false)

GAME:EnterGroundMap("cutsceneintrodock6", "Entrance")
end

return cutsceneintroforest5

