--[[
    init.lua
    Created: 04/16/2024 20:42:15
    Description: Autogenerated script file for the map intro.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local intro = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---intro.Init(zone)
--Engine callback function
function intro.Init(zone)


end

---intro.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function intro.EnterSegment(zone, rescuing, segmentID, mapID)


end

---intro.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function intro.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---intro.Rescued(zone, name, mail)
--Engine callback function
function intro.Rescued(zone, name, mail)


end

return intro

