--[[
    init.lua
    Created: 01/13/2024 21:48:46
    Description: Autogenerated script file for the map cutscenecrumblingcanyon2.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutscenecrumblingcanyon2 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutscenecrumblingcanyon2.Init(map)
--Engine callback function
function cutscenecrumblingcanyon2.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutscenecrumblingcanyon2.Enter(map)
--Engine callback function
function cutscenecrumblingcanyon2.Enter(map)

cutscenecanyon2()

end

---cutscenecrumblingcanyon2.Exit(map)
--Engine callback function
function cutscenecrumblingcanyon2.Exit(map)


end

---cutscenecrumblingcanyon2.Update(map)
--Engine callback function
function cutscenecrumblingcanyon2.Update(map)


end

---cutscenecrumblingcanyon2.GameSave(map)
--Engine callback function
function cutscenecrumblingcanyon2.GameSave(map)


end

---cutscenecrumblingcanyon2.GameLoad(map)
--Engine callback function
function cutscenecrumblingcanyon2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function cutscenecanyon2()
local player = CH('PLAYER')
local Madilyn = CH('Madilyn')
local Kecleon = CH('Kecleon')

GAME:CutsceneMode(true)
GAME:MoveCamera(200, 100, 1, false)
GROUND:AddMapStatus('clouds_overhead')

GAME:FadeIn(20)
GAME:WaitFrames(20)

local coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(player, Direction.Up, 40, false, 2)
end)

local coro2 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(Madilyn, Direction.Up, 40, false, 2)
GAME:WaitFrames(5)
GROUND:EntTurn(Madilyn, Direction.UpRight)
end)

local coro3 = TASK:BranchCoroutine(function()
GAME:WaitFrames(10)
GROUND:CharSetEmote(Kecleon, "question", 1)
SOUND:PlayBattleSE("EVT_Emote_Confused")
GAME:WaitFrames(40)
GROUND:CharAnimateTurn(Kecleon, Direction.DownLeft, 4, true)
end)

GAME:WaitFrames(60)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("There you are, [pause=10][color=#54ebaf]Madilyn[color]. [pause=0]I thought you were right behind me.")

GAME:WaitFrames(10)

UI:SetSpeaker(Madilyn)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Yeah yeah, [pause=10]I know. [pause=0]I got distracted. [pause=0]Just wanted to talk to ".. CH('PLAYER'):GetDisplayName() .." about something.")
UI:WaitShowDialogue("Anyways, [pause=10]where are we? [pause=0]I never seen this place before.")

GAME:WaitFrames(10)

UI:SetSpeaker(Kecleon)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("This dungeon is called [color=#FFC663]Crumbling Canyonway[color].")
UI:WaitShowDialogue("Besides going the lengthier route, [pause=10]or flying over the mountain, [pause=10]this is the quickest footpath through it.")

GROUND:EntTurn(Madilyn, Direction.Up)
GAME:WaitFrames(10)

UI:SetSpeaker(Madilyn)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Yeesh, [pause=10]we have to traverse through that...")

GAME:WaitFrames(30)
GROUND:CharAnimateTurn(Madilyn, Direction.DownRight, 4, false)
GROUND:EntTurn(player, Direction.UpLeft)

UI:WaitShowDialogue("".. CH('PLAYER'):GetDisplayName() ..", [pause=10]you're going to be the leader for this mission.")
UI:WaitShowDialogue("I'll make sure we don't get hit from behind. [pause=0]You should be able to handle whatever gets thrown at you.")

if SV.playerinfo.job == 'Prepared' or 'Helper' then

UI:WaitShowDialogue("If anything, [pause=10]you're more than qualified to help [color=#00FFFF]Kecleon[color] through this dungeon.") --196 076

end

local coro1 = TASK:BranchCoroutine(function()
GROUND:MoveToPosition(player, 196, 076, false, 1)
end)

local coro2 = TASK:BranchCoroutine(function()
GROUND:EntTurn(Madilyn, Direction.Right)
GAME:WaitFrames(5)
GROUND:EntTurn(Madilyn, Direction.UpRight)
GAME:WaitFrames(5)
end)

local coro3 = TASK:BranchCoroutine(function()
GROUND:CharAnimateTurn(Kecleon, Direction.UpLeft, 2, false)
end)

GAME:WaitFrames(10)
GAME:FadeOut(false, 20)
GAME:WaitFrames(20)
GAME:EnterDungeon('roadwalkpathway', 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, true)

GAME:CutsceneMode(false)
end

return cutscenecrumblingcanyon2

