--[[
    init.lua
    Created: 08/09/2024 21:25:47
    Description: Autogenerated script file for the map cutsceneintrofinalactualreal8.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local cutsceneintrofinalactualreal8 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneintrofinalactualreal8.Init(map)
--Engine callback function
function cutsceneintrofinalactualreal8.Init(map)


end

---cutsceneintrofinalactualreal8.Enter(map)
--Engine callback function
function cutsceneintrofinalactualreal8.Enter(map)

FINALCUTSCENEISWEAR()

end

---cutsceneintrofinalactualreal8.Exit(map)
--Engine callback function
function cutsceneintrofinalactualreal8.Exit(map)


end

---cutsceneintrofinalactualreal8.Update(map)
--Engine callback function
function cutsceneintrofinalactualreal8.Update(map)


end

---cutsceneintrofinalactualreal8.GameSave(map)
--Engine callback function
function cutsceneintrofinalactualreal8.GameSave(map)


end

---cutsceneintrofinalactualreal8.GameLoad(map)
--Engine callback function
function cutsceneintrofinalactualreal8.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function FINALCUTSCENEISWEAR()
local player = CH('PLAYER')
local Thievul = CH('Thievul')
local Purrloin = CH('Purrloin')
local Medallion = OBJ('Medallion') --Yes, this works. No, I will not take complaints about this. Deal with my awful programming (as long as it works).
local walkLoop = false

GROUND:AddMapStatus("sunset")
GAME:CutsceneMode(true)
GAME:MoveCamera(288, 216, 1, false)
GAME:FadeIn(20)
GAME:WaitFrames(20)

GROUND:MoveToPosition(player, 280, 230, false, 2)
GAME:MoveCamera(-000, -022, 1, true)
--288 216 / 230 player

local coro1 = TASK:BranchCoroutine(function()

	while not walkLoop do
	
		GROUND:MoveInDirection(player, Direction.Left, 5, false, 2)
	
	end

end)

local coro2 = TASK:BranchCoroutine(function()

	while not walkLoop do
	
		GROUND:MoveInDirection(Thievul, Direction.Left, 5, false, 2)
	
	end

end)

local coro3 = TASK:BranchCoroutine(function()  --You might thing 3 coros for a simple function is unnecessary, but I say 'I don't care'. If it works, then it works.

	while not walkLoop do
	
		GROUND:MoveInDirection(Purrloin, Direction.Left, 5, false, 2)
	
	end

end)

GAME:WaitFrames(40)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Looks like the sun's setting...)")
UI:WaitShowDialogue("(I should get out of the forest while I can before that happens...)")
UI:WaitShowDialogue("(There's a dungeon near here too, [pause=10]apparently it's dungeon magic causes branches to fall and block the path...)")
UI:WaitShowDialogue("(That's how the name [color=#FFC663]Branchway Woods[color] came to be for this forest.)")

GAME:WaitFrames(60)

walkLoop = true

GROUND:EntTurn(Thievul, Direction.DownLeft)
GROUND:CharSetAnim(Thievul, "Sleep", true)
GROUND:EntTurn(Purrloin, Direction.UpRight)

GROUND:MoveInDirection(player, Direction.Left, 20, false, 2)

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(player, "question", 1)
GAME:WaitFrames(40)

UI:WaitShowDialogue("(Huh...? [pause=0]Who are those two?)")

GROUND:MoveInDirection(player, Direction.Left, 40, false, 1)

--GAME:MoveCamera(-070, -022, 60, true)
GAME:MoveCamera(player.MapLoc.X-62, player.MapLoc.Y-14, 60, false) --Adjust 8 pixels down for both X and Y. Use Relative first before using this.

GAME:WaitFrames(30)

UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Wake up, [pause=10]you [color=#00FFFF]Slacking[color]!")
UI:WaitShowDialogue("There's better things to be doing than laying down here!")

GAME:WaitFrames(10)
UI:SetSpeakerLoc(128, 65)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Dizzy", true)
UI:WaitShowDialogue("Zzz... [pause=20]grumble grumble....")

GAME:WaitFrames(20)
SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(player, "sweatdrop", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(player, false)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("(What a... [pause=20]colorful duo.)")
UI:WaitShowDialogue("(Not sure what their deal is. [pause=0]They look pretty bruised up.)")

GROUND:EntTurn(player, Direction.DownLeft)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("(But they might know who dropped this... [pause=20]thing.)")
UI:WaitShowDialogue("(Worth a shot, [pause=10]anyways.)")

GROUND:EntTurn(player, Direction.Left)
GAME:WaitFrames(10)

GROUND:MoveInDirection(player, Direction.Left, 30, false, 1)

coro1 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(player, Direction.Left, 20, false, 1)

end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(20)
GROUND:EntTurn(Purrloin, Direction.Right)
GAME:WaitFrames(5)
SOUND:PlayBattleSE("EVT_Emote_Exclaim")
GROUND:CharSetEmote(Purrloin, "exclaim", 1)
GAME:WaitFrames(40)

GROUND:MoveInDirection(Purrloin, Direction.Right, 30, false, 1)

end)

TASK:JoinCoroutines({coro1,coro2})

UI:ResetSpeakerLoc()
UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("What'dya think you're...") --This was originally one line, but I had to split it because the emote didn't seem to time itself properly.
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Huh? [pause=0]What's that thing you're holding?")

GROUND:TeleportTo(Medallion,player.MapLoc.X-20, player.MapLoc.Y)
SOUND:PlayBattleSE("EVT_CH02_Item_Place")

GAME:WaitFrames(30)
GROUND:MoveInDirection(Purrloin, Direction.Right, 20, false, 1)
GROUND:EntTurn(Purrloin, Direction.UpRight)
GAME:WaitFrames(30)

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(Purrloin, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeakerLoc(40, 125)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Huh? [pause=0]Isn't that the...")

GROUND:CharAnimateTurn(Purrloin, Direction.UpLeft, 4, true)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("[color=#00FFFF]Thievul[color], [pause=10]check out what this ".. _DATA:GetMonster(CH('PLAYER').CurrentForm.Species):GetColoredName() .." just showed us.")
UI:WaitShowDialogue("Isn't this that coin you've been looking for?")

GROUND:CharSetEmote(Purrloin, "exclaim", 1)
GROUND:CharSetAnim(Purrloin, "hurt", false)
GROUND:CharSetAnim(Thievul, "hop", false)
SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(Thievul, "shock", 1)
GROUND:AnimateInDirection(player, "Hurt", Direction.Left, Direction.Right, 20, 3, 1)
SOUND:PlayBGM("None", true)

GAME:WaitFrames(40)

UI:SetSpeakerLoc(128, 65)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Angry", true)
UI:WaitShowDialogue("A coin? [pause=0]No, [pause=10]it's a medallion!")

GAME:WaitFrames(30)

GROUND:CharAnimateTurn(Thievul, Direction.DownRight, 4, true)

GAME:WaitFrames(40)

GROUND:EntTurn(Thievul, Direction.Right)
GAME:WaitFrames(40)

SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(Thievul, "sweatdrop", 1)
GAME:WaitFrames(40)
SOUND:PlayBGM("Strange Huh.ogg", true)

UI:SetSpeakerLoc(58, 65)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Oh... [pause=20]whoops.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("My apologies. [pause=0]I've been having... [pause=20]restless dreams.")
UI:WaitShowDialogue("I've been looking for that medallion there on the ground for quite some time now...")

GAME:WaitFrames(10)

UI:SetSpeakerLoc(40, 125)
UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I guess you have, [pause=10]but I honestly don't understand what you want it for.")
UI:WaitShowDialogue("This thing here just looks like a rusty coin... [pause=20]is it really 'treasure'?")

GROUND:EntTurn(Thievul, Direction.DownRight)
GROUND:CharSetEmote(Thievul, "angry", 0)
GAME:WaitFrames(10)

UI:SetSpeaker(Thievul)
UI:SetSpeakerLoc(58, 65)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Shh! [pause=0]...It's a treasure alright, [pause=10]but don't let ".. COMMON.GenderCheck(player, "them", false) .." know that...!")

SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(player, "sweatdrop", 1)
GAME:WaitFrames(40)

UI:SetSpeakerLoc(264,131)
UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("(You can say that, [pause=10]but uhm...)")
UI:WaitShowDialogue("(You two don't really look like you trust each other...)")

GROUND:CharSetEmote(Thievul, "", 0)

coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(player, Direction.Left, 20, false, 1)
end)

coro2 = TASK:BranchCoroutine(function()
GROUND:EntTurn(Thievul, Direction.Right)
GAME:WaitFrames(10)
end)

GROUND:CharAnimateTurn(Purrloin, Direction.Right, 4, false)

TASK:JoinCoroutines({coro1,coro2})

UI:SetSpeakerLoc(58, 65)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Normal")

coro1 = TASK:BranchCoroutine(function()
UI:WaitShowTimedDialogue("Regardless... [pause=20]It'd be fantastic if you would return what is r[emote=worried]ightfully... [pause=30]ours...", 60)
end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(60)
GROUND:Hide("Medallion")
GAME:WaitFrames(10)

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(Purrloin, "shock", 1)
GAME:WaitFrames(10)

GROUND:AnimateInDirection(player, "Walk", Direction.Left, Direction.Right, 20, 3, 1)

end)

TASK:JoinCoroutines({coro1,coro2})

GAME:WaitFrames(60)

UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Ehm... [pause=20]W-why did you pick it back up? [pause=0]What's with the head-tilting?")

GAME:WaitFrames(30)

SOUND:PlayBattleSE("EVT_Emote_Exclaim")
GROUND:CharSetEmote(Purrloin, "exclaim", 1)
GAME:WaitFrames(20)

UI:SetSpeaker(Purrloin)
UI:SetSpeakerLoc(40, 125)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Oh. I think I get what ".. COMMON.GenderCheck(player, "they're", false) .." trying to say.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I think ".. COMMON.GenderCheck(player, "they're", false) .." saying... [pause=20]'finder's keepers'.")

SOUND:PlayBGM("None", true)
SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(Thievul, "shock", 1)
GROUND:EntTurn(Thievul, Direction.DownRight)
GROUND:CharSetEmote(player, "shock", 1)
GAME:WaitFrames(40)

UI:SetSpeakerLoc(224,131)
UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Surprised", true)
UI:WaitShowDialogue("(W-wha...?! [pause=0]Where in the world did she even get that idea from??)")

GROUND:CharSetEmote(Thievul, "angry", 0)
GAME:WaitFrames(10)

UI:SetSpeakerLoc(58, 65)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Angry")
UI:WaitShowDialogue("Are you daft?! [pause=0]Why in [color=#00FFFF]Arceus[color]' name would you even say that??")

GROUND:CharSetEmote(Purrloin, "angry", 0)
GROUND:CharAnimateTurn(Purrloin, Direction.UpLeft, 4, true)
GAME:WaitFrames(10)
SOUND:PlayBGM("Air of Unease.ogg", true)

UI:SetSpeakerLoc(40, 125)
UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Angry")
UI:WaitShowDialogue("Says Mr. Fox Face! [pause=0]This is a stupid charade, [pause=10]why can't we just beat this loser up and take the thing already!?")

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(player, "shock", 1)
GAME:WaitFrames(40)

GROUND:CharSetAnim(Thievul, "charge", true)

UI:SetSpeakerLoc(58, 65)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Angry")
UI:WaitShowDialogue("It's not my fault we lost that battle with the Zorua in the first place!")
UI:WaitShowDialogue("The little scamp brought [color=#32a852]Blast Seeds[color] with him!")

GROUND:CharSetAnim(Purrloin, "Charge", true)
GAME:WaitFrames(10)

UI:SetSpeakerLoc(40, 125)
UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Angry")
UI:WaitShowDialogue("Maybe we should've brought some too, [pause=10]so I can take you all the way to [color=#00FFFF]Rayquaza[color]!")

SOUND:PlayBattleSE("EVT_Emote_Exclaim")
GROUND:CharSetEmote(player, "exclaim", 1)
GAME:WaitFrames(20)

UI:SetSpeakerLoc(224,131)
UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Surprised", true)
UI:WaitShowDialogue("(Th-they're fighting!)")
UI:SetSpeakerEmotion("Determined", true)
UI:WaitShowDialogue("(Now's my chance to get out of here...!)")

GROUND:CharAnimateTurn(player, Direction.Down, 4, true)
GAME:WaitFrames(10)

coro1 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(player, Direction.Down, 20, false, 3) end)
coro2 = TASK:BranchCoroutine(function() SOUND:PlayBattleSE("_UNK_EVT_023") GAME:FadeOut(false, 10) end) --Does this work?

TASK:JoinCoroutines({coro1,coro2})

SOUND:PlayBGM("None", true, 60)
GAME:WaitFrames(30)

UI:SetSpeaker('[color=#00FFFF]Purrloin[color]', true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("Huh? Where did that little ".. _DATA:GetMonster(CH('PLAYER').CurrentForm.Species):GetColoredName() .." go?")

GAME:WaitFrames(10)

UI:SetSpeaker('[color=#00FFFF]Thievul[color]', true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("Grahh!! Get off me, and go chase ".. COMMON.GenderCheck(player, "them", false) .."!")
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they are", true) .." going to give us that medallion today!")

GAME:WaitFrames(10)

UI:SetSpeaker('[color=#00FFFF]Purrloin[color]', true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("Yeah yeah, [pause=10]I'm on it already, [pause=10]Mr. Fox Face!")
UI:WaitShowDialogue("Don't have to tell me twice!")

GAME:WaitFrames(10)

UI:SetSpeaker('[color=#00FFFF]Thievul[color]', true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("Stop calling me that!")

GAME:WaitFrames(60)

UI:SetCenter(true)
UI:SetAutoFinish(true)

UI:WaitShowVoiceOver("Your journey begins here...", 90)
GAME:WaitFrames(90)
UI:WaitShowVoiceOver("Project EoN v0.2.3\n\n\nPresented and Developed by: [color=#20c7fa]Logical123[color]", 210)

UI:SetCenter(false)
UI:SetAutoFinish(false)
GAME:WaitFrames(60)

GAME:EnterGroundMap('branchwaywoods','BranchwayWoodsEntrance','Entrance',false)

GAME:CutsceneMode(false)
end

return cutsceneintrofinalactualreal8

