--[[
    init.lua
    Created: 06/16/2023 19:00:03
    Description: Autogenerated script file for the map cutsceneguildent.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutsceneguildent = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutsceneguildent.Init(map)
--Engine callback function
function cutsceneguildent.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutsceneguildent.Enter(map)
--Engine callback function
function cutsceneguildent.Enter(map)

  cutsceneguildent.OnlyCutscene(prologueend)
  --GAME:FadeIn(20)

end

---cutsceneguildent.Exit(map)
--Engine callback function
function cutsceneguildent.Exit(map)


end

---cutsceneguildent.Update(map)
--Engine callback function
function cutsceneguildent.Update(map)


end

---cutsceneguildent.GameSave(map)
--Engine callback function
function cutsceneguildent.GameSave(map)


end

---cutsceneguildent.GameLoad(map)
--Engine callback function
function cutsceneguildent.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function cutsceneguildent.OnlyCutscene(prologueend)

local player =CH('PLAYER')
local Madilyn =CH('Madilyn')
local AdamMudkip =CH('AdamMudkip')
local Piks =CH('Piks')
local Chatot =CH('Chatot')

GAME:MoveCamera(240, 300, 1, false)
GAME:CutsceneMode(true)

local coro1 = TASK:BranchCoroutine(function() cutsceneguildent.FadeInWalkLeft_Sequence(player) end)
local coro2 = TASK:BranchCoroutine(function() cutsceneguildent.FadeInWalkLeft2_Sequence(player) end)

TASK:JoinCoroutines({coro1,coro2})

GROUND:CharAnimateTurn(player, Direction.Right, 4, true)
GAME:WaitFrames(10)

GROUND:MoveInDirection(player, Direction.Right, 23, false, 1)

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
    GROUND:CharSetEmote(player, "exclaim", 1)
	
	UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['NoNameCallout']))
	
	GROUND:CharAnimateTurn(player, Direction.Down, 4, false)
	
local coro1 = TASK:BranchCoroutine(function() cutsceneguildent.TrioWalkIn_Sequence(AdamMudkip) end)
local coro2 = TASK:BranchCoroutine(function() cutsceneguildent.TrioWalkIn_Sequence(Piks) end)
local coro3 = TASK:BranchCoroutine(function() cutsceneguildent.TrioWalkIn_Sequence(Madilyn) end)

TASK:JoinCoroutines({coro1,coro2,coro3})

GAME:WaitFrames(20)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Sorry about that, [pause=10]I didn't think it'd turn sunset by the time we got back.")

GAME:WaitFrames(20)
GROUND:EntTurn(Madilyn, Direction.UpLeft)

UI:SetSpeaker(Madilyn)
UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("So who is this, [pause=10]anyways?")
GROUND:CharAnimateTurn(Piks, Direction.DownLeft, 4, true)
UI:WaitShowDialogue("Why can't we just go home?")

GROUND:CharAnimateTurn(AdamMudkip, Direction.DownRight, 4, false)
GAME:WaitFrames(20)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:ResetBounds()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Uh, [pause=10]good question.")

if SV.prologue_alts.talked_to_adam_at_cafe >= 1 then

UI:WaitShowDialogue("I saw ".. COMMON.GenderCheck(player, "them", false) .." at the Café this morning, [pause=10]but ".. COMMON.GenderCheck(player, "they", false) .." didn't tell me anything.")
UI:WaitShowDialogue("It was a pretty one-sided talk.")

else

UI:WaitShowDialogue("I have no idea.")
UI:WaitShowDialogue("We didn't really introduce ourselves too well.")

end

GAME:WaitFrames(20)
	GROUND:CharSetEmote(Madilyn, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GAME:WaitFrames(40)

UI:SetSpeaker(Madilyn)
UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("So... [pause=20]a complete stranger.")

SOUND:PlayBattleSE("EVT_Emote_Sweating")
GROUND:CharSetEmote(AdamMudkip, "sweating", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:ResetBounds()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Yes, [pause=10]but...")

GAME:WaitFrames(10)

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")

    GROUND:CharSetEmote(AdamMudkip, "exclaim", 1)
	GROUND:CharSetEmote(Piks, "exclaim", 1)
	GROUND:CharSetEmote(Madilyn, "exclaim", 1)
	GROUND:CharSetEmote(player, "exclaim", 1)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['ChatotSpeaks']))

GROUND:EntTurn(Madilyn, Direction.Up)

local coro1 = TASK:BranchCoroutine(function() cutsceneguildent.TurnAround_Sequence(AdamMudkip) end)
local coro2 = TASK:BranchCoroutine(function() cutsceneguildent.TurnAround_Sequence(player) end)
local coro3 = TASK:BranchCoroutine(function() cutsceneguildent.TurnAround_Sequence(Piks) end)

TASK:JoinCoroutines({coro1,coro2,coro3})

GROUND:MoveInDirection(Chatot, Direction.Down, 50, false, 2)

SOUND:PlayBattleSE("EVT_Emote_Exclaim")
GROUND:CharSetEmote(Chatot, "exclaim", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(Chatot)
UI:SetSpeakerLoc(090,060)

if SV.prologue_alts.chatot_greeted then

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Hm? [pause=0]You again?")
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Didn't I tell you that we aren't accepting visitors?")

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(AdamMudkip, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Hold on [color=#00FFFF]Chatot[color], [pause=10]you know this one?")

GAME:WaitFrames(10)
UI:SetSpeaker(Chatot)
UI:SetSpeakerLoc(180,060)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Not in the slightest, [pause=10]".. COMMON.GenderCheck(player, "they", false) .." came up to the entrance of the guild earlier.")
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("I had no idea why ".. COMMON.GenderCheck(player, "they", false) .." were up here to begin with, [pause=10]but I told ".. COMMON.GenderCheck(player, "them", false) .." to leave.")

	GROUND:CharSetEmote(AdamMudkip, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GAME:WaitFrames(40)
	
	UI:SetSpeaker(AdamMudkip)
	UI:ResetSpeakerLoc()
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Huh...")
	
	if SV.prologue_alts.talked_to_adam_at_cafe >= 1 then
	UI:WaitShowDialogue("This one's pretty explorative...")
	end

else --if the player hasn't met Chatot before finishing D.B then

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Hm? [pause=0]Who's your new friend?")

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("This would be our new recruit.")
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they're", true) .." going to be helping us unravel the weird anomaly happening around here.")
GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Normal", true)
UI:WaitShowDialogue("Yeah! [pause=0]This one went through [color=#FFC663]Drenched Bluff[color] while it had stronger Pokémon in it.")
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they'll", true) .." be perfect for experiencing any strange changes to the dungeons around here.")

GAME:WaitFrames(10)

UI:SetSpeaker(Chatot)
UI:SetSpeakerLoc(090,060)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Uh huh... [pause=20]How very interesting...")

GROUND:CharAnimateTurn(Chatot, Direction.Up, 4, false)

UI:WaitShowDialogue("I wonder how long ".. COMMON.GenderCheck(player, "they'll", false) .." stay for...")

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(AdamMudkip, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I couldn't hear you, [pause=10]were you saying something?")

GROUND:CharAnimateTurn(Chatot, Direction.Down, 4, true)

end
GAME:WaitFrames(10)

UI:SetSpeaker(Chatot)
UI:SetSpeakerLoc(90,060)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("*Ahem* [pause=10]Enough with your new friend.")
UI:WaitShowDialogue("I'll have to ask the Guildmaster if you're allowed to have ".. COMMON.GenderCheck(player, "them", false) .." here.")
UI:WaitShowDialogue("And I hate to ask, [pause=10]but what is ".. COMMON.GenderCheck(player, "their", false) .." name, [pause=10]exactly?")
UI:WaitShowDialogue("I can't have a guild member going around without a name to call ".. COMMON.GenderCheck(player, "them", false) ..".")

SOUND:PlayBattleSE("EVT_Emote_Sweating")
GROUND:CharSetEmote(AdamMudkip, "sweating", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Uhm... [pause=20]About that...")

if SV.prologue_alts.talked_to_adam_at_cafe >= 1 then
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they", true) .." haven't spoken once.")
UI:WaitShowDialogue("I'm guessing ".. COMMON.GenderCheck(player, "they're", false) .." not capable of talking...")
else
UI:WaitShowDialogue("I don't even know if ".. COMMON.GenderCheck(player, "they", false) .." can talk or not...")
UI:WaitShowDialogue("But for whatever reason, [pause=10]" .. COMMON.GenderCheck(player, "they're", false) .." staying shut.")
end

GROUND:CharSetAnim(Chatot, "Special0", false)
SOUND:PlayBattleSE("EVT_Chatot_Flutter")
GAME:WaitFrames(30)

UI:SetSpeaker(Chatot)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Then you better make ".. COMMON.GenderCheck(player, "them", false) .." come up with something, [pause=10]or ".. COMMON.GenderCheck(player, "they're", false) .." staying outside in the cold!")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("*Sigh...*[pause=20]")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Sit here for a second, [pause=10]I have to check on something quickly.")

GROUND:CharAnimateTurn(Chatot, Direction.Up, 4, false)
GAME:WaitFrames(20)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("What awful timing for a fever...")

GROUND:MoveInDirection(Chatot, Direction.Up, 60, false, 2)

GAME:WaitFrames(30)

GROUND:CharAnimateTurn(AdamMudkip, Direction.Right, 4, false)
GROUND:CharAnimateTurn(Piks, Direction.Left, 4, true)
GAME:WaitFrames(20)

UI:SetSpeaker(AdamMudkip)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("He seems more... [pause=20]agitated than usual.")

GAME:WaitFrames(10)

UI:SetSpeaker(Piks)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Yeah... [pause=20]what's going on with him?")

GAME:WaitFrames(10)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I dunno, [pause=10]but since we're waiting...")

GROUND:EntTurn(Piks, Direction.UpLeft)
GROUND:MoveInDirection(AdamMudkip, Direction.Up, 15, false, 1)
GROUND:EntTurn(AdamMudkip, Direction.UpRight)
GAME:WaitFrames(10)

UI:WaitShowDialogue("Uh, [pause=10]turn this way, [pause=10]please.")

GROUND:CharAnimateTurn(player, Direction.DownLeft, 4, true)
GAME:WaitFrames(10)

UI:WaitShowDialogue("I know you can't, [pause=10]or won't, [pause=10]talk to us, [pause=10]but you *can* write, [pause=10]I hope?")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I guess I'm lucky I brought my journal with me, [pause=10]otherwise your name would've been through charades.")
UI:SetSpeaker(AdamMudkip, false)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(It would've ended terribly, [pause=10]I suck at charades.)")

SOUND:PlayBattleSE("EVT_CH02_Item_Place")

GAME:WaitFrames(20)
	
UI:ResetSpeaker(false)
UI:SetCenter(true)
UI:WaitShowDialogue("The [color=#00FFFF]Mudkip[color] hands you a notebook with an empty page, and a writing tool.")
UI:SetCenter(false)

GAME:WaitFrames(20)

	GROUND:CharSetEmote(player, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GAME:WaitFrames(40)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(That's one way to get my name.)")
UI:WaitShowDialogue("(But I can't speak, [pause=10]so this is the only way I can say it.)")

SOUND:PlayBattleSE("_UNK_EVT_028")
GAME:WaitFrames(50)

UI:WaitShowDialogue("(There we go, [pause=10]all written down for him.)")
UI:WaitShowDialogue("(I hope he can read my handwriting. [pause=0]I can barely understand his...)")

SOUND:PlayBattleSE("EVT_CH02_Item_Place")
GAME:WaitFrames(30)

UI:ResetSpeaker(false)
UI:SetSpeakerEmotion("Normal")
UI:SetCenter(true)
UI:WaitShowDialogue("You gave the notebook and writing tool back to him.")
UI:SetCenter(false)
GAME:WaitFrames(20)

UI:SetSpeaker(AdamMudkip)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Ok, [pause=10]lemme see here real quick...")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['PlayerName'], player:GetDisplayName()))
UI:WaitShowDialogue("Thanks. [pause=0]Sit here for a second please, [pause=10]I gotta do the song and dance with [color=#00FFFF]Chatot[color] real quick.")

GROUND:EntTurn(Piks, Direction.Up)
GROUND:MoveInDirection(AdamMudkip, Direction.Up, 25, false, 1)

GROUND:CharSetEmote(AdamMudkip, "exclaim", 1)
SOUND:PlayBattleSE("EVT_Emote_Exclaim")
GROUND:CharAnimateTurn(player, Direction.Up, 4, false) --There's really no way to make the character turn with someone else's walking without jags in the animation, that just feels impossible. / Irritation is getting on my f---ing nerves. / There's definently a way, but it's rather complicated to set up.
																										--What in the world was I complaining about here?
GROUND:MoveInDirection(Chatot, Direction.Down, 40, false, 2)

UI:SetSpeaker(Chatot)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Attention, [pause=10]Team [color=#ffb5fd]Electrater[color]. [pause=0]I got some news for all of you.")
UI:WaitShowDialogue("[color=#54ebaf]Madilyn[color], [pause=10]there's been a slew of Pokémon waiting for you to show up.")
UI:WaitShowDialogue("It'd be best if you hurry down there now, [pause=10]they've been waiting all day.")

	GROUND:CharSetEmote(Madilyn, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GAME:WaitFrames(40)
	
UI:SetSpeaker(Madilyn)
UI:SetBounds(10,10,300,45)
UI:SetSpeakerLoc(10,65)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Yeah yeah, [pause=10][color=#00FFFF]Chatot[color]. [pause=0]I know that already.")

GROUND:MoveInDirection(Madilyn, Direction.Up, 15, false, 2)
GROUND:MoveInDirection(Madilyn, Direction.UpRight, 10, false, 2)
GROUND:EntTurn(Chatot, Direction.DownRight)
GROUND:MoveInDirection(Madilyn, Direction.Up, 80, false, 2)
GROUND:EntTurn(Chatot, Direction.Down)

GAME:WaitFrames(10)

UI:SetSpeaker(Chatot)
UI:ResetBounds()
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("[color=#54ebaf]Adam[color], [pause=10][color=#54ebaf]Piks[color], [pause=10]and... [pause=20]whoever you are.")
UI:WaitShowDialogue("I've thought a bit about it. [pause=10]The guildmaster wouldn't like it if I left your recruit out here...")
UI:WaitShowDialogue("I'd rather not make her upset, [pause=10]so please come in.")

GROUND:EntTurn(Piks, Direction.UpLeft)
GROUND:CharAnimateTurn(AdamMudkip, Direction.DownRight, 4, false)
GAME:WaitFrames(30)

GROUND:CharAnimateTurn(AdamMudkip, Direction.Up, 4, true)

local coro1 = TASK:BranchCoroutine(function() cutsceneguildent.EnterGuild_Sequence(AdamMudkip) end)
local coro2 = TASK:BranchCoroutine(function() cutsceneguildent.EnterGuild_Sequence(player) end)
local coro3 = TASK:BranchCoroutine(function() cutsceneguildent.EnterGuild_Sequence(Piks) end)
local coro4 = TASK:BranchCoroutine(function() cutsceneguildent.EnterGuild_Sequence(Chatot) end)
local coro5 = TASK:BranchCoroutine(function() cutsceneguildent.EnterGuild_Sequence(Game) end)

GAME:FadeOut(false, 30)
TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5})

GAME:WaitFrames(40)
GAME:EnterZone('cutscenezone', -1, 3, 0)

GAME:CutsceneMode(false)

end

function cutsceneguildent.FadeInWalkLeft_Sequence(character)
GROUND:MoveInDirection(character, Direction.Left, 40, false, 1)
end

function cutsceneguildent.FadeInWalkLeft2_Sequence(character)
GAME:FadeIn(20)
end

function cutsceneguildent.TrioWalkIn_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 100, false, 1)
end

function cutsceneguildent.TurnAround_Sequence(character)
GROUND:CharAnimateTurn(character, Direction.Up, 4, true)
end

function cutsceneguildent.EnterGuild_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 120, false, 1)
end

return cutsceneguildent
