--[[
    init.lua
    Created: 02/12/2024 21:44:11
    Description: Autogenerated script file for the map cutscenethieveshideout.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local cutscenethieveshideout = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cutscenethieveshideout.Init(map)
--Engine callback function
function cutscenethieveshideout.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cutscenethieveshideout.Enter(map)
--Engine callback function
function cutscenethieveshideout.Enter(map)

GROUND:AddMapStatus("dark")
CutsceneThieves()

end

---cutscenethieveshideout.Exit(map)
--Engine callback function
function cutscenethieveshideout.Exit(map)


end

---cutscenethieveshideout.Update(map)
--Engine callback function
function cutscenethieveshideout.Update(map)


end

---cutscenethieveshideout.GameSave(map)
--Engine callback function
function cutscenethieveshideout.GameSave(map)


end

---cutscenethieveshideout.GameLoad(map)
--Engine callback function
function cutscenethieveshideout.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function CutsceneThieves()
local Thievul = CH('Thievul')
local Purrloin = CH('Purrloin')
local ScraftyA = CH('ScraftyA')
local ScraftyB = CH('ScraftyB')
local player = CH('PLAYER')

local StopPacing = false
local rotationPurrloin = false
local pcSpecies = _DATA:GetMonster(CH('PLAYER').CurrentForm.Species):GetColoredName()

GAME:CutsceneMode(true)
GAME:MoveCamera(248, 224, 1, false)
GAME:FadeIn(20)

local coro1 = TASK:BranchCoroutine(function()

GROUND:MoveInDirection(Thievul, Direction.Left, 30, false, 1)
GROUND:CharAnimateTurn(Thievul, Direction.Right, 4, false)
GAME:WaitFrames(10)

while not StopPacing do

GROUND:MoveInDirection(Thievul, Direction.Right, 60, false, 1)
GROUND:CharAnimateTurn(Thievul, Direction.Left, 4, true)
GAME:WaitFrames(10)
GROUND:MoveInDirection(Thievul, Direction.Left, 60, false, 1)
GROUND:CharAnimateTurn(Thievul, Direction.Right, 4, false)
GAME:WaitFrames(10)

end
end)

local coro2 = TASK:BranchCoroutine(function()

while not rotationPurrloin do

GROUND:CharTurnToCharAnimated(Purrloin,Thievul, 3)
GAME:WaitFrames(10)

end
end)

UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Grr... [pause=20]we've prowled the eastern side of this stupid sunny region... [pause=20]where is that [color=#00F8F8]".. pcSpecies .."[color]!?") --[color] tags are completely ignored for some reason...

GAME:WaitFrames(10)

UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Normal", true)
UI:SetSpeakerLoc(264,131)
UI:WaitShowDialogue("You mean that ".. GenderCheck(player, "one", false) .." with the medallion?")

GAME:WaitFrames(10)
--GROUND:CharTurnToCharAnimated(Thievul, Purrloin, 3)
GAME:WaitFrames(10)

GROUND:CharSetEmote(Thievul, "angry", 0)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("Yes, [pause=10]that annoying twig!")
StopPacing = true
UI:WaitShowDialogue(GenderCheck(player, "they've", true) .." been holding that medallion for long enough!")

	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(Purrloin, "sweating", 1)
	rotationPurrloin = true
	GAME:WaitFrames(40)
	
UI:SetSpeaker(Purrloin)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Mm...")
UI:WaitShowDialogue("I'm a little confused about your obsession with that piece of jewelry...")

GROUND:CharSetEmote(Thievul, "", 0)
GROUND:EntTurn(Thievul, Direction.DownRight)
GAME:WaitFrames(10)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Hmph... [pause=20]What about it?")
UI:WaitShowDialogue("That little thing is much more valuable than what you'll find in the [color=#FFC663]Miracle Sea[color].")

	SOUND:PlayBattleSE("EVT_Emote_Shock")
	GROUND:CharSetEmote(Purrloin, "shock", 1)
	GAME:WaitFrames(30)
	
UI:SetSpeaker(Purrloin)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Surprised", true)
UI:WaitShowDialogue("Whuh!? [pause=0]Something more valuable than...?!")
UI:WaitShowDialogue("Nobody's allowed down there! [pause=0]There's no way the treasure there is less valuable than that muddy medallion!")

GAME:WaitFrames(10)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Oh, [pause=10]it is...")
UI:WaitShowDialogue("But first, [pause=10]we need to get it back from that ".. pcSpecies ..". [pause=0]Then we can discuss why it's so valuable...")

	GROUND:EntTurn(Purrloin, Direction.Left)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GROUND:CharSetEmote(Purrloin, "sweatdrop", 1)
	GAME:WaitFrames(30)

UI:SetSpeaker(Purrloin)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Uh, [pause=10]sure...")
UI:WaitShowDialogue("It better be as valuable as you say it is...")

GROUND:EntTurn(Thievul, Direction.Right)
GAME:WaitFrames(10)

coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(Thievul, Direction.Right, 28, false, 1)
end)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I know it is. [pause=0]That's all you need to know.")

GAME:WaitFrames(10)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(Purrloin, "exclaim", 1)
	GROUND:CharSetEmote(Thievul, "exclaim", 1)
	
	SOUND:PlayBGM("None", true)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:WaitShowDialogue("Oi, [pause=10]"..CH("Thievul"):GetDisplayName() .."!")

coro1 = TASK:BranchCoroutine(function()
GROUND:CharAnimateTurn(Thievul, Direction.Down, 4, false)
end)

coro2 = TASK:BranchCoroutine(function()
GROUND:CharAnimateTurn(Purrloin, Direction.Down, 4, true)
end)

GAME:WaitFrames(10)

coro1 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(ScraftyA, Direction.Up, 93, false, 2)
end)

coro2 = TASK:BranchCoroutine(function()
GROUND:MoveInDirection(ScraftyB, Direction.Up, 86, false, 2)
end)

GAME:WaitFrames(90)
UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Oh, [pause=10]it's you two.")
UI:WaitShowDialogue("Let me guess, [pause=10]those bruises are from a fight?")

GAME:WaitFrames(10)
UI:SetSpeaker(ScraftyB)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Yeah... [pause=20]we lost harshly.")
UI:WaitShowDialogue("The [color=#00F8F8]Zigzagoons[color] ran away with our food too. [pause=0]So much for their help...")

SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(Thievul, "sweatdrop", 1)
GAME:WaitFrames(30)

UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("That's great... [pause=20]How did you possibly lose? [pause=0]Who was there?")

GAME:WaitFrames(10)
UI:SetSpeaker(ScraftyA)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("Uh, [pause=10]let's see...")
UI:WaitShowDialogue("There was a [color=#00F8F8]Kecleon[color] and a [color=#00F8F8]Skiddo[color]...")

GAME:WaitFrames(10)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("They don't sound too strong. [pause=0]Anyone else that actually knows how to fight?")

SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(ScraftyB, "sweatdrop", 1)
GAME:WaitFrames(30)

UI:SetSpeaker(ScraftyB)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I guess a [color=#00F8F8]Piplup[color] with a black and white scarf...")

SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
GROUND:CharSetEmote(Thievul, "sweatdrop", 1)
GROUND:CharAnimateTurn(Thievul, Direction.Up, 4, true)
GAME:WaitFrames(30)

UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Oh great... [pause=20]That must've been [color=#54ebaf]Madilyn[color]. [pause=0]You weren't followed by her, [pause=10]right?")

SOUND:PlayBattleSE("EVT_Emote_Confused")
GROUND:CharSetEmote(ScraftyB, "question", 1)
GAME:WaitFrames(40)

UI:SetSpeaker(ScraftyB)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I don't think so... [pause=20]we split up, [pause=20]so I don't think she could've chased us both.")
UI:WaitShowDialogue("But there was one more in her group, [pause=10]a ".. pcSpecies ..".")

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(Thievul, "shock", 1)
GAME:WaitFrames(30)
GROUND:CharAnimateTurn(Thievul, Direction.Down, 4, true)

UI:SetSpeaker(Thievul)
UI:SetSpeakerEmotion("Angry")
GROUND:CharSetEmote(Thievul, "angry", 0)
UI:WaitShowDialogue("WHAT!?!?")
UI:WaitShowDialogue("WHAAAAAAAAAAT!?!?")
UI:WaitShowDialogue("You're telling me that little runt is working with those muppets!?")

SOUND:PlayBattleSE("EVT_Emote_Shock")
GROUND:CharSetEmote(ScraftyA, "shock", 1)
GROUND:CharSetEmote(ScraftyB, "shock", 1)
GAME:WaitFrames(30)

UI:SetSpeaker(ScraftyA)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Surprised", true)
UI:WaitShowDialogue("W-what if they are?? [pause=0]Can't we just lure that ".. pcSpecies .." out and ambush ".. GenderCheck(player, "them", false) .."?")

GROUND:CharAnimateTurn(Purrloin, Direction.UpLeft, 4, false)
GAME:WaitFrames(10)

UI:SetSpeaker(Purrloin)
UI:SetSpeakerEmotion("Normal", true)
--UI:SetSpeakerLoc(264,131)
UI:WaitShowDialogue("It would be pretty easy once we set it up correctly...")
GAME:WaitFrames(10)
GROUND:EntTurn(Thievul, Direction.DownRight)
GROUND:EntTurn(ScraftyA, Direction.UpRight)
GROUND:EntTurn(ScraftyB, Direction.UpRight)
GROUND:CharSetEmote(Thievul, "", 0)
UI:WaitShowDialogue(GenderCheck(player, "they don't", true) .." have a partner. [pause=0]".. GenderCheck(player, "they'll", true) .." be all alone for the ambush. ♪")

GROUND:CharAnimateTurn(Thievul, Direction.Up, 4, true)

UI:SetSpeaker(Thievul)
UI:ResetSpeakerLoc()
UI:SetSpeakerEmotion("Happy")
GROUND:EntTurn(ScraftyA, Direction.Up)
GROUND:EntTurn(ScraftyB, Direction.Up)
UI:WaitShowDialogue("Grah hah hah hah!")

coro1 = TASK:BranchCoroutine(function()
GAME:FadeOut(false, 60)
end)

UI:WaitShowDialogue("What a perfect foil! [pause=0]That fool won't know what hit ".. GenderCheck(player, "them", false) .."!")

GAME:WaitFrames(120)

UI:WaitShowTitle("Chapter Two: \nDon't Shirk Work!", 60)
GAME:WaitFrames(60)
UI:WaitHideTitle(60)

SV.chapter.number = 2

UI:WaitShowVoiceOver("The next morning...", -1)

GAME:EnterZone('treasuretownzone', -1, 16, 0)

GAME:CutsceneMode(false)
end

function GenderCheck(chara, form, uppercase) --Uppercase?

    local gender = chara.CurrentForm.Gender --Ripped straight from Halcyon / I lied, there's more.
    local value = ""
    
    if gender == Gender.Female then
        local female_pronouns = {
            ["one"] = "girl",
			["they've"] = "she's",
			["they'll"] = "she'll",
			["they don't"] = "she doesn't",
			["them"] = "her",
        }
        value = female_pronouns[form]
    elseif gender == Gender.Male then
        local male_pronouns = {
            ["one"] = "boy",
			["they've"] = "he",
			["they'll"] = "he'll",
			["they don't"] = "he doesn't",
			["them"] = "him",
        }
        value = male_pronouns[form]
    else -- if neither male or female, use they/them, so just return the form 
        value = form
    end

return uppercase and value:gsub("^%l", string.upper) or value

end

return cutscenethieveshideout

