--[[
    init.lua
    Created: 07/02/2023 09:11:32
    Description: Autogenerated script file for the map wigglyguildbedmoon.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildbedmoon = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildbedmoon.Init(map)
--Engine callback function
function wigglyguildbedmoon.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildbedmoon.Enter(map)
--Engine callback function
function wigglyguildbedmoon.Enter(map)
local dontresetday = true

  if SV.chapter.number == 0 then
  dontresetday = false
  wigglyguildbedmoon.FinalPrologueCS(finally)
  elseif SV.chapter.number == 1 then
	if SV.chapter1.thieves_defeated then
		  dontresetday = false
		wigglyguildbedmoon.SemiFinalChapter1CS()
	end
  else
  
  end
  
	if dontresetday then
    wigglyguildbedmoon.BedtimeCasual(resetday)
    end
	
end

---wigglyguildbedmoon.Exit(map)
--Engine callback function
function wigglyguildbedmoon.Exit(map)


end

---wigglyguildbedmoon.Update(map)
--Engine callback function
function wigglyguildbedmoon.Update(map)


end

---wigglyguildbedmoon.GameSave(map)
--Engine callback function
function wigglyguildbedmoon.GameSave(map)


end

---wigglyguildbedmoon.GameLoad(map)
--Engine callback function
function wigglyguildbedmoon.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function wigglyguildbedmoon.FinalPrologueCS(finally)
local player = CH('PLAYER')
local Piks = CH('Piks')
GAME:CutsceneMode(true)

GAME:FadeIn(20)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(I'm pretty exhausted after today...)")
UI:WaitShowDialogue("(I should really get some rest in before tomorrow.)")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(I wonder if this medallion, [pause=10]in any way, [pause=10]shape or form, [pause=10]causes a dungeon to behave strangely?)")
UI:WaitShowDialogue("...")
UI:WaitShowDialogue("(I guess I won't know for now...)")

GAME:WaitFrames(30)

UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['BusinessBeforeSleeping'], player:GetDisplayName()))

GROUND:CharAnimateTurn(player, Direction.Left, 4, false)
GROUND:MoveInDirection(Piks, Direction.Right, 60, false, 2)
GAME:WaitFrames(20)

UI:SetSpeaker(Piks)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Sorry for taking more of your time, [pause=10]and sorry if the room's very dusty.")
UI:WaitShowDialogue("I do come with various things you're going to want if you're going to explore these dungeons.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("I *do* find it weird that the guild didn't have equipment for you.")
UI:WaitShowDialogue("Not sure how they ran out of recruit items. [pause=0]I thought they'd usually stock up if a new wave of Pokémon appears.")
GROUND:EntTurn(Piks, Direction.UpRight)
GAME:WaitFrames(10)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Ah, [pause=10]hold on... [pause=20]There we go!")
GROUND:EntTurn(Piks, Direction.Right)
GAME:WaitFrames(10)
GROUND:MoveInDirection(Piks, Direction.Right, 15, false, 1)
SOUND:PlayBattleSE("EVT_CH02_Item_Place")

UI:ResetSpeaker(false)
UI:SetSpeakerEmotion("Normal")
UI:SetCenter(true)
UI:WaitShowDialogue("The [color=#00FFFF]Pikachu[color] hands you a better version of your [color=#32a852]Treasure Bag[color]. [pause=0]Inside the bag is a Map, and a custom badge.")
_DATA.Save.ActiveTeam:SetRank("normal")
UI:SetCenter(false)

GAME:WaitFrames(20)
UI:SetSpeaker(Piks)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("The bag might be a little... [pause=20]hand-me-downish. [br]It's the same bag when we started out, [pause=10]so don't break it, [pause=10]or lose it, [pause=10]or anything.")
UI:WaitShowDialogue("Oh, [pause=10]and please don't lose that badge either. [pause=0]It's hard to get replacements for badges like those.")
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("...and very expensive.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['NightPlayer'], player:GetDisplayName()))

GROUND:MoveInDirection(Piks, Direction.Left, 120, false, 2)

GAME:WaitFrames(40)
GROUND:CharAnimateTurn(player, Direction.Up, 4, false)
GAME:WaitFrames(10)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(It's starting to get a bit late.)")
UI:WaitShowDialogue("(I should get to bed.)")

GAME:FadeOut(false, 30)
SOUND:PlayBattleSE("EVT_CH03_Boss_Collapse")
GAME:WaitFrames(30)

UI:ResetSpeaker()
UI:WaitShowDialogue("(This is it, [pause=10]I'm starting to work for some high-ranking explorers.)")
UI:WaitShowDialogue("(I better do an outstanding job tomorrow.)")
GAME:WaitFrames(30)

UI:WaitShowDialogue("(It's actually pretty exciting, [pause=10]what will I discover on this small journey of mine?)")
UI:WaitShowDialogue("(Where will I go, [pause=10]and what different kinds of Pokémon will I meet?)")
UI:WaitShowDialogue("(Well... [pause=20]there's only one way I'm going to find out.)")

SOUND:PlayBGM("None", true)
GAME:WaitFrames(60)

SV.chapter.number = 1
SV.repeatable.day_finished = true

--UI:WaitShowTitle("Chapter: Prologue \nComplete", 80)
--GAME:WaitFrames(60)
--UI:WaitHideTitle(60)
GAME:WaitFrames(40)
UI:WaitShowTitle("Chapter One: \nThe Investigations Start", 60)
GAME:WaitFrames(60)
UI:WaitHideTitle(60)

SOUND:PlaySE("Fanfare/Note")
UI:ResetSpeaker()
UI:SetCenter(true)
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['AdviceBulletin3']))
UI:WaitShowDialogue("[color=#54ebaf]Sky-Green Names are important characters to the story.[color]")
UI:WaitShowDialogue("[color=#54ebaf]They will provide hints and tips to help you progress the game.[color]")
UI:WaitShowDialogue("[color=#9696ff]Dull-Blue Names are non-important characters to the story.[color]")
UI:WaitShowDialogue("[color=#9696ff]They are often cameos from friends, and do not progress the game.[color]")

GAME:WaitFrames(30)

UI:WaitShowVoiceOver("The next morning...", -1)

GAME:EnterGroundMap("wigglyguildbedsun", "Entrance")

GAME:CutsceneMode(false)
end

function wigglyguildbedmoon.BedtimeCasual(resetday)
SOUND:PlayBGM("Goodnight.ogg", true)
local player = CH('PLAYER')
GAME:CutsceneMode(true)

GAME:FadeIn(20)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(Looks like today's over.)")
UI:WaitShowDialogue("(I should get some sleep for tomorrow.)")

	if not SV.chapter1.meeting_partA then
local tasks = {
    ["Mossy Outcroppings"] = SV.dungeons.mossyoutcroppings,
    ["Seaside Serenade"] = SV.dungeons.seasideserenade,
    ["Cackling Quarry"] = SV.dungeons.cacklingquarry
} --I own absolutely no right for this code, all of it goes to Sunkern.

local completed = {}
local to_do = {}

for name, flag in pairs(tasks) do
    if flag then
        table.insert(completed, name)
    else
        table.insert(to_do, name)
    end
end

if #completed == 3 then
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(Looks like I finished my assignment on the dungeons!)")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("(Tomorrow, I have to share these with Team [color=#ffb5fd]Electrater[color].)")
	UI:WaitShowDialogue("(I hope they can use this information somehow.)")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("(But there was nothing in those places. [pause=0]Worse yet, [pause=10]not even a single lead...)")
elseif #completed == 2 then
    UI:WaitShowDialogue(
        string.format("(I finished my reports on [color=#FFC663]%s[color] and [color=#FFC663]%s[color].)", completed[1], completed[2])
    )
    UI:WaitShowDialogue(
        string.format("(The last one I need to do is [color=#FFC663]%s[color].)", to_do[1])
    )
elseif #completed == 1 then
    UI:WaitShowDialogue(
        string.format("(I got [color=#FFC663]%s[color] done, [pause=10]and I've got two more to do tomorrow.)", completed[1])
    )
elseif #completed == 0 then
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("(I need to step up my game... [pause=20]I got nothing on my report...)")
	end
end

GAME:FadeOut(false, 30)
SOUND:PlayBGM("None", true)
SV.repeatable.day_finished = true
SV.repeatable.daily_chant = false
GAME:WaitFrames(50)

	UI:SetCenter(true)
	UI:SetAutoFinish(true)

UI:WaitShowVoiceOver("The next morning...", -1)

	UI:SetCenter(false)
	UI:SetAutoFinish(false)

GAME:EnterGroundMap("wigglyguildbedsun", "Entrance")

GAME:CutsceneMode(false)
end

function wigglyguildbedmoon.SemiFinalChapter1CS()
local player = CH('PLAYER')
GROUND:TeleportTo(player, 152, 144, Direction.Up)
GAME:MoveCamera(156, 176, 1, false)
GAME:CutsceneMode(true)

GAME:WaitFrames(20)

    UI:WaitShowBG("Moonlight", 1, 40);
	GAME:WaitFrames(120)
	UI:WaitHideBG(40)
	
GAME:FadeIn(30)
GAME:WaitFrames(30)

SOUND:PlayBGM("Goodnight.ogg", true)

UI:SetSpeaker(player, false)
UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("(Another day went by...)")
UI:WaitShowDialogue("(But I feel like I didn't accomplish much...)")

GROUND:CharAnimateTurn(player, Direction.Down, 4, false)
GAME:WaitFrames(10)

--UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("(Maybe I should ask [color=#ffb5fd]Electrater[color] about this medallion when I get the oppertunity.)")
UI:WaitShowDialogue("(They must know something about it...)")

GROUND:CharAnimateTurn(player, Direction.Up, 4, true)
GAME:WaitFrames(30)

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("(I should head to sleep...)")
UI:WaitShowDialogue("(It's getting rather late.)")

GAME:FadeOut(false, 60)

GAME:WaitFrames(60)
SOUND:PlayBGM("None", true)

    UI:WaitShowBG("Moonlight", 1, 40);
	GAME:WaitFrames(120)
	UI:WaitHideBG(40)
	GAME:UnlockDungeon('roadwalkpathway')

SV.repeatable.day_finished = true
SV.repeatable.daily_chant = false

GAME:EnterZone('cutscenezone', -1, 6, 0)

GAME:CutsceneMode(false)
end

return wigglyguildbedmoon

