--[[
    init.lua
    Created: 02/08/2023 22:02:41
    Description: Autogenerated script file for the map wigglyguildent.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local wigglyguildent = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---wigglyguildent.Init
--Engine callback function
function wigglyguildent.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---wigglyguildent.Enter
--Engine callback function
function wigglyguildent.Enter(map)
GROUND:Hide("Madilyn")
wigglyguildent.SetupGround()
if SV.chapter.number == 1 and not SV.chapter1.apricorn_tutorial then
		GROUND:Unhide("Madilyn")
		wigglyguildent.ApricornTut()
end

COMMON.WeatherApply()

  GAME:FadeIn(20)

end

---wigglyguildent.Exit
--Engine callback function
function wigglyguildent.Exit(map)


end

---wigglyguildent.Update
--Engine callback function
function wigglyguildent.Update(map)


end

---wigglyguildent.GameSave
--Engine callback function
function wigglyguildent.GameSave(map)


end

---wigglyguildent.GameLoad
--Engine callback function
function wigglyguildent.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function wigglyguildent.Chatot_Action(chara, activator) --hide him later, because deleting him might be a bit much. / Rewrite in order? I dunno, might need reactions first. / Rewrote his intro anyways.
local player = CH('PLAYER')

	if not SV.prologue_alts.chatot_greeted then
UI:SetSpeaker(chara)
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Ugh, [pause=10]this headache won't go away...")
UI:WaitShowDialogue("It's been bouncing around since I thought someone threw a pebble at me this morning.")
UI:WaitShowDialogue("I hope it goes away, [pause=10]but I somehow doubt I'm that lucky...")

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_Idea")
    GROUND:CharSetEmote(chara, "exclaim", 1)
	GAME:WaitFrames(30)
	
GROUND:CharTurnToCharAnimated(chara, player, 4)
	GAME:WaitFrames(20)
	
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Oh, [pause=10]hello there. [pause=0]I did not see you there... [pause=20]you're awfully quiet.")
	UI:WaitShowDialogue("Now shoo. [pause=0]We're not letting any visitors inside.")
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue("...Do not tilt your head at me, [pause=10]no means no. [pause=0]No visitors inside for today.")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Now go away please.")
	
	SV.prologue_alts.chatot_greeted = true

	elseif SV.prologue_alts.chatot_greeted then

GROUND:CharTurnToChar(chara, player)

	UI:SetSpeaker(chara)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Run along now, [pause=10]I'm not going to change my answer.")
	
	else
	end
		end

function wigglyguildent.Leave_Touch(obj, activator)

GAME:FadeOut(false, 20)
GAME:EnterGroundMap("treasuretowncrossroads", "EntranceUp")

end

function wigglyguildent.Gate_Action(obj, activator) --I don't want you in the guild too early, but I do eventually want you inside it. / Be the same trigger that lets you through.
local player = CH('PLAYER')

	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("(It's a closed gate, [pause=10]it's too heavy to lift it out of the way.)")
	
		if SV.prologue_alts.chatot_greeted then
	UI:WaitShowDialogue("(Even if I could, [pause=10]I still shouldn't do it in front of someone who's stern with keeping me out.)")
		end
		
end

function wigglyguildent.InteractiveNearby_Touch(obj, activator)

SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(activator, "question", 1)

end

function wigglyguildent.SetupGround() --Palika's script for adding a real-fake door in the Groundmap. Yes, this comment is a reference. Go play Halycon instead of this.
    local door = RogueEssence.Ground.GroundObject(RogueEssence.Content.ObjAnimData("Door", 1, 0, 0), --Spawn an object with it's object being the Door.
                                                    RogueElements.Rect(216, 136, 48, 16), --X LOC / Y LOC / XSZE / YSZE
                                                    RogueElements.Loc(-8, 8), --Offsets
                                                    false, --Passthrough?
                                                    "Door_Exit") --Name
    door:ReloadEvents()
    GAME:GetCurrentGround():AddTempObject(door) --Add that temporary object.
    
	if SV.chapter.number >= 1 then
	GROUND:Hide("Chatot")
	GROUND:Hide("InteractiveNearby")
    GROUND:Hide('Door_Exit')
	GROUND:Hide('Gate')
	end
    --GAME:FadeIn(20)    --Should be unnecessary, as the game continues reading the Script.
end

function wigglyguildent.ApricornTut()
local player = CH('PLAYER')
local Madilyn = CH('Madilyn')

GAME:CutsceneMode(true)

local coro1 = TASK:BranchCoroutine(function() wigglyguildent.FadeInWalking_Sequence(Madilyn) end)
local coro2 = TASK:BranchCoroutine(function() wigglyguildent.FadeInWalking2_Sequence(player) end)

TASK:JoinCoroutines({coro1,coro2})

	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
    GROUND:CharSetEmote(Madilyn, "exclaim", 1)
	GAME:WaitFrames(30)
	
	UI:SetSpeaker(Madilyn)
	UI:SetSpeakerEmotion("Normal")
	--UI:WaitShowDialogue("...")
	UI:WaitShowDialogue("...[pause=0]Oh. [pause=0]You're the new trainee, [pause=10]or whatever.")
	UI:WaitShowDialogue("I don't really want to talk to you. [pause=0]I came to grab jobs off the board, [pause=10]and be on my way.")
	UI:WaitShowDialogue("But since I'm here, [pause=10]I might as well teach you something.")
	
	UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['StartApricornTut']), false)
	UI:WaitForChoice()
	ch = UI:ChoiceResult()
if ch then
    wigglyguildent.AreYouSure()
else
    wigglyguildent.ApricornTutorial()
end

GAME:CutsceneMode(false)

end

function wigglyguildent.ApricornTutorial()
local player = CH('PLAYER')
local Madilyn = CH('Madilyn')

GAME:CutsceneMode(true)

UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['ApricornTutorialStart']))
UI:WaitShowDialogue("[color=#32a852]Apricorns[color] are... [pause=20]well, [pause=10]I don't know what they are.")
UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("Certainly not a fruit, [pause=10]or a vegetable. [pause=0]You can't eat it or anything.")
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("But the thing is, [pause=10]Pokémon in dungeons want these things for one reason or another.")
UI:WaitShowDialogue("Throw one of these [color=#32a852]Apricorns[color] at them, [pause=10]and they'll follow you.")
UI:WaitShowDialogue("I personally prefer to travel alone, [pause=10]so take these with you.")

GAME:WaitFrames(10)

GAME:GivePlayerItem('apricorn_plain', 3) --Experimental, let's see how it goes. / Works just fine.
SOUND:PlayFanfare("Fanfare/Item")

UI:ResetSpeaker(false)
UI:SetCenter(true)
UI:WaitShowDialogue("You received a few [color=#32a852]Plain Apricorns[color].")
UI:SetCenter(false)

GAME:WaitFrames(10)

UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("I have to get going.")
UI:WaitShowDialogue("You probably should too. [pause=0][color=#ffb5fd]Electrater[color] has a job for you.")
UI:WaitShowDialogue("Just follow the signs to [color=#FFC663]Sharpedo Bluff[color], [pause=10]you can't miss it.")

GROUND:MoveInDirection(Madilyn, Direction.Up, 10, false, 2)
GROUND:MoveInDirection(Madilyn, Direction.UpRight, 10, false, 2)
GROUND:MoveInDirection(Madilyn, Direction.UpLeft, 10, false, 2)
GROUND:Hide("Madilyn")

GAME:CutsceneMode(false)

SV.chapter1.apricorn_tutorial = true

GAME:CutsceneMode(false)

end

function wigglyguildent.AreYouSure()
local player = CH('PLAYER')
local Madilyn = CH('Madilyn')

GAME:CutsceneMode(true)
UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")

	UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['ApricornTutorialSkip']), false)
	UI:WaitForChoice()
	ch = UI:ChoiceResult()
if ch then
    wigglyguildent.ApricornTutorial()
else
    wigglyguildent.ApricornHotshot()
end

GAME:CutsceneMode(false)

end

function wigglyguildent.ApricornHotshot()
local player = CH('PLAYER')
local Madilyn = CH('Madilyn')

GAME:CutsceneMode(true)
UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Well, [pause=10]if you insist.")

GAME:WaitFrames(10)

GAME:GivePlayerItem('apricorn_plain', 3) --Experimental, let's see how it goes.
SOUND:PlayFanfare("Fanfare/Item")

UI:ResetSpeaker(false)
UI:SetCenter(true)
UI:WaitShowDialogue("You received a few [color=#32a852]Plain Apricorns[color].")
UI:SetCenter(false)

GAME:WaitFrames(10)

UI:SetSpeaker(Madilyn)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Someone like you should be able to figure out how to use these, [pause=10]then.")
UI:WaitShowDialogue("Also, [pause=10]Team [color=#ffb5fd]Electrater[color] wants you.")
UI:WaitShowDialogue("Just follow the signs to [color=#FFC663]Sharpedo Bluff[color], [pause=10]you can't miss it.")

GROUND:MoveInDirection(Madilyn, Direction.Up, 10, false, 2)
GROUND:MoveInDirection(Madilyn, Direction.UpRight, 10, false, 2)
GROUND:MoveInDirection(Madilyn, Direction.UpLeft, 10, false, 2)
GROUND:Hide("Madilyn")

GAME:CutsceneMode(false)

SV.chapter1.apricorn_tutorial = true

end

function wigglyguildent.Enter_Touch(obj, activator)

	GAME:FadeOut(false, 20)
	GAME:EnterGroundMap("wigglyguildtop", "EntranceDown")

end

function wigglyguildent.FadeInWalking_Sequence(character)
GROUND:MoveInDirection(character, Direction.Up, 25, false, 1)
end

function wigglyguildent.FadeInWalking2_Sequence(character)
GAME:FadeIn(20)
end

return wigglyguildent

