--[[
    init.lua
    Created: 12/25/2022 22:01:30
    Description: Autogenerated script file for the map ivysaurhomecs.
]]--
-- Commonly included lua functions and data
require 'what_does_n_stand_for.common'

-- Package name
local caretakerhomecs = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---ivysaurhomecs.Init
--Engine callback function
function caretakerhomecs.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---ivysaurhomecs.Enter
--Engine callback function
function caretakerhomecs.Enter(map)

NewCutscene()

end

---ivysaurhomecs.Exit
--Engine callback function
function caretakerhomecs.Exit(map)


end

---ivysaurhomecs.Update
--Engine callback function
function caretakerhomecs.Update(map)


end

---ivysaurhomecs.GameSave
--Engine callback function
function caretakerhomecs.GameSave(map)


end

---ivysaurhomecs.GameLoad
--Engine callback function
function caretakerhomecs.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function NewCutscene()
local player = CH('PLAYER')
local Fennekin = CH('Fennekin')
local Bellosom = CH('Bellosom')
local Celebi = CH('Celebi')

GAME:CutsceneMode(true)
GROUND:AddMapStatus("dark")
GROUND:CharSetAnim(player, "Sleep", true)

GAME:FadeIn(120)
GAME:WaitFrames(20)

UI:SetSpeaker(Fennekin)
UI:SetSpeakerEmotion("Sad")
UI:WaitShowDialogue(COMMON.GenderCheck(player, "they're", true) .." still breathing...")
UI:WaitShowDialogue("I'm still glad they managed to bring ".. COMMON.GenderCheck(player, "them", false) .." back to a warmer place than that snowy wasteland...")

GROUND:EntTurn(Fennekin, Direction.Right)
GROUND:EntTurn(Bellosom, Direction.Left)
GAME:WaitFrames(10)

UI:WaitShowDialogue("But how long will ".. COMMON.GenderCheck(player, "they", false) .." sleep for? [pause=0]".. COMMON.GenderCheck(player, "they", true) .." haven't eaten in several days...")
UI:WaitShowDialogue("We don't even know who ".. COMMON.GenderCheck(player, "they are", false) ..", [pause=10]or where ".. COMMON.GenderCheck(player, "they", false) .." came from...")

GAME:WaitFrames(10)

UI:SetSpeaker(Bellosom)
UI:SetSpeakerLoc(264,131)
UI:SetSpeakerEmotion("Worried", true)
UI:WaitShowDialogue("I'm as concerned as you are...")
UI:WaitShowDialogue("But nothing we've tried so far has woke ".. COMMON.GenderCheck(player, "them", false) .." up...")
UI:WaitShowDialogue("I sent a letter to [color=#00FFFF]Audino[color] over in [color=#FFC663]Serene Village[color], [pause=10]she might know how to fix this...")
UI:WaitShowDialogue("We'll just have to wait and see, [pause=10]".. CH('Fennekin'):GetDisplayName() ..".")
UI:WaitShowDialogue("Hopefully ".. COMMON.GenderCheck(player, "they'll", false) .." be awake by then, [pause=10]it should be a warm day tomorrow.")

local coro1 = TASK:BranchCoroutine(function()

GROUND:EntTurn(Fennekin, Direction.UpRight)
SOUND:PlayBattleSE("EVT_Emote_Sweating")
GROUND:CharSetEmote(Fennekin, "sweating", 1)
GAME:WaitFrames(40)
GROUND:CharAnimateTurn(Fennekin, Direction.Down, 4, false)
GROUND:MoveInDirection(Fennekin, Direction.Down, 60, false, 2)

end)

local coro2 = TASK:BranchCoroutine(function()

GROUND:CharAnimateTurn(Bellosom, Direction.Down, 4, true)
GROUND:MoveInDirection(Bellosom, Direction.Down, 60, false, 2)

end)

TASK:JoinCoroutines({coro1,coro2})

GAME:WaitFrames(180)

SOUND:PlayBattleSE("EVT_Seven_Treasures")

coro1 = TASK:BranchCoroutine(function()
		  local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Seven_Treasures", 3))
		  emitter.LocHeight = 1
		  GROUND:PlayVFX(emitter, 180, 160)
end)

coro2 = TASK:BranchCoroutine(function()

GAME:WaitFrames(120)
GAME:FadeOut(true, 20)
GAME:WaitFrames(20)
GROUND:Unhide("Celebi")

end)

TASK:JoinCoroutines({coro1,coro2})

GAME:FadeIn(30)
GAME:WaitFrames(60)

GROUND:CharAnimateTurn(Celebi, Direction.Right, 4, false)
GAME:WaitFrames(20)
GROUND:CharAnimateTurn(Celebi, Direction.Left, 4, true)
GAME:WaitFrames(20)
GROUND:CharAnimateTurn(Celebi, Direction.Up, 4, false)
GAME:WaitFrames(20)

UI:ResetSpeakerLoc()
UI:SetSpeaker(Celebi)
UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("Looks like I'm right on schedule...")
UI:WaitShowDialogue("[color=#00FFFF]Dialga[color] isn't going to like this, [pause=10]but I have no other choice.")

GROUND:MoveInDirection(Celebi, Direction.Up, 25, false, 1)

GAME:WaitFrames(40)
GROUND:EntTurn(Celebi, Direction.UpRight)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("Just as I suspected...")
SOUND:PlayBGM("Thoughts for Friends.ogg", true)
UI:WaitShowDialogue("Your injuries are quite severe...")

GROUND:EntTurn(Celebi, Direction.UpLeft)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Sad")
UI:WaitShowDialogue("...")
UI:WaitShowDialogue("[color=#00FFFF]Hoopa[color]'s immense strength shouldn't be used to silence others.")
--UI:SetSpeakerEmotion("Sad")
UI:WaitShowDialogue("And yet, [pause=10]they do so to gain more power.")
UI:WaitShowDialogue("This is magic far greater than anything I know... [pause=20]That Pokémon muzzled you with their psychic abilities.")
UI:WaitShowDialogue("That shouldn't be possible...")

GAME:WaitFrames(30)
GROUND:EntTurn(Celebi, Direction.Up)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Determined")
UI:WaitShowDialogue("If you can, [pause=10]listen to me ".. CH('PLAYER'):GetDisplayName() ..". [pause=0]You must stop that Pokémon!")
UI:WaitShowDialogue("[color=#00FFFF]Hoopa[color] can, [pause=10]and will cause mass destruction with whatever Pokémon they summon!")

GROUND:EntTurn(Celebi, Direction.UpRight)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Pain")
UI:WaitShowDialogue("The Heroes of Sky... [pause=20]The Heroine of Prospect...")
UI:WaitShowDialogue("...They cannot win this battle on their own...")

GROUND:EntTurn(Celebi, Direction.Up)
GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Normal")
UI:WaitShowDialogue("But I sense something about you... [pause=20]It's the same feeling those two shared when I first met them.")
UI:WaitShowDialogue("...Something akin to deja vu, [pause=10]and unpredictability.")
UI:SetSpeakerEmotion("Inspired")
UI:WaitShowDialogue("That's how I know you're special.")

GROUND:EntTurn(Celebi, Direction.UpRight)
GAME:WaitFrames(60)
GROUND:EntTurn(Celebi, Direction.Up)

GAME:WaitFrames(10)

UI:SetSpeakerEmotion("Worried")
UI:WaitShowDialogue("If I don't heal you now, [pause=10]this world will go back to darkness.")
UI:WaitShowDialogue("[color=#00FFFF]Hoopa[color] has that power, [pause=10]and I shall not let them use it for such a purpose.")
UI:WaitShowDialogue("Now, [pause=10]the thing that causes your sleep is a sort of corruption growing from your heart.")
UI:WaitShowDialogue("I can heal it, [pause=10]but the price is dire... [pause=40]your power.")
UI:WaitShowDialogue("Not ideal, [pause=10]but that's the only way I can heal your physical body from [color=#00FFFF]Hoopa[color]'s might.")
UI:WaitShowDialogue("But I cannot heal your voice, [pause=10]for such magic is too strong for my purification...")
UI:WaitShowDialogue("I'll make it up to you somehow...")

GAME:FadeOut(false, 30)
SOUND:PlayBGM("None", true)
GAME:WaitFrames(10)

UI:ResetSpeaker()

UI:WaitShowDialogue("I promise.")

GAME:WaitFrames(90)

GAME:CutsceneMode(false)
GAME:EnterGroundMap("cutsceneintrosharpedo4", "Entrance")

end

function OldCutscene() --DO NOT USE! Keeping for reference for later, or people like you snooping where you shouldn't be. Also literally breaks the game, as Ivysaur is not referenced (because he's deleted).

  local ivysaur = CH('Ivysaur')

  GAME:CutsceneMode(true)
  GAME:WaitFrames(30)

  GAME:FadeIn(20)
  
  GAME:WaitFrames(40)
  
  GROUND:MoveInDirection(ivysaur, Direction.Up, 40, false, 2)
		GAME:WaitFrames(10)
  GROUND:EntTurn(ivysaur, Direction.UpRight)
		GAME:WaitFrames(15)
	SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(ivysaur, "question", 1)
	GAME:WaitFrames(40)
	
	UI:SetSpeaker(ivysaur)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['WhatsWrong'], player:GetDisplayName()))
	
	GROUND:CharAnimateTurn(player, Direction.DownLeft, 4, true)
	--GAME:WaitFrames(15) --use if it doesn't stay on the turning
	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue("...")
	
		GAME:WaitFrames(25)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GROUND:CharSetEmote(ivysaur, "sweatdrop", 1)
		GAME:WaitFrames(40)
	
	UI:SetSpeaker(ivysaur)
	UI:SetSpeakerEmotion("Stunned")
	UI:WaitShowDialogue("Oh, [pause=10]right, [pause=10]I nearly forgot. You can't talk, [pause=15]can you? [br]It's only been a week, [pause=15]and I'm still not used to it yet. [pause=20]Sorry about that.")
		UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("But let's not dwell on the sadness right now, [pause=10]I'm going to give you something very important.")
	
	UI:SetSpeaker(player)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("...?")
	
    --GROUND:MoveInDirection(player, Direction.DownRight, 20, false, 1)
	--GAME:WaitFrames(20)
	GROUND:MoveInDirection(player, Direction.Down, 76, false, 1)
	GAME:WaitFrames(20)
	GROUND:EntTurn(ivysaur, Direction.Right)
	GAME:WaitFrames(1)
	GROUND:MoveInDirection(player, Direction.Left, 40, false, 1)
	GAME:WaitFrames(30)
	
	UI:SetSpeaker(ivysaur)
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue("I'm going to give you my old [color=#32a852]Treasure Bag[color]. [br]You have that look in your eyes, [pause=13]the one that look like you will do great things when you get older.")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Don't worry about me, [pause=15]I don't explore Mystery Dungeons anymore. [br]I'm a bit too old now, [pause=9]I want to settle down and enjoy the peaceful life left in this village.")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['PromiseMe'], player:GetDisplayName()))

		GAME:WaitFrames(40)
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(ivysaur, "sweating", 1)
		GAME:WaitFrames(40)
		
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue("Agh, [pause=20]I'm sorry, [pause=20]it's just hard to spit it out since this is what my old partner said to me...")
	UI:WaitShowDialogue("I want you to promise me you'll never give up, [pause=15]that you'll always get back on your feet, [br]even when the world might seem to be against you.")
	
	GAME:FadeOut(false, 40)
	
	UI:ResetSpeaker()
	UI:WaitShowDialogue("[color=#00f2ff]Ivysaur[color]: Promise this to me, [pause=30]please...")
	
	SOUND:PlayBGM("None", true)
	
	SV.cutscenepath.DreamDone = true
	GAME:CutsceneMode(false)
	
	GAME:WaitFrames(80)
	GAME:EnterZone('cutscenezone', -1, 0, 1)
	
	end

return caretakerhomecs

